### ISSUE TITLE
Broaden the academic areas in the description?

### ISSUE THREAD

**Issue by jisuoqing** [Future-Scholars/paperlib#116]
Currently, it is constantly repeated in GitHub / webpage that this tool is "for computer science", "CSers", etc.. However, I'd think the description unnecessarily limits the scope of usage. `PaperLib` is absolutely a great tool for paper management in many other academic areas (math and natural sciences), beyond CS.

I might want to suggest to revise the description and make the purpose of this tool for general academic papers, in order to broaden the potential impact of and attract people's interests in this tool in future. To highlight CS, the description could be rephrased into something like "with a variety of build-in metadata scrapers, including ones specially designed for computer science".

Anyway, it's up to you :)

**Comment by GeoffreyChen777** [comment]
Thanks for your suggestion.

Because of the focus of my own research topic, currently I only know that Paperlib performs well in CS. Although the scraper now supports customization, not everyone can do coding. I have no idea whether the built-in scrapers fit other research topics or not. Do you work in other research topic? Does Paperlib work well?

**Comment by jisuoqing** [comment]
As far as I'm concerned, most papers from astrophysics / fluid mechanics could be imported without any problem, with the built-in scrapers only. Some decades- old papers might not come with full metadata, but it's a relatively minor issue and could be fixed manually. The scraper customization, as you mentioned, is not that straightforward, but at least it opens up a possibility for future field-specific customization purposes. Users from other fields may chime in.

**Comment by GeoffreyChen777** [comment]
Thanks for your feedback, your research field is soooooo different from mine. 🤣

The scraper customization requires users need to know node.js programming. That's indeed not easy.

This weekend I will release v1.9.0 for two important features (RSS Feed subscription and markdown notes). By then, Paperlib will have all the features I imagined. After that I'll have time to edit the webpage and do the promotion to attract more researchers to use Paperlib.
