### ISSUE TITLE
API for other apps

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib#137]

**Comment by GeoffreyChen777** [comment]
@aur3l14no yes absolutely. I really love raycast.

But now I’m focusing on making the code architecture support extensions. So users can develop and publish extensions like they do in vscode.

After that I will try to implement this feature.

**Comment by yzlnew** [comment]
Looking forward to a Raycast extension to search papaers & Obsidian extension to sync notes elegantly.
