### ISSUE TITLE
[Question] Linux Deepin v20 issue

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib#143]

**Comment by genghisun** [comment]
催更～

**Comment by GeoffreyChen777** [comment]
😂原来真有人有需求，那我尽快弄一下

**Comment by genghisun** [comment]
> 😂原来真有人有需求，那我尽快弄一下

感谢！计算机专业用linux桌面的人还是挺多的

**Comment by GeoffreyChen777** [comment]
请参照 

https://paperlib.app/cn/blog/linux-install/

来使用 Linux 版本。如果有什么 Bug 请重启这个 Issue。

**Comment by genghisun** [comment]
AppImage打开一直加载
![截图_选择区域_20221010112223](https://user-images.githubusercontent.com/26201304/194803000-04f19f8b-d70e-43db-84c9-c7d7230e1e4e.png)
```
$ ./Paperlib.AppImage 
Checking for update
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[235793:1010/131843.058746:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Update for version 2.0.4 is not available (latest version: 2.0.4, downgrade is disallowed).
```

**Comment by GeoffreyChen777** [comment]
请说一下您的linux版本

**Comment by genghisun** [comment]
你好，我测试了一下，在Ubuntu 20.04.2 LTS上可以正常运行，在Deepin 20.7上无法运行

**Comment by GeoffreyChen777** [comment]
嗯嗯我ubuntu也是没问题。我装个deepin试下。

**Comment by genghisun** [comment]
谢谢，辛苦了

**Comment by GeoffreyChen777** [comment]
该问题是因为 Paperlib 的核心依赖库 Realm.js 需求 GLIBCXX_3.4.26，然而 deepin 20.7 基于 Debian 10 开发。其 glibc 版本太低，导致无法打开。

deepin 使用的还是2018年版本的 glibc，很多新发布的软件都无法在上面运行。而且 deepin 似乎对 glibc 的更新非常保守。根据其官方论坛的说法，他们准备 deepin 23 才升级 glibc。

详见

https://bbs.deepin.org/post/234462

所以目前的选择估计只有：

1）换 linux 发行版
2）换 deepin 23 预览版，我测试了是可以运行的。
3）等 deepin 正式更新了

实在抱歉。

**Comment by GeoffreyChen777** [comment]
> @GeoffreyChen777 请问是怎么诊断出问题在 glibc 的呀？我在 NixOS 上也遇到了这个问题，但 glibc 版本应该是没问题的

首先尝试`ctrl shift i` 或者 `F12` 之类的打开 electron 开发者工具，查看里面的报错内容

**Comment by GeoffreyChen777** [comment]
@aur3l14no 可以先去配置文件里面，把那个插件的快捷键手动改了。

Linux 的配置文件可能在 `~/.config` 里面？ 试试看
