### ISSUE TITLE
[Feature Request] Show sup file name

### ISSUE THREAD

**Issue by woodwm** [Future-Scholars/paperlib#177]
It seems that paperlib does not support multiple files for a paper. The reason for multiple files is the additional supplementary documents. For example, https://www.nature.com/articles/s41467-022-34303-8#Sec13 has supplementary Information, Peer Review File, Reporting Summary and source data.

**Comment by GeoffreyChen777** [comment]
It is supported. Just drag files into the details panel.

**Comment by woodwm** [comment]
Sorry about that. paperlib only shows the extension of a supplementary document. It works if it only has one supplementary document, but is confusing when it has multiple supplementary documents. Please considering show the name of a file. 

Show part of the name in the list of supplementary documents and show full name when the mouse hover over it.

**Comment by GeoffreyChen777** [comment]
> Sorry about that. paperlib only shows the extension of a supplementary document. It works if it only has one supplementary document, but is confusing when it has multiple supplementary documents of the same extensions. Please considering show the name of a file.
> 
> Show part of the name in the list of supplementary documents and show full name when the mouse hover over it.

Doable.

**Comment by invisprints** [comment]
It seems the supplementary file https://static-content.springer.com/esm/art%3A10.1038%2Fs41551-020-00682-w/MediaObjects/41551_2020_682_MOESM1_ESM.pdf cannot show in the paperlib. Could you please figure out what happen? The file is already downloaded but not shown in the software.

**Comment by GeoffreyChen777** [comment]
@invisprints Hi, could you please describe your operation?

I tried to attach this PDF to a paper, and everything looks ok.

Are you following the guide here?
https://paperlib.app/en/doc/getting-started.html#attach-supplementary-files

**Comment by invisprints** [comment]
Thanks, I didn't notice there is a guide.
I just tried to drag the file in the main view or use the browser extension.

**Comment by GeoffreyChen777** [comment]
> Thanks, I didn't notice there is a guide. I just tried to drag the file in the main view or use the browser extension.

If you drag and drop it into the mainview, it will be regarded as a main paper rather than a supplementary file.

**Comment by ZephyrZhang3** [comment]
Is anyone working on this feature? I'm ready to try it😁

**Comment by GeoffreyChen777** [comment]
@ZephyrZhang3

No. It's not easy. To implement this, we need to change the database schema. Currently, the supplementary file name is like `xxxxxx_id_sup0.pdf`. We need a new field for aliases.

**Comment by ZephyrZhang3** [comment]
> @ZephyrZhang3
> 
> No. It's not easy. To implement this, we need to change the database schema. Currently, the supplementary file name is like `xxxxxx_id_sup0.pdf`. We need a new field for aliases.

could we add its name just between 'id' and 'sup#'

**Comment by GeoffreyChen777** [comment]
> > @ZephyrZhang3
> > No. It's not easy. To implement this, we need to change the database schema. Currently, the supplementary file name is like `xxxxxx_id_sup0.pdf`. We need a new field for aliases.
> 
> could we add its name just between 'id' and 'sup#'

Sounds good, try it?

**Comment by ZephyrZhang3** [comment]
I'll try

**Comment by ZephyrZhang3** [comment]
Is there a pop-up window now? maybe pop a window to input sup name

**Comment by GeoffreyChen777** [comment]
> Is there a pop-up window now? maybe pop a window to input sup name

@ZephyrZhang3 I would suggest implementing a UI component consisting of a `<input>` and a button for sup. Just like the tag item in the left sidebar.

We can edit its name by right clicking it.

**Comment by ZephyrZhang3** [comment]
at adding time, use a random name or default like now, just show the extension name

**Comment by ZephyrZhang3** [comment]
I think the extension name `PDF` is better😏

**Comment by GeoffreyChen777** [comment]
> at adding time, use a random name or default like now, just show the extension name

@ZephyrZhang3 The default alias is empty, which yields a file name `xxx_id_sup0.pdf`. In UI, we show `PDF`

If users input an alias, say `ABC`, the filename should be `xxx_id_sup0_ABC.pdf`. We show `ABC.pdf` in UI.

Basically, you split the filename with `_`, and then we check the last element `filename_components.pop()`. If it starts with `sup`, we only show the extname. Otherwise, we show the last element.

Notably, users should not input an alias like `supX`. which means that `supX` is invalid.

**Comment by GeoffreyChen777** [comment]
Implemented.
