### ISSUE TITLE
[Feature Request] Separate notes or journal interface

### ISSUE THREAD

**Issue by woodwm** [Future-Scholars/paperlib#178]
Suggest adding a separate notes interface for research notes, daily journal or blog post.

![image](https://user-images.githubusercontent.com/13971199/198922661-a4d0fab6-b63b-4543-b613-fc2a8db3160d.png)

**Comment by GeoffreyChen777** [comment]
Could you please explain more about this? What is this notes?

**Comment by woodwm** [comment]
It is used to add notes that does not belong to a specific paper. Possible use case:

1. summary of a problem that are studied in multiple papers. The reference to these papers can be added in the note as well.
2. New idea that inspired from one or more papers. 
3. Notes for experiments or study.

**Comment by GeoffreyChen777** [comment]
Well, it sounds like some noting feature. I think it seems to be beyond the scope of a paper management software.

I do have some similar usecase, but I don't plan to implement this function in paperlib, I want paperlib to focus on paper management. I plan to implement this by providing an open API #137, so that many note app such as obsidian can communicate with paperlib through plugins.

**Comment by woodwm** [comment]
I think noting is a process of reference management. I am not sure about others. I think note on a paper is almost only useful for that paper. If you write more content of thinking and summary, the note can easily be forgotten for ever, because it is less easy to be found. Separate note interface offers a place to put those valuable notes together, which may or may not closely related to the papers, but must be useful for the research that you are working on.

**Comment by GeoffreyChen777** [comment]
That sounds reasonable to some extent.

I cannot fully understand: 

> a simple one with the list of notes (not notes added for a paper).

I think I can start from a seperated list of notes. This list contains all notes of all papers in your library. You can go to that paper by clicking a note. Is this the `simple one` you mentioned? Or you want a place to store some notes without linking to any papers?

But for more advanced noting feature, let's leave it open for now.

**Comment by woodwm** [comment]
What I am thinking is a place just for notes. No need to show the notes for all papers. It is used to write long content that does not target to a specific paper. An enhancement feature is to link to other papers and show in the right.

**Comment by GeoffreyChen777** [comment]
UI design is never a problem. The key problem is database. Currently, note is just a string property of a paper entity in the database:

https://github.com/GeoffreyChen777/paperlib/blob/c10c0e3a40a947fc0376ddc29ac397c04564b8fa/app/models/paper-entity.ts#L38

From this image, I guess you want a bi-link feature: a paper may link to 0 ~ N notes, a note can link to 0 ~ N papers.

That is cool. But it requires to fully redesign the backend database. 

Are you available to participate in this? I'm thinking about the coding work..... emmm... It may take a long time if I develop this by myself 😂...

**Comment by GeoffreyChen777** [comment]
> What I am thinking is a place mainly for new notes. No need to show the notes for all papers. It is used to write long content that does not target to a specific paper. An enhancement feature is to link to other papers and show in the right.

May I ask why not do this in a note-taking software such as obsidian, logseq, bear, craft, etc. if linking to a paper is not a nessasary feature?

**Comment by woodwm** [comment]
> > What I am thinking is a place mainly for new notes. No need to show the notes for all papers. It is used to write long content that does not target to a specific paper. An enhancement feature is to link to other papers and show in the right.
> 
> May I ask why not do this in a note-taking software such as obsidian, logseq, bear, craft, etc. if linking to a paper is not a nessasary feature?

Note-taking software certainly works. I just think separate note interface is a good feature to have for a reference management tool. It is not high priority.
