### ISSUE TITLE
[Feature Request] Add more icons to show the status

### ISSUE THREAD

**Issue by woodwm** [Future-Scholars/paperlib#179]
I suggest adding more icons to show the property of papers, such as

- paper type (journal paper, conference paper, thesis or book)
- has PDF or not (maybe click to open a file)
- has notes or not (maybe click to open the note)

**Comment by GeoffreyChen777** [comment]
Has pdf/note or not can be seen from the details panel. I'm wondering if they are really necessary in the mainview for most users. 

One key design principle of Paperlib is: No extra useless features.
