### ISSUE TITLE
Add "Recent Papers" in the left pane

### ISSUE THREAD

**Issue by woodwm** [Future-Scholars/paperlib#180]
"Recent papers" can contain papers that are recently added, opened.

![image](https://user-images.githubusercontent.com/13971199/198925476-1d0f48cb-8e73-400c-a5fb-36eb0e544ee8.png)

**Comment by GeoffreyChen777** [comment]
Try sort by addTime in the menu bar?

**Comment by woodwm** [comment]
Sorting by "Add Time" seems working, but it has limitations. To show recently added files, the user needs to sort in all papers which may be slow when there are hundreds of papers in it. It cannot show papers that I read yesterday or last few days.

**Comment by GeoffreyChen777** [comment]
Actually, I have tested 10k papers sorting. It is really fast, about 30ms.

About  `It cannot show papers that I read yesterday or last few days.`, seems that it requires a `lastOpenTime` property for each paper, right?

**Comment by woodwm** [comment]
Great. Then, we only need "recent read papers".

**Comment by GeoffreyChen777** [comment]
Ok, added to the roadmap, but with mid priority.

Please forgive me that I'm a PhD student and I have my own research work. I'm not sure I can implement it recently.

**Comment by woodwm** [comment]
Do not worry. It is not so important. Take your time and needs.

**Comment by GeoffreyChen777** [comment]
resolved with the help of the new smart filter feature #243
