### ISSUE TITLE
[Feature Request] More customisable MainView layout

### ISSUE THREAD

**Issue by woodwm** [Future-Scholars/paperlib#181]
I would like to request a feature that offers more customisable MainView layout setting.

The List View can be considered as a multiple-line table. Currently, paperlib supports turning features on and off in the third line, but cannot change the position of features. I hope I can reorganise all features (by dragging), for example placing authors behind the title and a whole line for tags.

**Comment by GeoffreyChen777** [comment]
This also requires a lot of work to the UI component. Have you tried the table view? You can switch between list/table views by clicking the buttons on the menu bar.

**Comment by GeoffreyChen777** [comment]
Solved by #352.

In the next 3.0 beta version, the order of each column is changable, and I also added some icons for files and codes etc.

![image](https://github.com/Future-Scholars/paperlib/assets/14183213/2401fe40-5065-4bf6-a071-92e63c4e333b)

**Comment by woodwm** [comment]
Hi,

Thanks for consider this feature request. From your photo, it seems that it allows to change colume order in table view while the list view stays unchanged. This is great.

The intention of this feature request is to allow show the tags in a more confortable way. The table view allows change the column order and column width. Table view is good to present all information in order, but probably not so friendly for small screen users. The list view show more information, and the column width in the third row cannot be changed. 

What about multiline table view? I want to give more space to show the tags. I think many tools underestimate the function of tags. Most information of papers are fixed and tags are user defined to allow the user to organise the papers in their way. I do not need a whole line for authors, as most of the time they are strangers for me and I do not care about each one of them.

There are more configurations can be done in the view customisation.

**Comment by GeoffreyChen777** [comment]
The multiline table view is very similar to the list view.

I think we can make the list view more customisable to implement this multiline table.

First, split the elements in the list view into three groups:
- First line: main group
- Second line: second group
- Third line: additional group

Then add two splitters in this view:

<img width="745" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/aa8e83c1-9c50-4cb0-9132-aa4d284952b7">

By moving these splitters, elements are split into three groups, and we render them into corresponding lines.

**Comment by woodwm** [comment]
More customised list view should work. Could you make the customisation of table view and list view separatly (unconnected)? They can have different activated columes and orders. Probably, users can define and save more views later if they want. 

When talking about the costomising list view, how about show the space of three or more lines and allow users to move certain property to the corresponding line? It is the same as group, but showing different group in seperate lines. That will be clear what the group mean.

**Comment by GeoffreyChen777** [comment]
> More customised list view should work. Could you make the customisation of table view and list view separatly (unconnected)? They can have different activated columes and orders. Probably, users can define and save more views later if they want.
> 
> When talking about the costomising list view, how about show the space of three or more lines and allow users to move certain property to the corresponding line? It is the same as group, but showing different group in seperate lines. That will be clear what the group mean.

Decoupling them is doable.

For more lines, it is related to the styles: bold, colors, font sizes, etc. I think for a normal user, an open-box-to-use setting would be friendly.

For advanced users, I think we can achieve it by using custom CSS. This feature is tracked here #273 

BTW, users probably won't frequently switch views; most people likely have one they prefer the most.

**Comment by woodwm** [comment]
That is true. I do not switch views often. After I finish the customisation, I will use it for long time. 

If the style could be changed, then everything should be good.
