### ISSUE TITLE
[Feature Request] Browser extension supports Elsevier

### ISSUE THREAD

**Issue by greatzh** [Future-Scholars/paperlib#202]
Just started using Paperlib, there is a problem, I do not know if I am not using it correctly or not.

When I downloaded the paper from the university's purchased database and chose the save path to the Paperlib Library Folder, could Paperlib detect and import this paper to my Library automatically with the scraped data? 

Because I found that when I used the extension to import papers on some websites, it just imported the paper's basic info to Library but didn't download the paper pdf file for me. Then I downloaded this paper to the Library Folder, I still need to drag and drop this pdf file to Paperlib main face.

Maybe I should consider that configuring the custom downloader to help the Paperlib locate successfully.

**Comment by GeoffreyChen777** [comment]
Hi, Which database are you using?

**Comment by greatzh** [comment]
https://www.sciencedirect.com/ Elsevier?
eg: https://www.sciencedirect.com/science/article/pii/S0925231222011031
and when I click the "View PDF” to a new website with https://reader.elsevier.com/reader/..., the paperlib extension didn't work for this page.

**Comment by GeoffreyChen777** [comment]
Currently, the browser extension doesn’t support Elsevier.

I would suggest you download PDF and drag it to Paperlib to import.

I will add this feature to todo list.

**Comment by greatzh** [comment]
Okie, thanks for your work REALLY.

**Comment by GeoffreyChen777** [comment]
I tried this, but found that it's hard to programmatically download PDFs on sciencedirect as it has access control.

I tried to copy cookies etc. but no luck.

Now I need to let this issue be pending until I found a solution.

**Comment by GeoffreyChen777** [comment]
Currently, I tried to solve this, but still with no luck. So I close this issue.

The best workaround, for now, is just importing the basic metadata first, and then, click the `locate` btn in the detail panel to download the PDF.

**Comment by greatzh** [comment]
I understand. Thanks for your attention, and have a happy weekend!
