### ISSUE TITLE
Fix Chrome extension to import papers on IEEE Xplore.

### ISSUE THREAD

**Issue by greatzh** [Future-Scholars/paperlib#203]
Hi there, here again, I don't know what went wrong. The Chrome extension can import the paper to my library successfully when accessing the ieeexplore website, but the main pdf files automatically saved in the library folder cannot be opened. And I found that all those main pdf files that failed to open kept the same size at 65.8kB.
Thanks for your help.

**Comment by GeoffreyChen777** [comment]
Seems IEEE updated their webpage and the PDF url.

Thanks for reporting this.

Now please download PDFs manually and drag them to Paperlib to import papers.

**Comment by GeoffreyChen777** [comment]
But recently I've been busy because of my paper submission. I will fix this after March 8.

**Comment by greatzh** [comment]
Thank you. I'd love to, but I am a newbie for the Vue+Electron development. It may take some time for me to understand the whole project.
And good luck.

**Comment by GeoffreyChen777** [comment]
Resolved in the new version.
