### ISSUE TITLE
Some UI details and a typo.

### ISSUE THREAD

**Issue by yuhangch** [Future-Scholars/paperlib#206]
typo:
1. username in `app/renderer/ui/preference-view/cloud-view.vue` line 92 or 198. 

UI details (just suggest):
1. The views of preference with difference width and height, maybe a common size should be set.
2. When the mouse hovers over some buttons, cursor does not switch to `pointer`,this is actually not necessary, it might be better to keep the same behavior for all clickable buttons, such as 1)the right-bottom close button on dialog; 2)the filter/sort button next to preference button.

I originally wanted to submit a PR on these issues, but I didn't run it locally🤦.

Thanks for your awesome work 🐮🍺

**Comment by GeoffreyChen777** [comment]
Thanks for your suggestions!

Will fix them soon.

**Comment by GeoffreyChen777** [comment]
Resolved in the new version.
