### ISSUE TITLE
[Feature Request] Fuzzy search support

### ISSUE THREAD

**Issue by h-jia** [Future-Scholars/paperlib#225]
Thanks for the app! Any plan to support the fuzzy search?

**Comment by GeoffreyChen777** [comment]
You mean the top search bar?

**Comment by h-jia** [comment]
If we have this: 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/29906369/226097536-cd2af8d5-7b49-43db-aec4-65a99022824f.png">

It is great. 

While if we want to do this:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/29906369/226097606-cbd9edf2-3759-4f15-8bd4-d4b7e38b1f37.png">

It disappears.

**Comment by GeoffreyChen777** [comment]
OK, I got you.

For this case, I guess it's doable in the future version by using `LIKE` query: `title LIKE keyword1 * keword2 *`. The backend database does provide an API like that:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/14183213/226097779-5238b39b-0ee5-494e-b4b6-ab0998e61de2.png">


But if you want to search this paper by something like: `teet time`, misspelling words, I guess it's hard to do that.

Anyway, I will try `LIKE` query recently. If it is doable, I will add this feature in the next version.

**Comment by GeoffreyChen777** [comment]
resolved.
