### ISSUE TITLE
Drag and drop on Windows

### ISSUE THREAD

**Issue by MjolnirT** [Future-Scholars/paperlib#229]
Does paperlib for Windows support drag-and-drop functionality? On the official webside, it does have but I am not sure it is supported on Windows.

**Comment by GeoffreyChen777** [comment]
You mean drag a pdf and drop it to the main view to import it?

**Comment by GeoffreyChen777** [comment]
I've tested v2.2.1 on my Windows PC, and everything looks good.

Please provide more info about this issue, thanks.

**Comment by MjolnirT** [comment]
Thanks for testing it. I also use v2.2.1 with Windows 10 (OS build 19045.2788). When I try to drag a pdf file to the main view my cursor becomes a block sign and will not import any pdf files.

**Comment by GeoffreyChen777** [comment]
Hi I record a video of my operation,

https://imgur.com/a/YmcxJ5b

is that look similar to your operation?

**Comment by MjolnirT** [comment]
I record an animation of my case. 
![Animation](https://user-images.githubusercontent.com/19630721/231359353-adebe09d-e034-4e12-881d-a6a8d255d8c0.gif)
As you can see, the cursor becomes a block sign when I drag my pdf file to the main view.

**Comment by GeoffreyChen777** [comment]
Does drag-drop work for other apps such as Chrome etc.?

**Comment by GeoffreyChen777** [comment]
I found this issue:

https://github.com/electron/electron/issues/12460

looks similar to your case.

It suggests that:

> As far as I understand, the problem is when the application runs in Administration mode (windows), in this mode it's impossible to drag and drop files because the OS is avoiding this behavior, if the same application runs with normal user rights, the drag and drop of files works as expected. I don't know if there is some technique to change this, although.

**Comment by MjolnirT** [comment]
Thanks for your suggestion! It works now after I run it as a non-admin user.
