### ISSUE TITLE
[Feature Request] Modification of Font Size

### ISSUE THREAD

**Issue by brant-ruan** [Future-Scholars/paperlib#231]
Hi, thanks for creating this awesome program!

The default appearance font size seems to be small. I want to make it bigger.

Thanks!

**Comment by GeoffreyChen777** [comment]
Hi, if you use macOS, you can press cmd+ -/= to decrease/increase the font size.

on Windows, I guess it’s ctrl+ -/=. Try it.

**Comment by brant-ruan** [comment]
Got it, many thanks!
