### ISSUE TITLE
Restore window size when reopen the App

### ISSUE THREAD

**Issue by h-jia** [Future-Scholars/paperlib#235]
Once I closed the app, I noticed that it restored with a very wide window size when I reopen it. As a result, I had to readjust the window each time to fit my desired layout. 

Is there a setting related to `UIApplicationSupportsMultipleScenes` that could potentially address this issue?

**Comment by GeoffreyChen777** [comment]
The initial size of the window is fixed:

https://github.com/Future-Scholars/paperlib/blob/93a5fc010bacf34a73a6ec7791b0b4ffee93f926/app/main/win_main/index.ts#L21

I guess your monitor/resolution is a small one.

**Comment by h-jia** [comment]
Thanks for the prompt response. Any option to change this in my installed app? Not familiar with electron development my apologizes. I searched within the app folder use 'width' keyword and did not find a clue.

**Comment by GeoffreyChen777** [comment]
Pls wait for the next release. I will make it remember the last window's size.

**Comment by h-jia** [comment]
Got it. Thanks very much for the app and help!

**Comment by GeoffreyChen777** [comment]
resolved #240
