### ISSUE TITLE
[Feature request] Smart Folder

### ISSUE THREAD

**Issue by fkcptlst** [Future-Scholars/paperlib#237]
目前Tag可以实现比较好的细粒度分类，但每次进行Advanced  Mode查询较为麻烦。能否实现一个“智能文件夹”的功能（本质上是一个视图），这样就能搭配自动打标签实现很多丰富功能，比如自动分类、最近阅读、最近添加等。

另外可否让查询支持正则表达式？这样的话 #182 提到的层级化tag也能有一个workaround（通过`/`+正则匹配）

**Comment by GeoffreyChen777** [comment]
智能文件夹 在实现中。

**Comment by GeoffreyChen777** [comment]
Resolved in #243
