### ISSUE TITLE
[Feature Request] 插件系统和插件商店

### ISSUE THREAD

**Issue by fkcptlst** [Future-Scholars/paperlib#238]
## 为什么需要？

- 不同学术领域有很多自己的出版社，小规模开发团队很难实现和持续维护所有出版社的scraper
- 现有的自定义scraper需要手动粘贴代码，这对非计算机出身的用户不是太友好，也不方便分享。如果是插件商店按照则能解决这个问题。
- 学术领域、工作流差异会导致不同人有不同的需求，如果妥协所有人的需求会导致臃肿化，而过度精简会导致一部分人的核心需求无法满足。不如采用软件+内置插件+社区插件的模式
- 插件方便社区贡献，这样可以将不是太紧急的功能需求“外包”出去。

## 一些想法

- scraper和downloader这两个核心功能可以改成插件形式，方便扩展和分享
- 开放文档属性增删改查的api，这样能够实现定时自动添加、修改tag之类的自定义功能，方便开发工作流插件
- 开放数据库相关接口，方便开发数据分析相关插件（类似于obsidian的dataview）
- 前端我不是太懂，但是如果能像vscode和obsidian那样能够让插件修改图形界面布局，那么或许可以支持许多较为小众的插件功能（笔记、脑图等）
- 可以模仿vscode的extension host来懒加载插件，防止插件拖慢主进程速度

**Comment by GeoffreyChen777** [comment]
你说的是想做的，不过插件系统有些复杂，我也不是专业前端…我还在学习如何做…

**Comment by GeoffreyChen777** [comment]
track in #241
