### ISSUE TITLE
[BUG] The detail view (right panel) doesn't appear after one paper is clicked

### ISSUE THREAD

**Issue by brant-ruan** [Future-Scholars/paperlib#253]
**Describe the bug**

When I click & select one paper, there is no detail view (right panel) any more.

**To Reproduce**

Just open Paperlib and click one paper.

**Screenshots or Log**

<img width="1190" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/13882906/9bade4f4-6f35-4d1e-85c0-a1e7076864ad">

**System (please complete the following information):**

OS version: macOS Ventura 13.3.1 (a) (Intel)
Paperlib version: Version 2.2.2 (2.2.2)

**Additional context**

**Comment by GeoffreyChen777** [comment]
I guess you minimized it’s width. #207

**Comment by brant-ruan** [comment]
Oh, you're right. Thanks!
