### ISSUE TITLE
[BUG] Unable to edit smart filters

### ISSUE THREAD

**Issue by aur3l14no** [Future-Scholars/paperlib#258]
**Describe the bug**
Unable to edit smart filters

**To Reproduce**
1. Create a smart filter
2. Edit it
3. Restart the app
4. The smart filter is back to the initial state

**System (please complete the following information):**
 - OS: macOS
 - Paperlib Version 2.2.2

**Additional context**

**Comment by GeoffreyChen777** [comment]
it's not a bug.

The smart filter was just added to Paperlib last version. It is still an in-progress feature.

**Comment by GeoffreyChen777** [comment]
I will make it editable in future. Close for now.
