### ISSUE TITLE
[BUG] Keeps telling me there are background jobs after an error

### ISSUE THREAD

**Issue by aur3l14no** [Future-Scholars/paperlib#260]
**Describe the bug**
Keeps showing ongoing work after an error

**To Reproduce**
1. Update metadata or delete paper and bump into an error
2. Left-bottom corner always displays "updating papers" "deleting papers"

**Screenshots or Log**
<img width="190" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/12196273/acc0cbb5-a62a-462e-84ab-50b12dbef8d5">

**System (please complete the following information):**
 - OS: macSO
 - Paperlib Version 2.2.2

**Additional context**

**Comment by GeoffreyChen777** [comment]
This is a known bug and has been fixed in the next version.

Please reopen Paperlib to solve this for now. 

New version is on its way, please wait.

**Comment by GeoffreyChen777** [comment]
Hi I released a new version to fix some bugs except this one as fixing this bug requires our newly designed notification system which will be released with version3.0.0. Please wait for 3.0.0 thanks!
