### ISSUE TITLE
[BUG] Can not add Tags or Folders on  macOS (Intel) APP

### ISSUE THREAD

**Issue by MEIXuYan** [Future-Scholars/paperlib#261]
**Describe the bug**
Can not add Tags or Folders on  macOS (Intel) APP

**To Reproduce**
no add button '+' besides 'Tags' or 'Folders'.

**Screenshots or Log**
![IMG_6027](https://github.com/Future-Scholars/paperlib/assets/16874175/9f569305-9120-4847-a6f3-82e265d539c7)

**System (please complete the following information):**
 - OS: Ventura 13.4.1 (22F82), Macmini 2018
 - Paperlib Version 2.2.2

**Additional context**

**Comment by GeoffreyChen777** [comment]
https://github.com/Future-Scholars/paperlib/discussions/185

Refer to this if you speak Chinese.
