### ISSUE TITLE
[Feature Request] Add a default folder/tag for those uncategorized papers

### ISSUE THREAD

**Issue by Raibows** [Future-Scholars/paperlib#262]
Hi, thanks for your great work!

It will be convenient to gather all uncategorized papers.
Sometimes, I import many papers at once and it is hard for me to identify which papers lack labels (i.e., they do not belong to any folders or have any tags associated with them).
Therefore, incorporating a default "unclassified" folder/tag would be beneficial.

**Comment by GeoffreyChen777** [comment]
Hi, it can be easily achieved by the smart filter feature like this:

```
tags.@count == 0 && folders.@count == 0
```
<img width="727" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/ec5f2198-c74b-4df8-96ac-62317a897b77">

**Comment by GeoffreyChen777** [comment]
> Cool, that works! Thanks!
> 
> However, I find that the filter expression is not working in the top search (even advanced mode). Is the advanced search different from smart filters?

It should work. Make sure you pressed Enter after you input the expression

**Comment by Raibows** [comment]
Neither `tags.@count == 0` nor `folders.@count == 0` works for me.
However, other expressions, like `rating > 3` works well.

**Comment by GeoffreyChen777** [comment]
Any error message?

**Comment by GeoffreyChen777** [comment]
Thanks! I will make this logic better later.
