### ISSUE TITLE
[BUG] Auto scrolling with the selected item

### ISSUE THREAD

**Issue by Raibows** [Future-Scholars/paperlib#263]
**Describe the bug**
The pageview is not automatically scrolling down or up when you use the arrow keys.

**To Reproduce**
1. select a paper item
2. press up/down keys to switch the selected item until it fades out the page
3. bug here, the pageview is not automatically scrolling up/down

**Screenshots or Log**
Not applicable.

**System (please complete the following information):**
 - OS: Windows 11
 - Paperlib Version 2.2.2

**Additional context**
Not provided.

**Comment by GeoffreyChen777** [comment]
Fixed by #331
