### ISSUE TITLE
[Feature Request] Copy or drag pdf file from main window

### ISSUE THREAD

**Issue by Daryubel** [Future-Scholars/paperlib#266]
PaperLib uses drag-in for file importing, which I think makes it intuitive that user should be able to copy the file from the lib folder by dragging out the selected paper from the main window. 

For now the select and drag operation is only used for tagging as far as I know, and if in case I want to quickly pack or share the raw files of papers I have selected I can only do that by clicking `show in explorer` and manually finding all the intended files (and multiple selection - `show in explorer` does not default select all the pdfs in the explorer, instead it only selects the last one, making identification of files rather difficult).

Again I believe it would be a very useful and consistent feature if you can just drag-and-copy the raw pdfs from the main window. Alternatively maybe adding an option for raw file export in `export` submenu would also solve the problem.

**Comment by GeoffreyChen777** [comment]
Thanks, agree.

**Comment by GeoffreyChen777** [comment]
Implemented in #347.

In the next 3.0.0 beta version, you can drag papers to the file explore with `alt (win) / cmd (mac)` pressed to copy the PDFs.
