### ISSUE TITLE
[Feature Request] Add Hotkey for Search Function

### ISSUE THREAD

**Issue by jianghao-zhang** [Future-Scholars/paperlib#269]
Currently, users need to manually navigate to the search bar every time they want to perform a search. In Paperlib, using "cmd/ctrl + f" will flag the selected paper. However, this hotkey is commonly used to activate the search function in various other applications. Thus I would like to request the addition of a hotkey for the search function in Paperlib. By adding a customizable hotkey, users could effortlessly trigger the search function, saving time and enhancing productivity.

Feature Request Details:
	•	Feature: Add hotkey for search function
	•	Description: Enable users to assign a keyboard shortcut to trigger the search functionality in Paperlib.
	•	Benefits:
	             - Improved user efficiency and productivity.
	             - Quick access to search functionality without manual navigation.
	             - Current Manual Workflow: Users have to manually navigate to the search bar in order to perform a search.
	             - Example Hotkey Implementation: Utilize the “Ctrl + F” combination, commonly used in productivity applications for search functionalities.

I believe this feature would greatly benefit many users of Paperlib. 
Thank you for considering this request.

**Comment by GeoffreyChen777** [comment]
In Paperlib 3.0, the search bar will look like the one in Github. It will be more than a search bar. And also, pressing '/' will focus on it.

**Comment by jianghao-zhang** [comment]
That’s great. Thanks for your efforts!
