### ISSUE TITLE
[BUG] 我在windows上遇到关于 组 标签 和 pdf下载 的问题

### ISSUE THREAD

**Issue by sonwe1e** [Future-Scholars/paperlib#270]
这个软件无论是界面还是功能都几乎满足了我对文献管理软件的所有期待，但我遇到了一些麻烦。在我点击搜寻后并不会自动下载pdf，那么在我双击论文的时候也不会打开该论文，只会跳转到软件安装目录。
另外我尝试了几次，我也找不到如何添加标签和组。

**Comment by GeoffreyChen777** [comment]
首先关于 标签和组，请参考 https://github.com/Future-Scholars/paperlib/discussions/185

另外关于PDF问题，请问，你的右侧详情界面，有显示PDF 预览嘛？

**Comment by sonwe1e** [comment]
如果本地有文件，就有预览；没有文件就没有预览，我之前下载过一部分论文在文件夹里，我不知道因为什么原因这些论文被清空了，如果要一篇篇去找的话会很耗时

**Comment by GeoffreyChen777** [comment]
那对于那些有预览的论文，你能正常通过双击打开PDF嘛？

**Comment by sonwe1e** [comment]
可以，会通过默认的应用打开，空格也可以预览。主要问题还是不能下载的，也就是本地没有pdf文件吧

**Comment by GeoffreyChen777** [comment]
PDF 下载功能，并不能做到所有论文都能搜到下载链接，可用的下载器在设置里，你可以看看你打开了哪些

<img width="649" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/d6497ef6-ccfa-4a4c-a4be-2a99ec31b587">


如果一个论文有 arxiv id，那它大概率能下载到，如果有DOI，并且启用了 x-hub （也就是很知名的那个，因为法律问题，我无法直接提供功能，需要用户自己启用） 的话，也基本是可以的。但是你需要自己启用x-hub，并填入网址进去

<img width="677" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/6b72ea62-c46b-4c14-8c17-879f0c8f154d">

**Comment by GeoffreyChen777** [comment]
你可以先找一个带有 arxiv id 并且没有PDF的测试一下

**Comment by sonwe1e** [comment]
https://arxiv.org/abs/2303.01494
我尝试了这一篇，args我填写了https://xxx-hub.live/
另外我打开了arxiv和semanticschool
![image](https://github.com/Future-Scholars/paperlib/assets/72198365/44ff61de-ecb8-4d57-a025-ea0fe35bd212)
最后还是不能下载

**Comment by GeoffreyChen777** [comment]
对于这个文章，麻烦截图我看一下编辑界面

<img width="550" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/13018071-d586-4a1c-a668-0a7131ca4fed">

**Comment by sonwe1e** [comment]
![image](https://github.com/Future-Scholars/paperlib/assets/72198365/ba46f7bc-7568-43a4-863b-ce90f7001b63)
另外想请问一下，这里说的通过一个论文创建folder的意思是在文件管理器创建一个文件夹还是在论文的设置里创建，如果是设置里我可能不知道如何设置
![image](https://github.com/Future-Scholars/paperlib/assets/72198365/886d2cbf-43dd-4f36-80e3-e06385071794)

**Comment by GeoffreyChen777** [comment]
> ![image](https://user-images.githubusercontent.com/72198365/252906626-ba46f7bc-7568-43a4-863b-ce90f7001b63.png) 另外想请问一下，这里说的通过一个论文创建folder的意思是在文件管理器创建一个文件夹还是在论文的设置里创建，如果是设置里我可能不知道如何设置 ![image](https://user-images.githubusercontent.com/72198365/252907115-886d2cbf-43dd-4f36-80e3-e06385071794.png)

就是在编辑界面，你想创建，直接输入就行了，鼠标点上去，在这里，输入

<img width="543" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/b3081350-0061-4583-a0f6-986f8220aa2f">

**Comment by GeoffreyChen777** [comment]
显然，你这个论文，没有 arxiv ID，所以导致搜不到PDF。解决办法很简单，你直接手动输入 arxiv ID，保存，然后重新搜索PDF就能下载了

**Comment by sonwe1e** [comment]
针对这篇论文我将2303.01494以及arXiv:2303.01494填入arxiv ID中还是不能进行下载，红圈位置不会显示download from arxiv
![image](https://github.com/Future-Scholars/paperlib/assets/72198365/d211d3fc-6bcb-478e-93c1-a06dd08df86f)
![image](https://github.com/Future-Scholars/paperlib/assets/72198365/ab5a8ddf-73ba-4b95-81b8-180763d48ef9)

**Comment by GeoffreyChen777** [comment]
这有些奇怪哎，如果你只启用 arxiv 下载器呢？

**Comment by sonwe1e** [comment]
我也试过了，只选择arxiv，并且我怕因为我设置了什么导致的所以卸载重装了，发现设置还是会保存下来

**Comment by GeoffreyChen777** [comment]
奇怪，不用卸载，不会是设置问题，我找个windows笔记本试试看，我是mac所以也许是系统问题。

**Comment by sonwe1e** [comment]
对，我想过，但我附近没有mac，所以我也没法测试

**Comment by GeoffreyChen777** [comment]
我用我windows 笔记本试了，也没问题。。。。

加我 vx 吧，沟通方便点，我帮你看看 vx: geoffreychen777

**Comment by sonwe1e** [comment]
好的谢谢

**Comment by Aues6uen11Z** [comment]
所以最后问题是怎么解决的？我有时候还是不能下载pdf

**Comment by GeoffreyChen777** [comment]
> 所以最后问题是怎么解决的？我有时候还是不能下载pdf

是arxiv下载不下来？

**Comment by Aues6uen11Z** [comment]
> > 所以最后问题是怎么解决的？我有时候还是不能下载pdf
> 
> 是arxiv下载不下来？

是的 我怀疑是代理的问题，但我试了也能正常访问外网。之前下载的时候左下角会显示，现在直接没有下载pdf这一步
![image](https://github.com/Future-Scholars/paperlib/assets/79563000/e76b02fa-59b5-4fb4-b210-03f40fd843d8)

**Comment by GeoffreyChen777** [comment]
> > > 所以最后问题是怎么解决的？我有时候还是不能下载pdf
> > 
> > 
> > 是arxiv下载不下来？
> 
> 是的 我怀疑是代理的问题，但我试了也能正常访问外网。之前下载的时候左下角会显示，现在直接没有下载pdf这一步 ![image](https://user-images.githubusercontent.com/79563000/268903571-e76b02fa-59b5-4fb4-b210-03f40fd843d8.png)

感觉应该还是网络问题吧，我在墙外试了是没啥问题的。。如果只是偶发不是一直不行，那应该就是网络的事了。

**Comment by Aues6uen11Z** [comment]
行，我先再用一段时间试试，谢谢
