### ISSUE TITLE
[Feature Request] Add papers through DOI, arXiv ID, etc.

### ISSUE THREAD

**Issue by Abrygzy** [Future-Scholars/paperlib#271]
Sometimes my browser extension can not import papers for whatever reason, it would be excellent if I can directly import papers by typing their DOIs, arXiv ID, etc without first downloading the pdf files and then dragging them into the app.

**Comment by GeoffreyChen777** [comment]
Let’s wait for the next major version 3.0.0. It will introduce the extension system and I believe this feature can be implemented as an extension.

**Comment by Abrygzy** [comment]
> Let’s wait for the next major version 3.0.0. It will introduce the extension system and I believe this feature can be implemented as an extension.

Sounds great!

**Comment by GeoffreyChen777** [comment]
Hi, 3.0.0-beta.1 is released now. It introduces an extension system.

Your feature request can be achieved by a `command extension`. For more information, please refer to:

https://paperlib.app/en/extension-doc/ext-types/command-ext.html


**3.0.0-beta.1 Release Note:**

1. The entire code has been refactored to support the extensible architecture. For details on extension development, please refer to our official website. Let's make Paperlib better together!
2. All metadata scrapers and downloaders have been moved into corresponding extensions.
3. A new command panel interface has been introduced to replace the basic search bar.
4. Support for creating new tags and folders in the sidebar.
5. Fixed some bugs.
