### ISSUE TITLE
[Feature Request] Custom CSS style

### ISSUE THREAD

**Issue by xiajunwen1007** [Future-Scholars/paperlib#273]
**Describe your feature request**
现在的调整字体大小的方法会放大整个界面，使得整个界面比较臃肿，特别是放大缩小按钮也会跟着放大。
<img width="1244" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/49160447/643a8d17-5655-41c5-a5c3-5a16a1a4cb8d">
不知道能否像zotero那样提供单独改变字体大小的方式。zotero调整字体大小还支持单独调整信息栏的字体大小以及界面的字体大小。现在信息栏的字体大小对我个人来说有点小如果能单独调节的话就很好了。

**Comment by GeoffreyChen777** [comment]
目前没有这个功能，未来可以加上一个自定义css的功能，就可以改所有样式了

**Comment by GeoffreyChen777** [comment]
你好，3.0.0-beta.1 版本刚刚发布了，暂时支持了字体大小的选择，如果你想要尝试的话，可以试一下。

关于更改所有 UI 的 CSS，因为我需要给每一个组件都写上 id，目前还没完成。

更新日志：

1. 重构了整个底层代码，以支持可扩展的插件架构，插件的开发等详情请参考官网。一起来让 Paperlib 更强大吧！
2. 将所有的搜刮器，下载器移动到了插件中。
3. 引入了新的命令面板界面替换了基础的搜索框。
4. 支持了在侧边栏新建标签和组。
5. 修复了一些 Bug。

**Comment by GeoffreyChen777** [comment]
@ischaojie Hi, 有时间帮忙实现这个功能嘛?

我想应该比较简单，用这个就行：

https://www.electronjs.org/docs/latest/api/web-contents#contentsinsertcsscss-options

组件div ID 可以留着我抽空给加上去。

**Comment by GeoffreyChen777** [comment]
@charlieJ107 

 Hi, 有时间帮忙实现这个功能嘛?

我想应该比较简单，用这个就行：

https://www.electronjs.org/docs/latest/api/web-contents#contentsinsertcsscss-options

组件div ID 可以留着我抽空给加上去。

**Comment by charlieJ107** [comment]
Okay, 这周事情有点多，周末开始弄来得及吧？

> @charlieJ107
> 
> Hi, 有时间帮忙实现这个功能嘛?
> 
> 我想应该比较简单，用这个就行：
> 
> https://www.electronjs.org/docs/latest/api/web-contents#contentsinsertcsscss-options
> 
> 组件div ID 可以留着我抽空给加上去。

**Comment by GeoffreyChen777** [comment]
> Okay, 这周事情有点多，周末开始弄来得及吧？
> 
> > @charlieJ107
> > Hi, 有时间帮忙实现这个功能嘛?
> > 我想应该比较简单，用这个就行：
> > https://www.electronjs.org/docs/latest/api/web-contents#contentsinsertcsscss-options
> > 组件div ID 可以留着我抽空给加上去。

周末搞就好~感谢
