### ISSUE TITLE
更方便的移动窗口位置

### ISSUE THREAD

**Issue by xiajunwen1007** [Future-Scholars/paperlib#274]
**Describe your feature request**
在mac中目前移动窗口只有按住非常小的一块区域才能移动窗口，不知道能否借鉴zotero在搜索栏上面再添加一行使得有更多的地方可以按住移动
<img width="1183" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/49160447/57e2a27e-7f38-49b1-b286-aa3fc5c4e9b9">

**Comment by xiajunwen1007** [comment]
好的 了解了 可能是之前习惯了zotero那样点击上面移动 我适应适应 谢谢

**Comment by xiajunwen1007** [comment]
不知道方不方便实现 在最上面这一行没有按钮和搜索框的地方实现拖动
<img width="1061" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/49160447/7ca44aa2-4417-416c-830f-ab19e6499f7a">

**Comment by GeoffreyChen777** [comment]
现在这一片支持拖动哇，你不行嘛？

<img width="1625" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/80460575-795a-49f3-ad49-f97dd6504bed">

**Comment by xiajunwen1007** [comment]
我想着这一块是不是可以实现拖动 然后再稍微缩小一下搜索框
<img width="1077" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/49160447/7338aed5-2e29-4837-9ec7-01dce5fd3b37">

**Comment by GeoffreyChen777** [comment]
emmm 我想想吧， 在下个版本，这个搜索栏变为了更强大的 command bar，所以我得想想办法怎么安排。

**Comment by xiajunwen1007** [comment]
好的 辛苦啦
