### ISSUE TITLE
利用键盘移动条目到界面以外的条目时时主界面不会跟着移动

### ISSUE THREAD

**Issue by xiajunwen1007** [Future-Scholars/paperlib#275]
**Describe the bug**
点击任意一个条目，利用键盘向下移动，当移动到最后一个条目后，再利用键盘向下移动，此时主界面没有跟着移动以显示下一个条目。

**Comment by GeoffreyChen777** [comment]
https://github.com/Future-Scholars/paperlib/issues/263
