### ISSUE TITLE
编辑元数据后焦点跟随

### ISSUE THREAD

**Issue by xiajunwen1007** [Future-Scholars/paperlib#276]
**Describe your feature request**
当我们以出版处作为排序准则排序主界面的条目时，此时若编辑某一条目的出版处，条目会因为自动排序而去到别的地方此时选中的条目自动变成另一个临近的条目。不知道能否让焦点跟随选中的条目，而不是选择一个临近的条目。

**Comment by GeoffreyChen777** [comment]
你好，我尝试了解决这个问题，很遗憾目前似乎做不到。

为了解决列表的性能问题，目前的列表采用的是 virtual scrolling 的方式，也就是说，即便数据库里有一万篇论文，实际在界面渲染的条目也只是可见的那几个，以及前后的一点点作为缓存。当滑动条开始滚动的时候，会动态加载其他的论文，同时销毁之前论文的渲染。这样可以保证列表的性能。

然而，在你描述的这个场景中，在编辑完 publication 之后，很多时候，因为排序变了，这个条目已经到了渲染区域之外了，在界面里不再存在相对应的条目 UI 元素。因此我们无法定位到他在什么位置。

如果想解决这个问题，需要控制滚动条滚动，前往该条目所在的位置。然而，这会造成很大的性能问题。目前的架构无法做到直接前往目标位置。

所以抱歉这个问题暂时无法解决。如果未来我找到了更好的办法会重新解决它。
