### ISSUE TITLE
[Feature Request] CAYW and JSON-RPC  interface from Better Bibtex

### ISSUE THREAD

**Issue by qcts33** [Future-Scholars/paperlib#277]
**Describe your feature request**
The CAYW (Cite As You Write) and JSON-RPC interfaces provided by Better Bibtex are widely used as a bridge to integrate zotero with other editing software. I think paperlib could implement both and integrate itself into the zotero ecosystem.

https://retorque.re/zotero-better-bibtex/citing/cayw/#diy
https://retorque.re/zotero-better-bibtex/exporting/json-rpc/

**Comment by GeoffreyChen777** [comment]
I don’t know how to use this. Could you please explain more about this? Use case?

**Comment by qcts33** [comment]
Sorry for the late reply. 
The main purpose of this interface is to enable "cite-as-you-write" when writing reading notes or research papers. For example, when I write a LaTeX document in vscode, I can use this interface to get the citekey of a paper, and I wrote a little python code to call Zotero/BetterBiBTeX to generate a bibtex file based on the citekeys in the paper.
In addition to my python code, there are many other programs that interact with zotero through such an interface. The [obsidian plugin](https://github.com/mgmeyers/obsidian-zotero-integration), for example, uses this interface to get information to quickly generate paper notes.

**Comment by GeoffreyChen777** [comment]
Have you tried our quick copy paste plugin?

When you write a paper, if you are using LaTex, you can use the Quick Copy Paste plugin to quickly copy and paste BibTex strings. Just press CMD/CTRL+SHIFT+I, search for a paper and press Enter or SHIFT + Enter to copy the BibTex or BibTex keys to your clipboard. You can link the plugin to a folder that will hold all your copied papers, just click the bottom left of the plugin UI. When you are done writing, you can copy all the BibTex strings in this folder at once.

An ideal writing process would be: 1) link the plugin to a folder first, 2) searching and copying BibTex keys into your LaTex file as you write, 3) when you're done writing, open the plugin and copy all the BibTex into the .bib file.

**Comment by GeoffreyChen777** [comment]
> Have you tried our quick copy paste plugin?
> 
> When you write a paper, if you are using LaTex, you can use the Quick Copy Paste plugin to quickly copy and paste BibTex strings. Just press CMD/CTRL+SHIFT+I, search for a paper and press Enter or SHIFT + Enter to copy the BibTex or BibTex keys to your clipboard. You can link the plugin to a folder that will hold all your copied papers, just click the bottom left of the plugin UI. When you are done writing, you can copy all the BibTex strings in this folder at once.
> 
> An ideal writing process would be: 1) link the plugin to a folder first, 2) searching and copying BibTex keys into your LaTex file as you write, 3) when you're done writing, open the plugin and copy all the BibTex into the .bib file.

@qcts33 @aur3l14no

**Comment by GeoffreyChen777** [comment]
@aur3l14no try CMD/CTRL+SHIFT+I, look through the popes out window. There are some useful button and shortcuts hints.

**Comment by GeoffreyChen777** [comment]
Close as inactive. Fell free to reopen if you have new comments.
