### ISSUE TITLE
[BUG] 特殊 HTML 元素渲染错误

### ISSUE THREAD

**Issue by EstrellaXD** [Future-Scholars/paperlib#279]
**Describe the bug**
在一些化学生物期刊中的特殊符号，在主界面中以 HTML 标签的方式显示而非正确渲染。

**To Reproduce**

Article: Notarangelo, G., Spinelli, J. B., Perez, E. M., Baker, G. J., Kurmi, K., Elia, I., Stopka, S. A., Baquer, G., Lin, J.-R., Golby, A. J., Joshi, S., Baron, H. F., Drijvers, J. M., Georgiev, P., Ringel, A. E., Zaganjor, E., McBrayer, S. K., Sorger, P. K., Sharpe, A. H., … Haigis, M. C. (2022). Oncometabolite            <scp>d</scp>            -2HG alters T cell metabolism to impair CD8                         T cell function. In Science (Vol. 377, Issue 6614, pp. 1519–1529). American Association for the Advancement of Science (AAAS). https://doi.org/10.1126/science.abj5104

**Screenshots or Log**

<img width="854" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/33726646/9713d415-d45d-4fd9-aae0-28dbb85012c7">

正确的 Title 应该是：
<img width="513" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/33726646/02de8ce5-3b8b-4c0a-bbdc-f05320a3040e">

**System (please complete the following information):**
 - OS: macOS
 - Paperlib Version: Latest

**Comment by GeoffreyChen777** [comment]
这个问题是因为，列表内渲染特殊符号会在快速滚动的时候造成一定的性能影响。所以没做渲染。

之后需要研究下优化方案。

谢谢issue

**Comment by GeoffreyChen777** [comment]
Solved by #345 in the next 3.0.0 beta version.
