### ISSUE TITLE
高级搜索支持模糊搜索

### ISSUE THREAD

**Issue by xiajunwen1007** [Future-Scholars/paperlib#280]
**Describe your feature request**
目前高级搜索功能不支持模糊搜索 #226

**Comment by GeoffreyChen777** [comment]
<img width="734" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/f746f160-5bbb-45bf-968a-97a012f7ce29">


我测试支持哇

**Comment by xiajunwen1007** [comment]
我测试是这样唉，普通模式表现是正常的
title contains "composite"
<img width="650" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/49160447/fc8b9b8d-d319-4a59-b6b9-f08fb298ae4f">

title contains "Composite"
<img width="776" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/49160447/a7d28f98-199f-4524-a68f-ca53ee73f5e9">

普通搜索 composite
<img width="727" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/49160447/832d44b4-bc2e-4b2f-9b49-d366c436b8f9">

**Comment by GeoffreyChen777** [comment]
你是想说大小写敏感嘛？

**Comment by xiajunwen1007** [comment]
是的是的

**Comment by GeoffreyChen777** [comment]
<img width="752" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/079ce3bb-1ce5-422e-866b-ceb462f16dbc">


加上这个就可以啦，详细的搜索语言，可以参考 smart filter 的介绍

https://paperlib.app/cn/doc/smart-filter/

**Comment by xiajunwen1007** [comment]
好的好的，感谢作者。顺便不知道为什么不把忽略大小写设置成默认，感觉这样好像更符合大家的使用习惯

**Comment by GeoffreyChen777** [comment]
普通搜索是设置了的。

但是高级搜索是需要开放全部可能性的搜索模式，因此高级搜索直接是送入用户自定义的搜索语句到数据库查询。因此无法指定任何参数。

普通搜索用户输入的其实只是关键词，软件内部把关键词转化为了搜索语句，并加上了大小写不敏感，然后再送给数据库查询。

**Comment by xiajunwen1007** [comment]
好的 感谢
