### ISSUE TITLE
二次搜索

### ISSUE THREAD

**Issue by xiajunwen1007** [Future-Scholars/paperlib#286]
**Describe your feature request**
点击smart过滤器或标签或组，此时无法再次进行搜索。有时候一个标签里论文太多这样不太方便查找，这时往往只能点击所有文献后再进行搜索，有一些不方便。

顺便一提，搜索失败后好像需要删除搜索框中的文字再重新打上才能顺利搜索。复现步骤为
1. 点击任意一个标签
2. 在搜索栏中输入搜索内容
3. 点击所有文献
4. 在搜索栏中回车，正常情况应该会出现搜索内容，但是却没有反应
5. 删除搜索栏中的文字重新回车就正常了

**Comment by GeoffreyChen777** [comment]
已修复，现在可以在标签里搜索了。
