### ISSUE TITLE
[BUG] Setting custom renaming format in preference cause a UI bug

### ISSUE THREAD

**Issue by Rccubc** [Future-Scholars/paperlib#289]
**Screenshots or Log**
Full
![image](https://github.com/Future-Scholars/paperlib/assets/64493219/e4c08e90-cf9e-4434-9a37-f3c24a51e4db)

Custom
![image](https://github.com/Future-Scholars/paperlib/assets/64493219/143d806e-1f94-4016-92c0-4e93048451fe)

**System**
 - OS: Windows 11
 - Paperlib Version: 2.2.5

**Comment by GeoffreyChen777** [comment]
Thanks!
