### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by zzrzzr0123** [Future-Scholars/paperlib#292]
**Describe your feature request**
...
能否把空格的预览设置成为seer这类的预览工具的exe，然后打开pdf的设置又可以是专门看pdf的exe【因为空格的预览只能看到论文的第一页】
能否像notion这种，直接对于空的标签输入信息，因为现在的界面是需要特意的点编辑然后输入标签信息

**Comment by GeoffreyChen777** [comment]
目前预览无法更改，但是pdf打开的软件可以在设置里更改为你喜欢的。我没有用过你说的这个，必须是他支持这种快速预览的功能才能结合。

第二个问题我没看懂，能再描述下吗

**Comment by zzrzzr0123** [comment]
针对第一个问题：应该是mac原生态自带的文件预览，但是window没有的哈，所有像能否使用seer(类似mac里面的一指禅的按下空格就可以预览各种文件的一个应用吧)
针对第二个问题就是在paperlib里面没有办法直接像notion这样直接输入对应的标签内容【虽然Ctrl+E的快捷键也算方便的吧】
![image](https://github.com/Future-Scholars/paperlib/assets/130990085/4bce5fa8-7c62-4113-9d92-ac0bc9911e9f)
notion里面的数据库形式可以直接点击这个空白的地方直接输入对应的标签内容【主要是notion比较不太方便的地方是：整理文献的是否没法直接速览pdf的内容，若是嵌入太多pdf直接卡爆了，所以把文献重新导入到paperlib，真的蛮好用的~~
![image](https://github.com/Future-Scholars/paperlib/assets/130990085/20ef7ed2-84a2-49aa-b7e3-2b5e7f013c03)
![image](https://github.com/Future-Scholars/paperlib/assets/130990085/74fdd8bb-73c5-40c8-8743-6aee2ba83fbc)

**Comment by zzrzzr0123** [comment]
对于这个标记能否过滤出没有标记的文献么？因为这个标记不知道是什么样子的字符欸~
![image](https://github.com/Future-Scholars/paperlib/assets/130990085/1a48beaa-ef56-4ea3-817a-bf102cb390c9)

**Comment by GeoffreyChen777** [comment]
> 对于这个标记能否过滤出没有标记的文献么？因为这个标记不知道是什么样子的字符欸~
> ![image](https://user-images.githubusercontent.com/130990085/257738194-1a48beaa-ef56-4ea3-817a-bf102cb390c9.png)

你是想过滤出没tag的论文？

**Comment by zzrzzr0123** [comment]
> > 对于这个标记能否过滤出没有标记的文献么？因为这个标记不知道是什么样子的字符欸~
> > ![image](https://user-images.githubusercontent.com/130990085/257738194-1a48beaa-ef56-4ea3-817a-bf102cb390c9.png)
> 
> 你是想过滤出没tag的论文？

对对，因为tag掉的是已经精读的论文了，有点小小的😅hh

**Comment by zzrzzr0123** [comment]
> 

原来这样也是可以的哈

**Comment by GeoffreyChen777** [comment]
> > > 对于这个标记能否过滤出没有标记的文献么？因为这个标记不知道是什么样子的字符欸~
> > > ![image](https://user-images.githubusercontent.com/130990085/257738194-1a48beaa-ef56-4ea3-817a-bf102cb390c9.png)
> > 
> > 
> > 你是想过滤出没tag的论文？
> 
> 对对，因为tag掉的是已经精读的论文了，有点小小的😅hh

`tags.@count == 0`

同理，想过滤没有组的论文：

`folders.@count == 0`

两个都没有的：

`tags.@count == 0 AND folders.@count == 0`

**Comment by GeoffreyChen777** [comment]
你可以查看这里，得到所有的语法

https://www.mongodb.com/docs/realm/realm-query-language/#aggregate-operators

**Comment by GeoffreyChen777** [comment]
本地路径的图片应该是不好弄，但是可以用图床，在线图片。
