### ISSUE TITLE
[Feature Request] 希望支持bibtex导入

### ISSUE THREAD

**Issue by davidchern** [Future-Scholars/paperlib#295]
我很早就知道Paperlib，但刚升级了MacOS版本，今天才得以开始使用。

平常我维护了一个Python脚本，支持从arxiv、openreview和biorxiv等网站抓取和解析文献信息为bibtex格式，然后导入到一个文献管理软件（通常是双击即导入，也可使用开始菜单的“导入”功能），使用起来很方便。

目前出于放弃该文献管理软件的考虑，我从该软件导出全部文献列表为bibtex格式，但是始终没法把那些文献的信息（包括注释、星标等）以bibtex格式导入到Paperlib。

请问，有没什么办法可以做到这一点？或许，我需要手工解析bibtex中的文献信息并直接操作Paperlib的数据库？当然，我希望最好是Paperlib加上以上bibtex导入功能。

其次，我希望Paperlib添加一个“添加/Add”或“新建/New”按钮（或/和一个快捷键），允许开启一个信息输入界面，以便手工输入某些信息如arxiv_id或doi号，然后由Paperlib自动获取，这样会更加灵活而方便，而不是目前主要是拖动PDF进Paperlib（某些PDF的元信息并不完整）或靠浏览器扩展的方式。

再者，能否支持设置PDF默认不下载，而是待用户需要时再点击下载（该文献的pdf-url可自动解析，也可由用户手工指定）？

谢谢！

**Comment by GeoffreyChen777** [comment]
直接把 .bib 拖进主界面就可以了。

PDF可选下不载是在计划中的改进了，目前的精力主要还是放在extension架构的实现，等完成了这个重要任务再改进其他的小地方。

**Comment by davidchern** [comment]
> 直接把 .bib 拖进主界面就可以了。
> 
> PDF可选下不载是在计划中的改进了，目前的精力主要还是放在extension架构的实现，等完成了这个重要任务再改进其他的小地方。

感谢你的回复！

我刚尝试了一下，对包含单条文献信息的bib文件，拖进去确实可以导入，但对包含多条文献信息的bib文件，拖进去似乎仍无法导入，换句话说，这块对bibtex的导入功能仍不完整。

至于其他方面的功能，我将继续期待……

**Comment by GeoffreyChen777** [comment]
不会呀，我刚测试了多条的，是可以导入的。是不是你的bib里面有什么特殊的格式，导致解析不了？或者你可以传个网盘啥的链接给我我试试

**Comment by GeoffreyChen777** [comment]
Close as inactive. Please reopen if you want to discuss more.
