### ISSUE TITLE
[Feature Request] Request Support for iOS (especially iPadOS)

### ISSUE THREAD

**Issue by geekifan** [Future-Scholars/paperlib#298]
**Idea About Support for iOS (iPadOS)**

More and more researchers are using their iPads to read papers, so I think it is necessary to develop a simple iOS app for paperlib. I think the app just needs to be able to show managed papers, edit some information (stars/add tags/add folders) and support PDF reading for now.

If the author doesn't have the time, I'd be willing to create a simple app and try to implement the idea. I'm a PhD student and don't know much about iOS development, so maybe it will take me 2-4 months :).

**Comment by GeoffreyChen777** [comment]
I'm really happy that you are willing to contribute to Paperlib!

Now my sparetime only supports me in developing the desktop version. Thus i', very happy and welcome if you can develop the ios version.

To discuss more about this, you can contact me: wechat: https://bitwarden.geoch.top/#/send/j-a7plpVRHauZrMCpJN2Cw/WJh_GUUBNzOAEpWSDV3IBQ
