### ISSUE TITLE
CCF RANK[Feature Request] 

### ISSUE THREAD

**Issue by Hasakii-ghj** [Future-Scholars/paperlib#299]
大佬是否有计划增加会议的CCF RANK？

**Comment by Garibelhj** [comment]
确实，但可能对刚起步的一些科研人员来说可能更多的还是参考CCF，不过问题也不大

**Comment by fkcptlst** [comment]
感觉可以作为插件

**Comment by GeoffreyChen777** [comment]
你好，3.0.0-beta.1 版本刚刚发布了，支持了插件系统，如果你想要尝试的话，可以试一下用插件实现这个功能。非常简单。

参考：

https://paperlib.app/cn/extension-doc/ext-types/ui-ext.html

**Comment by AlphaGogoo** [comment]
> 大佬是否有计划增加会议的CCF RANK？

我写了个插件可以试试，`paperlib-ccf-rank-scrape-extension` ，可以直接在插件市场搜到
