### ISSUE TITLE
[Question] MS adds-in

### ISSUE THREAD

**Issue by xdchen2** [Future-Scholars/paperlib#300]
I installed the MS extension using add-in feature. I managed to make it work but it doesn't seem to connect to my local files. The paper-lib adds-in doesn't allow to search my local files. I was wondering if there's anything wrong with my setting or file?

**Comment by GeoffreyChen777** [comment]
The reason is that the SSL certification is expired. To update it, I need to release a new version. But the new version is not ready for release.

So could you please tell me your OS platform? I can compile a private version with the new SSL certification for you and give you the download link.

**Comment by xdchen2** [comment]
Hi,

I’m using Mac OS M2 chip one. Thanks a lot!

Best,
Xuanda
On Sep 22, 2023 at 12:22 PM -0400, GeoffreyChen777 ***@***.***>, wrote:

The reason is that the SSL certification is expired. To update it, I need to release a new version. But the new version is not ready for release.

So could you please tell me your OS platform? I can compile a private version with the new SSL certification for you and give you the download link.

**Comment by GeoffreyChen777** [comment]
https://we.tl/t-e2RP3ZF45H

Here is the download link, just replace the version on your Mac. You will not lose your data and config.
It should work now.

**Comment by xdchen2** [comment]
Thanks! It works perfectly!
