### ISSUE TITLE
[BUG] Could not download file from webdav: Error: Invalid response: 409

### ISSUE THREAD

**Issue by cntommy** [Future-Scholars/paperlib#301]
**Describe the bug**
用paperlib的浏览器插件添加的论文，无法打开，提示Could not download file from webdav: Error: Invalid response: 409

![image](https://github.com/Future-Scholars/paperlib/assets/26520294/ee352fb5-1f22-43e0-86a2-21e3173e9b7d)

请问怎么解决呢

**Comment by GeoffreyChen777** [comment]
你设置了webdav作为文件存储是么

**Comment by cntommy** [comment]
应该是没用webadv，只用了icloud

具体
通用-paperlib文献库-存储文件夹   选择的是icloud下的文件夹
云同步-文件存储-文件存储方式    选的是本地

**Comment by GeoffreyChen777** [comment]
这里显示你设置了webdav，你可以打开webdav看看清空账号密码然后选择本地存储，然后重启paperlib再试。

**Comment by cntommy** [comment]
清空后 选择本地存储 重启没问题了 感谢！
可能刚开始默认在webadv界面 但是没账号密码 我以为就是没开启

**Comment by GeoffreyChen777** [comment]
好的
