### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xdchen2** [Future-Scholars/paperlib#302]
fail to drag pdf and move pdf to the target directory.

it generates metadata, but the pdf doesn't move.

it gave errors like 'failed to move files'; 'could not remove file on wevdav.'; 'could not upload file to webdav:'

**Comment by xdchen2** [comment]
solved

**Comment by WhaleGe** [comment]
I had the same error, the file could not be moved, but could be copied. Once moved, the error "Failed to move files" was happened

**Comment by GeoffreyChen777** [comment]
@WhaleGe please open a new issue. Describe your bug in detail with screenshots.
