### ISSUE TITLE
[Question] Windows10系统下Word插件无法安装

### ISSUE THREAD

**Issue by museburg** [Future-Scholars/paperlib#304]

**Comment by museburg** [comment]
按照Paperlib文档提供的方案，在导出里选择Word插件后，电脑提示“此应用无法在你的电脑上运行”。
![image](https://github.com/Future-Scholars/paperlib/assets/59810944/1af3fd6b-018b-45ac-9b24-c1b7e0868903)

Windows规格如下：
版本	Windows 10 专业版
版本号	22H2

**Comment by GeoffreyChen777** [comment]
我测试了22H2和最新版word365，无法复现。

不知道是不是你word 版本问题

**Comment by museburg** [comment]
> 我测试了22H2和最新版word365，无法复现。
> 
> 不知道是不是你word 版本问题

谢谢回复！

我的word是microsoft office LTSC 专业增强版 2021，不像是版本的问题。

**Comment by le0n** [comment]
@museburg is your word authenticated using a university license? certain volume licenses block the install of particular add-ons.

**Comment by museburg** [comment]
> @museburg is your word authenticated using a university license? certain volume licenses block the install of particular add-ons.

Yes, I'm using a university license. Probably this is the case. Thank you!

**Comment by Lixiao-bai** [comment]
同样的问题，在win11专业版22H2复现，也是用的校园KMS认证，请问更换系统激活方式可以解决吗

**Comment by museburg** [comment]
> Hi all @le0n @museburg @Lixiao-bai , finally I found that the install helper download link is broken. Now I fixed it.
> 
> Please try to install it again. Everything should be fine.
> 
> Sorry for this!

Problem solved. Thank you very much!
