### ISSUE TITLE
[Question] Word Add-in unable to connect to local library on both Web Office and Mac OS (Intel) platforms

### ISSUE THREAD

**Issue by museburg** [Future-Scholars/paperlib#305]
Although the Word Add-in is successfully installed on both Web Office and Mac OS (Intel) platforms, I found it unable to connect to my local library and cannot insert references. Restarting Paperlib or Microsoft Word did not make any help. It looks like this:
![image](https://github.com/Future-Scholars/paperlib/assets/59810944/4d1bfaee-fdb2-4f23-9fa1-e34f627f29de)

**Comment by GeoffreyChen777** [comment]
The reason is that the SSL certification is expired.

Please update Paperlib to 2.2.6 and retry.

**Comment by museburg** [comment]
> The reason is that the SSL certification is expired.
> 
> Please update Paperlib to 2.2.6 and retry.

It worked. Thank you!
