### ISSUE TITLE
[BUG] Inaccurate publication date

### ISSUE THREAD

**Issue by museburg** [Future-Scholars/paperlib#307]
**Describe the bug**
Some articles' issue dates deviate from their online publish dates. For example, this article (https://link.springer.com/article/10.1007/s00382-017-3830-7) was published online in 2017, but issued in 2018. When I cite this article, I hope the publication date to be 2018, however, all scrapers available would give me the publication date of 2017. Such discrepancies in publication date are quite common in my field (earth sciences). It would be very helpful if you could fix this problem.

**Screenshots or Log**
Publication date
![Snipaste_2023-10-30_09-29-03](https://github.com/Future-Scholars/paperlib/assets/59810944/8e662d27-40da-4a1b-8724-1b83f8b1958c)

Metadata in Paperlib
![Snipaste_2023-10-30_09-20-01](https://github.com/Future-Scholars/paperlib/assets/59810944/62de2bf5-0a02-45f1-8074-113e6747d1a8)

**System (please complete the following information):**
 - Paperlib Version 2.2.6

**Comment by GeoffreyChen777** [comment]
Hi, I checked the response body of this paper from crossref.

I found that the issue date, published data in this database are both 2017:

<img width="255" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/77f965e3-9d7d-4221-8930-906811c9e54a">

The published print date is 2018:

<img width="239" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/94227acd-cbf1-4cd9-a2aa-58d241d4c1f3">

Should we use the published print date here?

**Comment by museburg** [comment]
> Hi, I checked the response body of this paper from crossref.
> 
> I found that the issue date, published date in this database are both 2017:
> 
> <img alt="image" width="255" src="https://user-images.githubusercontent.com/14183213/279026472-77f965e3-9d7d-4221-8930-906811c9e54a.png">
> The published print date is 2018:
> 
> <img alt="image" width="239" src="https://user-images.githubusercontent.com/14183213/279026627-94227acd-cbf1-4cd9-a2aa-58d241d4c1f3.png">
> Should we use the published print date here?

Yes, the published print date is the issue date of this article. Thanks for your reply!

**Comment by GeoffreyChen777** [comment]
Hi, I checked the metadata used by zotero and mendely, seems 2018 is commonly adopted. So I fixed this of our metadata server.

Please try to rescrape this paper. You should get 2018 now!

**Comment by museburg** [comment]
> Hi, I checked the metadata used by zotero and mendely, seems 2018 is commonly adopted. So I fixed this of our metadata server.
> 
> Please try to rescrape this paper. You should get 2018 now!

Yes, solved. Thank you :)
