### ISSUE TITLE
[Feature Request] 您好，能否考虑增加可以自由调整tag顺序的功能

### ISSUE THREAD

**Issue by mijhe** [Future-Scholars/paperlib#308]
**Describe your feature request**
我是最近才发现的这款宝藏软件，感谢大佬的开发。对计算机会议的支持太友好了🙏🙏🙏

在使用中我发现【标签】是按照我创建的时间顺序固定排序的，大佬能否考虑新增一项功能，能够让使用者自由的调整标签的次序。私以为这样更有利于论文的分类与整理。

**Comment by GeoffreyChen777** [comment]
![image](https://github.com/Future-Scholars/paperlib/assets/14183213/98f98ac1-fcf1-41a9-867f-689c6d194b09)


有这个功能哦

**Comment by mijhe** [comment]
感谢！
