### ISSUE TITLE
[Feature Request] Nested directories  for PDF storage and nested groups 

### ISSUE THREAD

**Issue by wangcwangc** [Future-Scholars/paperlib#311]
**Describe your feature request**
开发者您好，最近发现了这个工具，现有的功能已经非常好用了，问一下以后会不会修改或添加以下特性：

1. 嵌套组：现有的组不能嵌套，我通常习惯 **会议/年份** 的方式整理。
2. 独立存储位置：希望以后能把论文的本地存储目录独立出来，这样我即使不同步数据库，也能通过云的方式同步论文（有一种情况就是在ipad移动端阅读论文，可能不需要app去管理，直接在云空间（icloud）中打开并阅读，简单的论文标注修改也能够通过云的方式同步回来，不影响论文文件的链接）。
3. 更多的命名格式：现有的命名，首字母缩写不太实用，经常不能一眼看出是什么论文，而论文全名的话，又因为{id}字段，导致文件名不易于阅读。
4. 嵌套文件夹结构：希望能结合1 2 3的特性，pdf存储在本地时，能够单独放在一个文件夹，然后以组的路径格式存储，例如example.pdf属于a组中的子组b，那么在本地硬盘上存储的就是 **{论文文件夹}/a/b/example.pdf**。

**Comment by GeoffreyChen777** [comment]
感谢建议。

1. 嵌套的标签和组，应该会做吧，不过短期内我要先完成插件系统，工作量有点大。
2. 现在的存储位置不就是可以随意改的嘛。我没太懂你的意思哎，你现在把你的选定文件夹放在icloud 应该没什么问题吧。
3. 现在支持自定义格式。你点那个 custom，就可以了。
<img width="647" alt="Screenshot 2023-11-18 at 14 02 24" src="https://github.com/Future-Scholars/paperlib/assets/14183213/df198e84-666a-4c88-a9d0-bbd2f4d9e705">

4. 这个估计很难做。当初在设计的时候，就是不想让人们手动去文件夹里访问PDF的。一切操作都是从 paperlib 作为入口的。而且最重要的是，对于一个论文来说，组不是唯一的。你的习惯是组当作整理文件夹，每个论文只属于一个组。但是很多人不是这么用组。比如有的人会把一次论文投稿的reference整理成一个组。显然同一个论文可能出现在多个reference组里面。此时如何处理本地文件夹结构似乎很麻烦。

**Comment by wangcwangc** [comment]
明白了，感谢你的回复。
1. 期待3.0
2. 是的，我现在就是用iCloud同步的论文文件夹，但是我看到同级目录下还有一些数据文件，这些也会一直同步，如果影响不大倒也还好。
3. 我现在就是使用的custom 用的 {year}_{author}_{full titile}，但我点击重命名后发现，实际的文件名是，例：2022_A_title_id_main.pdf，不知道是不是有问题。
4. 好的，明白了，或许可以以后以软件插件的形式开发出来，类似于zotero的zfile插件。

**Comment by GeoffreyChen777** [comment]
2. 应该没有什么问题，只要注意，不要在另一台电脑上用 paperlib 读取数据库文件。如需要云同步请按教程设置。
3. 关于是否有 bug 我会查一下。
