### ISSUE TITLE
[BUG] Could not download file from webdav: Error: Invalid response: 404

### ISSUE THREAD

**Issue by fkcptlst** [Future-Scholars/paperlib#315]
**Describe the bug**

An error occurred when attempting to use webdav to sync files.

<img width="246" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/79003314/d2dfc5d8-717c-4097-9b28-56c4f65a779a">

**To Reproduce**

1. Set up webdav with url: `https://dav.jianguoyun.com/dav/paperlib`
2. Enter username and password
3. Press connect. The button turns into `disconnect`, indicating that login is successful.
4. When opening a paper from another computer, the 404 error occurs.

**Screenshots or Log**
If applicable, add screenshots or log to help explain your problem.

**System (please complete the following information):**
 - OS: Computer A: windows 11. Computer B: MacOS
 - Paperlib Version 2.2.7

**Additional context**

When using WinSCP to browse webdav files, the files are in the correct place.

![IMG_7968](https://github.com/Future-Scholars/paperlib/assets/79003314/13a6ab23-cb67-47db-8d55-a5017af77be4)

**Comment by fkcptlst** [comment]
Additionally, removing the `paperlib` suffix in the url is also attempted with no success.

**Comment by GeoffreyChen777** [comment]
Hi, I tried the webdav without any issue, here are my settings:

<img width="647" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/d7b7884b-242f-401a-b65d-87f15c7ccd15">
<img width="803" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/5f64b915-bd28-40d8-acec-d6a99915bad7">
<img width="618" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/73180a81-d5cf-431f-9397-fd062c527854">

**Comment by fkcptlst** [comment]
That's weird.

Anyway, I switch to folder sync instead of webdav as a work around, it seems to work for now. Closing issue as completed.
