### ISSUE TITLE
[BUG] some chinese papers cannot be recognized when imported

### ISSUE THREAD

**Issue by ischaojie** [Future-Scholars/paperlib#317]
Solving this problem may require adding a new `scraper` (e.g. parsing data from pubscholar or cnki), or supported in the form of plugins.

<img width="794" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/12986082/a91039b1-79f3-413d-98a7-3c635c78a273">

**Comment by GeoffreyChen777** [comment]
Do you have wechat?

https://bitwarden.geoch.top/#/send/RITQFwkiRL6NbRhlqJW0PA/1LRcl3lEBsmxmJgISKLwIQ

I guess you are also from China.

**Comment by GeoffreyChen777** [comment]
Close as inactive. Please reopen if you want to discuss more.
