### ISSUE TITLE
Can not close what's new page after updated version 2.2.8

### ISSUE THREAD

**Issue by Tabrisrei** [Future-Scholars/paperlib#321]
![image](https://github.com/Future-Scholars/paperlib/assets/44642774/f8ed6b48-30d5-4e5d-8e4f-44fba3ff81fa)

**Comment by Tabrisrei** [comment]
I have updated version 2.2.8, but nothing happend when I click close, I tried to force close paperlib and restart it, this page is still appears. It might be a bug

**Comment by GeoffreyChen777** [comment]
please scroll down and click
