### ISSUE TITLE
[BUG] 搜寻论文可以下载但是无法移动到`/paperlib`文件夹

### ISSUE THREAD

**Issue by lblbk** [Future-Scholars/paperlib#322]
**Describe the bug**
点击右边搜索下载pdf的时候，左下角log显示

```
10:51 Could not copy file: Error: EINVAL: invalid argument, copyfile '~/Downloads/arxiv:2103.14030v2.pdf' -> '~/paperlib/Swin...
```

下次重新打开发现pdf没有被下载，`~/pathlib`目录下也没有pdf文件

**To Reproduce**
点击这里
![image](https://github.com/Future-Scholars/paperlib/assets/26684296/f7f34ded-6221-4136-94aa-a65b60fb44d8)

**Screenshots or Log**
可以看到缩略图，但是左下角log提示错误
![image](https://github.com/Future-Scholars/paperlib/assets/26684296/eb58f7a3-4ec8-4fe6-b319-34d17f299059)

![image](https://github.com/Future-Scholars/paperlib/assets/26684296/25abbcf0-c447-427d-8737-5c5dd6a6d85e)

![image](https://github.com/Future-Scholars/paperlib/assets/26684296/4d4e814d-74a0-4d2b-bb98-774d28d0ebbf)

**System (please complete the following information):**
 - OS: [win11]
 - Paperlib Version [2.2.8]

**Comment by GeoffreyChen777** [comment]
请问每一篇都这样吗？

**Comment by lblbk** [comment]
> 请问每一篇都这样吗？

嗯，我这边没有pdf的点击基本都是这个情况，我在下载目录下又看到一个`.tmp`文件，猜测可能是paperlib下载的。这样还会导致一个情况这个条目的pdf路径会被更新到上面的下载目录`~/Downloads/paper_name.pdf`，打开paperlib会报错不存在。最后就是程序有运行日志吗，我没找到...

**Comment by GeoffreyChen777** [comment]
谢谢不用日志了，已经够清楚啦

**Comment by lblbk** [comment]
又发现个问题，webdav同步不成功，我这边是群晖自己的服务器地址、账号、密码都没任何问题，但是设置好后一直报错无法上传

![image](https://github.com/Future-Scholars/paperlib/assets/26684296/4a5eeafd-9b23-49b7-9367-f61cef459d75)

![image](https://github.com/Future-Scholars/paperlib/assets/26684296/9f94c5ff-e7c1-499b-93ef-2caca148ff16)

**Comment by GeoffreyChen777** [comment]
webdav 我只测试过坚果云，这是设置对应的样子：

<img width="818" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/647b27a6-9557-4704-a4bb-365d8603060b">


我没有群晖不知它要如何设置连接

**Comment by GeoffreyChen777** [comment]
对了，你可以试试在你的群晖文件夹中建立一个名字叫做 paperlib 的文件夹，也许群晖的webdav 并不会自动创建对应路径的文件夹。

**Comment by lblbk** [comment]
> 对了，你可以试试在你的群晖文件夹中建立一个名字叫做 paperlib 的文件夹，也许群晖的webdav 并不会自动创建对应路径的文件夹。

多谢，路径要设置成和坚果云一致就可以同步了
![image](https://github.com/Future-Scholars/paperlib/assets/26684296/45c7c724-eabd-4191-84b1-cbadf229b2e0)

`https://ip:port/webdav/`

**Comment by GeoffreyChen777** [comment]
你好我这无法复制你这个问题，3.0.0-beta.1 版本刚刚发布了，如果你想要尝试的话，可以试一下。如果还有这个问题，可以告诉我，我再询问详细信息去排查。

**Comment by lblbk** [comment]
感谢，我目前用了下2.2.9还没碰到问题🎉
