### ISSUE TITLE
[BUG] Incorrect Display when Denying "Request to Store in Keychain" [3.0.0-beta.1]

### ISSUE THREAD

**Issue by Adam-lxd** [Future-Scholars/paperlib#330]
**Describe the bug**
As described in the title. It can be solved by reopening preference, seems a minor bug.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on 'Cloud'
2. Click on 'Deny'
3. See error

**Screenshots or Log**
Step 1:
<img width="1064" alt="iShot_2024-01-10_20 03 17" src="https://github.com/Future-Scholars/paperlib/assets/62455172/afeb7f40-ec79-48d9-94bb-34fbc5c6cdec">
Step 2:
<img width="1442" alt="iShot_2024-01-10_20 00 58" src="https://github.com/Future-Scholars/paperlib/assets/62455172/61eb1333-047b-4b78-b33c-03783c849bdf">

**System (please complete the following information):**
 - OS: MacOS 14.0 (23A344)
 - Paperlib Version: 3.0.0-beta.1

**Comment by GeoffreyChen777** [comment]
Thanks for reporting this. Will try to fix in the next beta.

We need to access keychain to store the cloud sync password, and the WebDAV password.

Currently, if you want to modify some settings in this tab, please allow it.

There is no secure issue as we only access the password related to `paperlib` dict as shown in the prompt.

**Comment by GeoffreyChen777** [comment]
Fixed in #332
