### ISSUE TITLE
[Feature Request] Direct search by typing on the main layout and press ESC to cancel the search

### ISSUE THREAD

**Issue by sudrizzz** [Future-Scholars/paperlib#333]
## 1. Direct search by typing in the main layout

When focusing on the main layout, is it possible to start searching by typing in the keywords directly, instead of manually tapping the search box to start searching?

## 2. Press ESC to cancel the search

Once the search is complete, can we use the ESC key to exit the search status directly instead of clicking the ❎ button on the right side of the search box?

**Thank you so much for this wonderful project!**

**Comment by GeoffreyChen777** [comment]
Hi, which version are you using?

If you are using 2.2.9, I'm afraid I will not introduce such a feature into 2.x as version 2.x is frozen unless for some crucial bug fixing.

If you are using 3.0.0-beta1, the search bar has been replaced by a brand-new command panel. You can press `\` to search for commands such as `\search` to achieve your request.

Once you finish searching, just press `esc` to close the command panel.

Here is the gif screenshot:

![Screen Recording 2024-01-12 at 09 43 05 (1)](https://github.com/Future-Scholars/paperlib/assets/14183213/cd5cb381-d07b-483e-ad44-f08631ef7839)

**Comment by sudrizzz** [comment]
Thanks for your reply.

I was indeed using version 2.2.9. I had previously installed 3.0beta, but instead of replacing the old 2.2.9 version, it just recreated an app icon, and I'm wondring if this is normal? 

The other thing is, when will the official 3.0 release version be pushed?

**Comment by GeoffreyChen777** [comment]
It's normal, as 3.0 is still in the beta phase. The name of the beta app should be `Paperlib Beta` to make sure that a user can install both Release and Beta versions. And the auto-upgrading channel of the beta version is different from the release version's, which means that the beta APP can only detect new beta versions in the future.

You can just keep the 2.2.9 on your PC, and use the separated beta-3.0 if you want to try some new features such as this command panel, and extension systems. Once we officially release the 3.0, you will get a notification from your beta APP, and then just open the 2.2.9 to upgrade.

We will release 3.0 ASAP. But now I need some time to use the beta version in my own research workflow to find bugs. Also I need to wait for the extension developers' feedback to polish our extension design.

**Comment by sudrizzz** [comment]
Got it. I'm looking forward to the official 3.0 release. Thanks very much for your and your team's hard work! ❤️
