### ISSUE TITLE
[BUG] 3.0 Beta error occurred when clicking on cloud synchronization in settings.

### ISSUE THREAD

**Issue by ischaojie** [Future-Scholars/paperlib#335]
<img width="1440" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/12986082/bfdc892b-fb6e-407b-a255-be1de7266f05">

I want to try and see if I can fix the problem.

**Comment by GeoffreyChen777** [comment]
Hi, this bug has been fixed by #332 

But the new beta version has not been pushed.

You can git clone this project and run it in development mode to see if it is fixed:

```
pnpm install
pnpm run dev
```

**Comment by ischaojie** [comment]
cool!
