### ISSUE TITLE
[BUG] Exporting error with CSL-China National Standard GB/T 7714-2015

### ISSUE THREAD

**Issue by ForeUP** [Future-Scholars/paperlib#343]
**Describe the bug**
在设置了`China National Standard GB/T 7714-2015`格式的CSL后，导出文献的 `CSL 纯文本` 时报错；

**To Reproduce**
1. 选择文献条目
2. 右键导出为`CSL 纯文本`
3. See error

**Screenshots or Log**
```
TypeError: Cannot read properties of undefined (reading 'strings') at f.NameOutput.getEtAlConfig...
TypeError: Error processing argument at index 0, conversion failure from undefined at Oo.export ...
```
![error-out-20240115120655](https://github.com/Future-Scholars/paperlib/assets/81366928/3181cf5b-5b3c-42b8-8fbe-0fa450827638)

**System (please complete the following information):**
 - OS: Win11
 - Paperlib Version 3.0.0-beta.1

**Additional context**
用其他类型的CSL不会报错，但CSL都是从https://github.com/citation-style-language/styles/tree/master
[这里](https://github.com/citation-style-language/styles/tree/master)下载的，难道时不支持GB格式的导出？

**Comment by GeoffreyChen777** [comment]
这个问题是因为，你使用的 这个 CSL，首先不是英文的，指定了语言，然而却没有定义相关字段的翻译，比如 `et-al`。

因此`citation-js`库不知道该如何翻译英文中的 `et al.`。你可以自己修改一下这个 CSL，添加上相应的字段即可。

```
  <locale xml:lang="zh-CN">
    <date form="text">
      <date-part name="year" suffix="年" range-delimiter="&#8212;"/>
      <date-part name="month" form="numeric" suffix="月" range-delimiter="&#8212;"/>
      <date-part name="day" suffix="日" range-delimiter="&#8212;"/>
    </date>
    <terms>
      <term name="anonymous" form="short">佚名</term>
      <term name="edition" form="short">版</term>
      <term name="open-quote">“</term>
      <term name="close-quote">”</term>
      <term name="open-inner-quote">‘</term>
      <term name="close-inner-quote">’</term>
      <term name="et-al" form="short">等</term>      <-------
      <term name="et-al" form="long">等</term>        <---------
    </terms>
  </locale>
```
