### ISSUE TITLE
[Feature Request] Automatic Update of Paper Status from Conference Acceptances

### ISSUE THREAD

**Issue by SKDDJ** [Future-Scholars/paperlib#357]
Hello @GeoffreyChen777,

I am using your software to manage my collection of academic papers, primarily downloaded as PDFs from arXiv. I appreciate the way the software organizes and categorizes these papers. However, I've encountered an issue with the updating of paper statuses.

Many papers initially appear on arXiv and are later accepted for publication in conferences. The status of these papers in the software remains as 'arXiv', even after their acceptance at conferences. This leads to outdated information in the software's database.

For instance, papers accepted at ICLR 2024 are now listed on Open Review with their updated status, but in the software, they still appear as if they are only on arXiv.

Is there a way for the software to automatically fetch and update the status of these papers, possibly by integrating with sites like Open Review? This feature would significantly enhance the software's accuracy and utility.

Looking forward to your thoughts on this.

Best regards,
Yiming Shi

**Comment by GeoffreyChen777** [comment]
We have this feature. In the preference window-Scraper tab, there is an option called Routine Scrape.

It is what you want.

**Comment by SKDDJ** [comment]
> We have this feature. In the preference window-Scraper tab, there is an option called Routine Scrape.
> 
> It is what you want.


Hello, @GeoffreyChen777 

I noticed your response regarding the Routine Scrape feature in the preference window-Scraper tab. I wanted to let you know that you can find the latest information on ICLR 2024 accepted papers on OpenReview. However, it seems that the scraper is not updating promptly.

Additionally, I have a suggestion for a new feature. It would be great if the scraper could differentiate whether a paper accepted at the conference is categorized as 'Oral,' 'Spotlight,' or 'Poster.' This would provide valuable information for users.

Thank you for your work on this repository!

Best regards

**Comment by GeoffreyChen777** [comment]
We have an OpenReview scraper which scrapes metadata from OpenReview.

Please make sure you have already turned it on.

About oral, poster. It depends on the data source. If the data source contains such information, you can get it. For example some data from OpenReview contains such info. However not for every conference metadata.

We cannot recognize such info for every conference as there are huge numbers of conf.

If you’d like to custom the metadata you get. I’d suggest you to try the 3.0beta version and write your own extension.

https://paperlib.app/en/extension-doc/

**Comment by GeoffreyChen777** [comment]
BTW, we get openreview data from this API:

```
https://api.openreview.net/notes/search?content=all&group=all&limit=20&term=xxx&type=terms
```

However, the response data is different from the results yielded by the searching function of the website.

If you know how to use openreview API better, feel free to tell us and we will enhance our scraper soon.

**Comment by GeoffreyChen777** [comment]
And I checked the API response for ICLR24.

we have the results of papers on ICLRv2 from the v2 api. However, without author's information. On the openreview website you can see, the author is still hidden.

Thus, our metadata server would refuse to return it to the Paperlib APP as it is an incomplete metadata.

Once the openreview releases the author information. I think you can get the metadata of papers on ICLR24.

**Comment by SKDDJ** [comment]
Thank you for the information. I'll definitely try out what you suggested.
