### ISSUE TITLE
[Feature Request] More Granular Date Formatting in File Naming Convention

### ISSUE THREAD

**Issue by SKDDJ** [Future-Scholars/paperlib#358]
Hi @GeoffreyChen777 ,

I am reaching out to suggest an enhancement to the file naming convention used within Paperlib. Currently, the files are named with the year only, such as "[2020]-[publication]-...". 

![image](https://github.com/Future-Scholars/paperlib/assets/64692063/76fb95f2-0b86-4db6-ba00-fbd137b67046)

While this provides a general time frame, it could be greatly beneficial to include the month of publication or acquisition as well.

For instance, a format like "[20-03]-[publication]-..." would offer immediate insight into not only the year but also the month when the paper was published or updated. This level of detail would greatly aid in organizing and referencing papers, especially for those of us dealing with publications that have significant updates or are subject to frequent changes.

![image](https://github.com/Future-Scholars/paperlib/assets/64692063/9a1de44f-6811-46e6-bcfc-0cdef9f82b68)

Adding this feature would enhance the functionality and user experience of your software. Could you consider implementing this additional date formatting option in a future update?

Thank you for considering this request. I look forward to any possibility of this implementation.

Best regards

**Comment by GeoffreyChen777** [comment]
Thanks for your suggestion.
 
 It’s hard to implement such feature as the responses of many metadata APIs don’t have such month field.

And, for Paperlib, we recommend users to ignore the filesystem. Paperlib UI is the only entry to access, organize your paper library.

I don’t understand why this feature is necessary.

I would suggest you propose more use cases.

**Comment by SKDDJ** [comment]
Thank you for elaborating on your suggestion. I''m using a Greasemonkey script for arXiv (link: [arXiv Download PDF Auto Rename Tool](https://greasyfork.org/zh-CN/scripts/475078-arxiv%E8%AE%BA%E6%96%87%E4%B8%8B%E8%BD%BD%E8%87%AA%E5%8A%A8%E9%87%8D%E5%91%BD%E5%90%8D%E4%B8%BA%E8%AE%BA%E6%96%87%E5%90%8D-%E5%8A%9F%E8%83%BD%E5%A2%9E%E5%BC%BA%E7%89%88-arxiv-download-pdf-auto-rename-tool)) which renames files in a "Year-Month - Paper Title" format. This is indeed useful for quick reference and tracking recent research, especially when using macOS's Spotlight.

**Comment by GeoffreyChen777** [comment]
if you still want to keep your original file at somewhere outside paperlib’s folder, I would suggest you choose the ‘link’ option in the preference view to handle source file rather than ‘cut’.

Please see if it can solve your problem.

**Comment by SKDDJ** [comment]
Thank you for the suggestion, I will try the 'link' option as you mentioned.
