### ISSUE TITLE
[Feature Request] Markdown in document title

### ISSUE THREAD

**Issue by fkcptlst** [Future-Scholars/paperlib#359]
Title such as this is correctly rendered at right side, but not in the middle.

<img width="1040" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/79003314/625579f4-46d7-4a9c-841f-0693e70bfaeb">

**Comment by GeoffreyChen777** [comment]
It will cause an performance issue when scrolling.

**Comment by fkcptlst** [comment]
> It will cause an performance issue when scrolling.

I see. I guess rendering latex in title is not a big issue, closing
