### ISSUE TITLE
[BUG] Jump to 'Local' tab after clicking Disconnect in Cloud

### ISSUE THREAD

**Issue by cpfy** [Future-Scholars/paperlib#361]
**To Reproduce**
1. Go to `Preference -> Cloud -> File Storage -> WebDAV` and first login in.
2. Click on `Disconnect`
3. See error

**Screenshots or Log**
Before click
![image](https://github.com/Future-Scholars/paperlib/assets/30110832/141ed381-fc5b-408a-995d-cd41a6f0bb6b)

After click (jump to `Local` tab)
![image](https://github.com/Future-Scholars/paperlib/assets/30110832/8954db75-9ab5-428d-a80b-3b003ed07a71)

**System (please complete the following information):**
 - OS: windows 10
 - Paperlib Version: 3.0.0-beta.3

**Additional Info:**
No error found in Paperlib Version 2.2.9.

**Comment by GeoffreyChen777** [comment]
I think it's expected. Once you click disconnected, it means you don't want to use webdav anymore, i.e., you are using local storage. So we switch to the `local` tab.

**Comment by cpfy** [comment]
@GeoffreyChen777 It is not as excepted, it should be changed to the state like the image below, it's editable now, the user may need to change the webdav settings.

As of Paperlib 2.2.9, this event is handled correctly.

![image](https://github.com/Future-Scholars/paperlib/assets/30110832/11fbde04-d562-43d9-a6c1-29f281502c2a)

**Comment by GeoffreyChen777** [comment]
In fact, the one in 2.2.9 is a bug.

The switcher here binds a preference called `syncFileStorage`.

2.2.9, The preference store will not emit an event when the value changes. So we don't switch to local immediately.

However, in 3.0.0, we reconstruct all codes, and now everything is eventable. Thus the switcher will immediately switch to `local` after you disconnect.

It is expected.

**Comment by cpfy** [comment]
I see, but I'm wondering what if I need to change the webdav configuration information, such as change webdav address in 3.0 version?

**Comment by GeoffreyChen777** [comment]
Emm. I believe that no one changes it frequently. 😂

**Comment by cpfy** [comment]
That's OK😂, I'll close the issue as expected behaviours.
