### ISSUE TITLE
[Feature Request] Automatically import PDFs

### ISSUE THREAD

**Issue by y10ab1** [Future-Scholars/paperlib#372]
Thanks for the great work!

Is it possible to add a feature that automatically imports downloaded PDFs from the folder to the paperlib instead of having to import them manually?

**Comment by GeoffreyChen777** [comment]
Could you please explain more about this? What is reimporting?

**Comment by y10ab1** [comment]
Apologies for any confusion earlier. I'm curious to know if there's a way to set up an automatic import of PDFs from the folders where we store our papers to paperlib, perhaps on a daily basis or at some regular interval.

**Comment by y10ab1** [comment]
Got it, thanks!
