### ISSUE TITLE
[BUG] unable to install extension from maketplace for paperlin 3.0beta.

### ISSUE THREAD

**Issue by yluo-astro** [Future-Scholars/paperlib#374]
Hi,

In the new 3.0 version, when trying to install the extensions, It shows error as:
FetchError: request to https://registry.npmjs.org/@future-scholars/paperlib-entry-scrape-...

maybe a connection problem ?

Thanks,
Yang

**Comment by yluo-astro** [comment]
In the package of 3.0, these extensions are not install default. Could be pre-installed in the new version ?

**Comment by GeoffreyChen777** [comment]
Are you in China mainland? If so you can use a proxy to solve this.

we will add an alternative extension url for mainland user later.

**Comment by yluo-astro** [comment]
even with proxy, it is still not working.

**Comment by GeoffreyChen777** [comment]
Could you make sure that npmjs.org is in your proxy rules and paperlib are using your proxy? There is a proxy setting page in the preference. Please go to there to setup your proxy and restart paperlib to try again.

**Comment by GeoffreyChen777** [comment]
This issue has been fixed by #375.

Just wait for the next beta version.

For China mainland users, we use `https://registry.npmmirror.com/` as an alternative for `npmjs.org`.

Currently, please use a proxy as a workaround.

---

Close for now, feel free to reopen if you want to discuss more.

**Comment by GeoffreyChen777** [comment]
The new beta version has been released.
