### ISSUE TITLE
[Feature Request] files need to be organized 

### ISSUE THREAD

**Issue by yluo-astro** [Future-Scholars/paperlib#377]
Hi,

When one paper is imported, the files are put under the storage folder. But all pdf files are put together under this folder, which make this folder too messy. It would be better to make new folders, to store these pdf files. Also do not make too many pdf files under one folder. 

Terry

**Comment by GeoffreyChen777** [comment]
Hi.

1. The design of Paperlib is that we wish the Paperlib App should be the only entry. It means that users should never use the file explorer to access their papers.
2. Suppose you have 100 papers. Now you have 100 PDFs in the library folder. If we create one folder for each paper, you have 100 folders. I can't feel any big difference with the current file structure.
3. If you have any use case that really requires this feature. Please let me know.

Thanks for your support again.

**Comment by yluo-astro** [comment]
you can create one folder named "storage".  under storage folder, for every 100 pdf files, create one folder.

**Comment by GeoffreyChen777** [comment]
You can achieve this now.

- Create a folder structure as you wish. (can be outside the library folder.)
- Choose `Symlink` in the preference
- Put PDFs at your desired location in that folder first.
- Then drag PDFs in that folder to the UI to import them.
- Ignore the default library folder.

<img width="806" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/911e8309-6425-46a1-b354-41a9dbd65520">

**Comment by GeoffreyChen777** [comment]
Please wait for this #448

It allows us to organise papers in the library folders via the custom renaming format.

<img width="721" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/354b95dc-f046-4e9d-895f-7d9d6537b6c2">


For example, we have a renaming format: `{year}/{publication}/{title}`, we will have:

```
| -- 2022
    | -- CVPR
        | -- Paper A_id.pdf
        | -- ...
    | -- ICCV
| -- 2024
...
```
