### ISSUE TITLE
[BUG] Rename and deleting bug

### ISSUE THREAD

**Issue by Kevate** [Future-Scholars/paperlib#381]
**Describe the bug**
Hi, thanks for this great work. I found when I renaming new Tag names, typing blank will corrupt the typing and remain unsaved. This bug is also seen when renaming Folders.

**To Reproduce**
1. Go to Sidebar
2. Click on '+' in Tag or Folders
3. Edit and rename, type a blank character.

**Screenshots or Log**
Before typing blank
<img width="1392" alt="截屏2024-02-26 21 10 08" src="https://github.com/Future-Scholars/paperlib/assets/26180320/75531c35-8fdd-40cb-82b5-b97f218216a4">
After typing blank
<img width="1331" alt="截屏2024-02-26 21 10 18" src="https://github.com/Future-Scholars/paperlib/assets/26180320/7d770ef7-b471-47bf-9c78-8caa1fc8f6a4">

**System (please complete the following information):**
 - OS: macOS M1
 - Paperlib Version 3.0.0

**Additional context**
This didn't happened all the time. Restart may solve, but after I check, it will happen when paperlib starts to ask for access of other App.
<img width="328" alt="截屏2024-02-26 21 16 17" src="https://github.com/Future-Scholars/paperlib/assets/26180320/88537f6a-d6f5-4980-afbd-f2a8aed08c82">
So it seems like blank will wrongly activate mac's QuickLook function as the error seems like QuickLook interface.

**Comment by Kevate** [comment]
And Sometimes we cannot delete the tag or folder we created, restart will be fine, but I haven't figured out the pattern of this bug yet.

**Comment by GeoffreyChen777** [comment]
Hi, reproduced. I will fix this soon.

About 'ask for access of other App'

Could you please help me to solve this as it should not happen?

Please add my wechat if you are happy with it:
geoffreychen777

**Comment by GeoffreyChen777** [comment]
> And Sometimes we cannot delete the tag or folder we created, restart will be fine, but I haven't figured out the pattern of this bug yet.

Next time you have this bug, please open the console and attach the log here:
<img width="532" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/551e8f52-cc3c-451e-9887-51895b703773">
<img width="807" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/0a0354b8-ee7d-4afb-94b5-d60a950befef">

**Comment by GeoffreyChen777** [comment]
Close for now. If you meet this bug again, feel free to reopen.
