### ISSUE TITLE
[BUG] Word Add-in cannot search

### ISSUE THREAD

**Issue by IZER0I** [Future-Scholars/paperlib#384]
**Describe the bug**

It was my first time to use the word add-in. After successfully citing several papers, I found that the target document could not be searched.

Even if I create a new word file, I still can't find a specific document in the library, and I'm sure it exists in the PaperLib.

Now no matter what I type into the search box, it shows the same items.

I've tried restarting the PaperLib, reinstalling the add-in, restarting the computer, but the problem persists.

**Screenshots or Log**
<img width="350" alt="iShot_2024-02-28_12 33 25" src="https://github.com/Future-Scholars/paperlib/assets/56252281/446c5fd7-58c5-42bc-b295-64702068b778">

**System (please complete the following information):**
 - macOS 14.3.1
 - Paperlib Version 2.2.9

**Additional context**

Please guide me on how to proceed next, including providing more information or any action to help me solve this problem. Thank you very much.

**Comment by IZER0I** [comment]
https://github.com/Future-Scholars/paperlib/assets/56252281/5793f972-ba65-4b52-b3e0-11a3e4024d3d

As shown in the video, no matter what I type in the search box, it always shows these items.

**Comment by GeoffreyChen777** [comment]
It's weird.

Please click this to open the console to see the log.

<img width="388" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/a707d3ca-43d9-41f1-8a23-0461023c9800">
<img width="1016" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/06b396df-f98b-4629-b618-2444e6621fe4">

**Comment by IZER0I** [comment]
<img width="352" alt="iShot_2024-02-28_19 54 14" src="https://github.com/Future-Scholars/paperlib/assets/56252281/02e4d9f1-4b07-4d89-81d5-15aeadd3ed89">

no inspect element？

So I open the Developer Tools of PaperLib

<img width="1023" alt="iShot_2024-02-28_19 55 39" src="https://github.com/Future-Scholars/paperlib/assets/56252281/10fcca23-2f95-40f5-92c3-64d79b34528c">

**Comment by GeoffreyChen777** [comment]
Please check the search mode of paperlib. I think it is not in the general mode.

**Comment by IZER0I** [comment]
yes, it works!

I usually stay in advanced search mode, and once I change it back to normal mode (which may require restarting PaperLib), everything returns to normal.

Thank you!

Is this a software bug? Is it possible to optimize it in the future so that the Add-in can work normally in other search modes (I usually need to search to help me locate documents)

**Comment by GeoffreyChen777** [comment]
The 2.x version has been frozen except for urgent bug fixing.

You can try the 3.0 beta if you want. In 3.0, there is everything you want.

If you don't want to take a risk of beta (although it's very stale, I've been using it for a while), please wait for the official release. I will release it ASAP.

**Comment by IZER0I** [comment]
Thanks again.

Wish you all the best.
