### ISSUE TITLE
[Feature Request] Support importing bibtex to revise the wrong scraped information for a existed paper

### ISSUE THREAD

**Issue by Raibows** [Future-Scholars/paperlib#388]
I'm using paperlib 2.2.9. 

Currently for most cases, it can automatically scrape the right information for a paper (pdf file) I added to it. However, for some special cases, I need to revise it for correction but have to manually edit the required fields like `Publication`, `Volume`, `Pages` and etc, which is a little bit inefficient if I already have the bibtex information. 

Thus, I hope to add an option to directly revise the paper information by:

- pasting the bibtex plaintext
- importing from a bib file (only containing 1 entry )

Thanks for consistently maintaining this useful academic software!

**Comment by GeoffreyChen777** [comment]
Hi, currently we support importing a paper by dropping a bib to the app. If you wish to revise a paper in your library by a bib string, I believe it would be easy to implement by a command extension in 3.0 version.

You can try the beta now or wait for the official release.

Extension Development Doc
https://paperlib.app/en/extension-doc/

**Comment by Raibows** [comment]
Thanks for your prompt reply.

In this issue, I mean revising a paper already existed in the library via a bib string. 

The 3.0 extension system is really exciting and I'm looking forward to its official release. 

Btw, just for discussion, from my quick look at the extension development docs, it's in node.js lang. Is it possible to support Python in the future? That may be more widely used.

**Comment by GeoffreyChen777** [comment]
Paperlib is developed in Electron which is a Chrome viewer with a nodejs environment. It’s the best cross-platform development solution which has been used by many softwares such as VSCode.

Similar to VSCode, node.js is the most straightforward language for an extension.

To support python, I think there should be a translation layer. I’m open to it, but I think I will not implement it anytime soon as it is a complicated stuff.

You don’t need to be a node.js expert to develop an extension. node.js is very easy to learn. For pythoners, I believe they can learn and start developing an extension in 1 hours.

**Comment by Raibows** [comment]
Great! I'm willing to learn it some time after the official release. Thank you!
