### ISSUE TITLE
[BUG] The "In" smart filter built by GUI will cause Error

### ISSUE THREAD

**Issue by Rccubc** [Future-Scholars/paperlib#389]
**Describe the bug**
When building a smart filter containing `In` condition by GUI, the generated filter string causes an invalid filter error.

**To Reproduce**
1. drag a pdf paper in paperlib
2. add two tags 'A' and 'B' to this paper
3. create a smart filter using the GUI way:
![image](https://github.com/Future-Scholars/paperlib/assets/64493219/052cef05-31e6-47a2-951f-1d3c3564920d)

![image](https://github.com/Future-Scholars/paperlib/assets/64493219/43f9ab00-5bb1-481f-a168-fc4959de2643)

**System (please complete the following information):**
 - OS: Windows 11
 - Paperlib Version: 3.0.0-dev.11

**Additional context**

I don't find an "In" filter example in paperlib's [usage document](https://paperlib.app/cn/doc/smart-filter/), so I jump to the [Realm Query Language](https://www.mongodb.com/docs/realm-sdks/js/latest/tutorial-query-language.html) in usage document. The query document has an "IN" filter example: `let favoriteNames = realm.objects('Contact').filtered("name IN {'John', 'Mary'}"); `.

I explore Paperlib's code at `app/repositories/db-repository/paper-entity-repository.ts`, functions `createFilterPattern()` and `load()`, and find that the way Paperlib filtering `paperEntitys` is similar to the upper example, but the `searchText`(filter pattern) generated by GUI maybe this one:  `"(name IN "{'John', 'Mary'}")" `, I think the error may be caused by the `"` wrapping the `{}`.

I change the `searchText` to `(ANY tags.name in {'A', 'B'})` by hand, and then the filter work well. Maybe adding some code in the function `createFilterPattern()` to change the `"{}"` to `{}` is a solving way. Or change the GUI component code.

**Comment by GeoffreyChen777** [comment]
Thanks for reporting this!

I think currently, for a workaround, you can create two conditions combined by "OR" to achieve this.

Will fix it in the next beta.

**Comment by GeoffreyChen777** [comment]
Fixed.
