### ISSUE TITLE
[BUG] Bibliography doesn't change line when using web word add-in

### ISSUE THREAD

**Issue by fkcptlst** [Future-Scholars/paperlib#390]
**Describe the bug**

使用Web word add-in时，导入参考文献不会自动换行。

**Screenshots or Log**

<img width="1412" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/79003314/a81addd0-23fd-46b6-92dc-0131bc96ffe6">

**System (please complete the following information):**
 - OS: macOS
 - Paperlib Version 2.2.9

**Comment by GeoffreyChen777** [comment]
Thanks.

**Comment by GeoffreyChen777** [comment]
Sorry I cannot reproduce this bug:
<img width="1501" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/dd3b09c8-e5d1-4465-9e63-aa70564aa06e">

I guess this is related to your CSL style.

**Comment by fkcptlst** [comment]
Yes, I think you're right. I'm using GB/T-7714-2015-numeric. Do you have any ideas of what might be causing this issue?

**Comment by GeoffreyChen777** [comment]
I have no idea now.

But you can share this CSL with me. I will try to figure it out.

**Comment by fkcptlst** [comment]
Here is the CSL:

[csl.zip](https://github.com/Future-Scholars/paperlib/files/14572357/csl.zip)

**Comment by GeoffreyChen777** [comment]
<img width="1469" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/0b193ce4-1ea9-4307-916d-64aa51ac79c2">

Still cannot reproduce this issue.

I guess there is something wrong with your document.

Could you please try to create a new document for testing?

**Comment by GeoffreyChen777** [comment]
因无法复现，暂时关闭，如还有此问题，欢迎 reopen。
