### ISSUE TITLE
[Enhance] Register contextmenu from extensions.

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib#401]

**Comment by GeoffreyChen777** [comment]
Hi, @igoogolx

I would suggest you to implement this feature to get familiar with the extension system. 

As a former Electron developer, I believe you should know there are two basic processes: `main` and `renderer`. In Paperlib, in addition to these two processes, we have an additional one `extension`.

Here we fork an extension process:

https://github.com/Future-Scholars/paperlib/blob/358bf8e42cf1489b7b2dd9b5a895ae4393fb720b/app/main/services/extension-process-management-service.ts#L40-L42


In each process, we have many services, the `RPCService` enables us to call a method of any service across processes. For example, you can call the `logService` in the `renderer` process in the `main` process by `PLAPI.logService.info(...)`.

About the RPC, please refer to https://github.com/Future-Scholars/paperlib/tree/main/app/base/rpc

- `main` - `PLMainAPI`
- `renderer` - `PLAPI`
- `extension` - `PLExtAPI`


---


For this issue, the basic design is adding two methods to the `contextMenuService` in the `main` process:

https://github.com/Future-Scholars/paperlib/blob/358bf8e42cf1489b7b2dd9b5a895ae4393fb720b/app/main/services/contextmenu-service.ts#L83


These two methods help extensions register and unregister context menu items.
- `registerContext`
-  `unregisterContext`

We should have a private property called `_extensionContextMenuItems` to store the required information such as:
```
{
    id: string       // the id of the contextmenu item
    label: string  // the label shown in the UI.
}
```
When users right-click the UI, we construct the template. So we need to append the `template` with the `_extensionContextMenuItems` before this line:
https://github.com/Future-Scholars/paperlib/blob/358bf8e42cf1489b7b2dd9b5a895ae4393fb720b/app/main/services/contextmenu-service.ts#L258

The callback of each item can be just an event dispatching like:
```
{
    label: "...",
    click: () => {
        this.fire(`${id}Clicked`);
    }
}
```

As a result, extensions are able to listen to this event.

---

Feel free to contact me if you need any help.

**Comment by igoogolx** [comment]
I noticed that type checking is being ignored when calling buildFromTemplate. In fact, MenuItemConstructorOptions satisfies the type requirements here so that those comments can be removed. https://github.com/igoogolx/paperlib/commit/99abe94bc62e43b561e3655ea573a5cbc8b54a12

**Comment by igoogolx** [comment]
Regarding eventName, it seems that "${id}Clicked" can't be used directly. It must be defined first in IContextMenuServiceState or there is a type error from TS.
Here I add "dataContextMenuFromExtensionsClicked" as the key. Fire the event in the callback like this:

`
this.fire({ dataContextMenuFromExtensionsClicked: id });
`

**Comment by GeoffreyChen777** [comment]
> Regarding eventName, it seems that "${id}Clicked" can't be used directly. It must be defined first in IContextMenuServiceState or there is a type error from TS. Here I add "dataContextMenuFromExtensionsClicked" as the key. Fire the event in the callback like this:
> 
> `this.fire({ dataContextMenuFromExtensionsClicked: id });`

Agree, that would be better.

the `id` should consist of two parts: `extID.itemID`. Please emphasize it in the doc of the `register` method.

**Comment by igoogolx** [comment]
Should we allow an extension to register multiple menu items here? Since we need both extID and itemID, here is the data structure and function signature I designed.

```
private readonly _extensionContextMenuItems: {
    [extID: string]: { id: string; label: string }[];
  };

registerContext(extID: string, items: { id: string; label: string }[])


//will remove all items of extID
unregisterContext(extID: string)
```

**Comment by GeoffreyChen777** [comment]
Yes.

`registerContext` -> `registerContextMenu`
`unregisterContext` -> `unregisterContextMenu`

Others look good.
