### ISSUE TITLE
Mac 空格键预览会将条目下滑

### ISSUE THREAD

**Issue by IZER0I** [Future-Scholars/paperlib#403]
**Describe the bug**

你好，

当我打开 PaperLib 主界面，选择一个条目，按下空格键进行预览，此时条目窗口会往下下滑

我是更新最新版（3.0.0）才出现这个问题

**Screenshots or Log**

https://github.com/Future-Scholars/paperlib/assets/56252281/a68f777f-72bf-4e0d-9745-a20d23be6632

**System (please complete the following information):**
 - OS: macOS 14.4
 - Paperlib Version 3.0.0

**Comment by GeoffreyChen777** [comment]
谢谢，已复现。会在下个版本修复。

**Comment by GeoffreyChen777** [comment]
Fixed in #408
