### ISSUE TITLE
如何管理 CSL 文件

### ISSUE THREAD

**Issue by IZER0I** [Future-Scholars/paperlib#404]
你好，

我想试图管理软件内 CSL 文件，但我只找到了导入按钮，并没有出现删除按钮。

<img width="384" alt="iShot_2024-03-15_13 12 33" src="https://github.com/Future-Scholars/paperlib/assets/56252281/d225a704-e8c2-417c-9ad7-281194193332">

如图，我想删除一个我已经导入的 CSL 文件（例如 China National Standard GB/T 7714-2015 （author-date， 中文）），但不知如何操作，请帮帮我。

同时，我发现，我导入 CSL 文件后每次打开 PaperLib 系统都会提示我访问权限

<img width="260" alt="iShot_2024-03-15_13 11 53" src="https://github.com/Future-Scholars/paperlib/assets/56252281/019d7e5d-57a4-492d-beba-05ece12d15d4">

我想是不是就是外来 CSL 导致的，除了完全赋予 PaperLib 磁盘权限，有无其他方法让软件每次毋需出现这个提示？

**Comment by GeoffreyChen777** [comment]
这个提示是word插件导致的，我猜你安装了。

因为word插件实际上是向word软件注入程序。我会想办法看看能不能避免。

**Comment by GeoffreyChen777** [comment]
你这个csl是软件本体的还是word插件的

**Comment by IZER0I** [comment]
> 你这个csl是软件本体的还是word插件的

是软件本体的

**Comment by GeoffreyChen777** [comment]
如果我没记错你把文件夹里的csl删了再重启paperlib就好了
