### ISSUE TITLE
PDF 附件无法打开

### ISSUE THREAD

**Issue by IZER0I** [Future-Scholars/paperlib#405]
**Describe the bug**

打开附件时提示 "URL should have a protocol"

删除附件，重新导入，还是同样的提示。

**Screenshots or Log**
<img width="285" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/56252281/b2155762-aa54-4ff6-bfd3-b595d3f9392d">

**System (please complete the following information):**
 - OS: macOS 14.4
 - Paperlib Version 3.0.0

**Additional context**

**Comment by GeoffreyChen777** [comment]
谢谢，可复现。

会尽快修复。

**Comment by GeoffreyChen777** [comment]
Fixed.
