### ISSUE TITLE
Can Paperlib have hierachical folders?

### ISSUE THREAD

**Issue by David-zju** [Future-Scholars/paperlib#406]
It seems that paperlib only supports a single layer of folders, which limits its effectiveness for paper management. Maybe it's possible to add hierarchical folders like Zotereo?

**Comment by GeoffreyChen777** [comment]
Paperlib supports that.

A ‘+’ appears when the mouse is placed over a folder.

**Comment by GeoffreyChen777** [comment]
<img width="268" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/f99ff46f-40e7-4be0-923a-e8e65c78b868">
