### ISSUE TITLE
“组”标签消失

### ISSUE THREAD

**Issue by IZER0I** [Future-Scholars/paperlib#407]
**Describe the bug**

新的版本里“组”标签不见了？原本编辑文件时能够同时编辑“Tags“和”Folder“标签，现在只显示前者，无法编辑”组“标签了

**Screenshots or Log**
<img width="599" alt="iShot_2024-03-15_17 10 27" src="https://github.com/Future-Scholars/paperlib/assets/56252281/fe16f5fd-945f-4379-a248-1047e87e43ee">

**System (please complete the following information):**
 - OS: macOS 14.4
 - Paperlib Version: 3.0.0

**Additional context**

**Comment by GeoffreyChen777** [comment]
https://github.com/Future-Scholars/paperlib/issues/402

如这里讨论的。

> 我们删除了编辑视图中的组选项。 原因是，在3.0中，我们引入了分层的组。 所以像标签一样对组进行分配是不合理的。

> 以前，我们有两个分类器——标签和文件夹。 但说实话，他们还是挺相似的。

> 但现在，他们不同了。

> 标签是原子的。 所以不能有等级之分。 标签通常表示论文的属性，例如论文的主题。

> 组使用起来更加自由。 您可以将其用作标签。 或者您可以创建许多分层组来组织论文，就像文件系统中的文件夹一样。
