### ISSUE TITLE
Cool idea: Paper Notes Comments/Post！

### ISSUE THREAD

**Issue by huskydoge** [Future-Scholars/paperlib#410]
**Describe your feature request**
...

Hi, guys @paperlib! Thanks for your meaningful efforts! As a CSer, Paperlib is the most convenient paper management tool I have ever used! Here I have some thoughts and ideas to share you with:

As we all know, reading and completely understanding a paper is quite difficult without several reading-throughs. In this procedure, an experienced researcher will write down some very insightful notes, like how is this paper relevant to another paper, and how to understand an equation from other perspectives; while a green hand like me will struggle reading papers. 

Every time I encounter an unknown concept or fail to understand an equation, I need to look elsewhere for information. Nevertheless, those information are not grouped into one platform. I'm always thinking about how wonderful it would be if there could be a bubble above the point which I'm struggling, which can be clicked to see the notations from other people, with ordered qualities. 

This will make reading a paper more interesting and easy, as if I'm reading a book on Weread or reading comic books. I think this could be an amazing reading experience, though it will be difficult, with abundant data and numerous papers......

**Comment by GeoffreyChen777** [comment]
Hi, what you are looking for is a forum.

However it's far beyond my personal ability：

1. It requires a good cloud server. I don't have funding for that.
2. It requires a good user system to prevent the forum from junk content, scamming.
3. In China, it is illegal to create a forum without registration to gov. If I create a registered forum, I have the responsibility for the content in this forum. If there is any inappropriate content, say, terrorist, politics. I'm afraid I have no more chance to maintain Paperlib.

I know a platform that provides such features:

https://readpaper.com/

you can try that.

**Comment by huskydoge** [comment]
Thanks for your reply and tool recommendation! Also, thanks for telling me what's the potential difficulty of implementing this idea~ 

readpaper is sooooo powerful!

**Comment by GeoffreyChen777** [comment]
You can use Paperlib to organise papers, and use readpaper to read papers.

I would suggest you implement a small extension to connect them.

**Comment by GeoffreyChen777** [comment]
I think Stanford University implemented your idea. alphaxiv.org.

Paperlib now has an extension to show comments from alphaxiv.org: `paperlib-community-comments-extension`. Try it.

**Comment by huskydoge** [comment]
Yes! This is great! Thanks for telling me~ I will have a try.

Best Regards,
husky
在 2024年8月1日 -0700 02:57，GeoffreyChen777 ***@***.***>，写道：
