### ISSUE TITLE
Missing PDF file

### ISSUE THREAD

**Issue by IZER0I** [Future-Scholars/paperlib#411]
**Describe the bug**

when I use “Table Reader View”, some papers are missing, but as you can see in the figure below, the pdf does exist in the right location.

**Screenshots or Log**

<img width="1081" alt="iShot_2024-03-15_22 35 44" src="https://github.com/Future-Scholars/paperlib/assets/56252281/49cc3468-58ab-4c2a-a940-61ccd46ff1de">

**System (please complete the following information):**
 - OS: macOS 14.4
 - Paperlib Version 3.0.0

**Additional context**

**Comment by GeoffreyChen777** [comment]
Cannot reproduce.

Could you please try to click other papers and the click back to this one to see what happened?

**Comment by IZER0I** [comment]
Most document preview interfaces display normally, and only a few display missing files. After repeated attempts to restart, there is always a problem with those specific files.(Only one case of missing files occurs in dozens of documents.）

I discovered a new situation. (still in Table Reader view mode)
Only by clicking on different documents with the mouse can the preview be displayed correctly. If you just use the up and down keys on the keyboard to move the focus, the preview interface will not change.

**Comment by GeoffreyChen777** [comment]
Could you please try to double click this paper to see if you can open it.

**Comment by IZER0I** [comment]
> Could you please try to double click this paper to see if you can open it.

yes, I can open this paper normally.

**Comment by GeoffreyChen777** [comment]
Could you please share the file name? I guess there are some special chars in the filename.

**Comment by GeoffreyChen777** [comment]
Let's first remove all special chars in the title.

Then you will find the filename should be changed.

Finally, try in the Table Reader View again.

If everything is normal. I would say this is a bug.

**Comment by IZER0I** [comment]
Could you consider finding a solution for these documents?



> Most document preview interfaces display normally, and only a few display missing files. After repeated attempts to restart, there is always a problem with those specific files.(Only one case of missing files occurs in dozens of documents.）
> 
> I discovered a new situation. (still in Table Reader view mode) Only by clicking on different documents with the mouse can the preview be displayed correctly. If you just use the up and down keys on the keyboard to move the focus, the preview interface will not change.

Is the new situation mentioned here a bug?

**Comment by GeoffreyChen777** [comment]
> I discovered a new situation. (still in Table Reader view mode) Only by clicking on different documents with the mouse can the preview be displayed correctly. If you just use the up and down keys on the keyboard to move the focus, the preview interface will not change.

Yes this is a bug.

> Could you consider finding a solution for these documents?

Because I cannot reproduce this bug, and I don't have your paper files. So I cannot debug by myself.

You can do what I said before to see if everything is ok. That would help me make sure the special chars caused this bug.

Or, please share this paper here.

**Comment by IZER0I** [comment]
> Let's first remove all special chars in the title.
> 
> Then you will find the filename should be changed.
> 
> Finally, try in the Table Reader View again.
> 
> If everything is normal. I would say this is a bug.

Do you mean to modify the pdf file name or the pdf file content title? If it is the former, I tried it and found that it still cannot be previewed normally in Table Reader View after importing.

**Comment by IZER0I** [comment]
here is PDF file

[PDF.pdf](https://github.com/Future-Scholars/paperlib/files/14617426/PDF.pdf)

**Comment by GeoffreyChen777** [comment]
<img width="1041" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/a3751bcb-d200-4c73-8d2b-4aa470f6cb32">

On my device, everything is ok.

Could you please remove this paper and reimport it again?

**Comment by IZER0I** [comment]
I tried deleting and re-importing, but it still doesn't work.

**Comment by GeoffreyChen777** [comment]
Currently I have no idea how to solve it. Do you use wechat?

https://share.1password.com/s#bjj8Qhq8qGJOKCN_MtDXwV9Ng55WFmGuTCcfuJ15Lmw

I wish to see the full path of this file.

**Comment by GeoffreyChen777** [comment]
Fixed.
