### ISSUE TITLE
[Question] 在安装 Microsoft Word 插件时未找到“安装”按钮

### ISSUE THREAD

**Issue by yhdsl** [Future-Scholars/paperlib#417]
我当前在 Windows11 上安装了 Office 365 以及 PaperLib-3.0.1
但是在按照 `Microsoft Word 插件安装文档` 中的步骤进行时
并没有在“导出”选项卡中找到“安装”按钮

![image](https://github.com/Future-Scholars/paperlib/assets/56674878/7cc7beed-9d87-42b6-895d-c4093897dd65)

我继续尝试了 2.2.9 版本，发现与文档中记录的一致

![image](https://github.com/Future-Scholars/paperlib/assets/56674878/cc2b4b59-e420-4777-87fd-a083a179f09b)

---

所以请问当前 Microsoft Word 插件是在V3版本中暂时被移除了吗？

**Comment by GeoffreyChen777** [comment]
3.0版本请去插件里安装msword插件
