### ISSUE TITLE
[BUG] Cannot reopen paperlib after the window is closed with `command+w` shortcut.

### ISSUE THREAD

**Issue by brant-ruan** [Future-Scholars/paperlib#420]
**Describe the bug**
After I close Paperlib's window with `command + w` shortcut and reopen it, Paperlib will get stuck on the initialization startup interface and cannot enter the literature interface. Then I have to force quit Paperlib, but get an error message:

**Screenshots or Log**
<img width="1419" alt="Xnip2024-03-18_10-40-20" src="https://github.com/Future-Scholars/paperlib/assets/13882906/6b30a796-9c9c-44a4-b027-29344589fa45">

**System (please complete the following information):**
 - OS: macOS 13.6.5 (Intel)
 - Paperlib Version: 3.0.2

**Comment by GeoffreyChen777** [comment]
Could you please try to search the activity monitor  to see if Paperlib is really exited?

**Comment by GeoffreyChen777** [comment]
Hi, I can reproduce the first `cmd+w` bug.

For the error message. I guess you installed the `paperlib-preview-extension`.

It's for Windows and Linux. It's unnecessary for macOS users. Please uninstall it.

**Comment by giorgosgiapis** [comment]
Same error happens on my arm-based Mac (MacOS 14.3.1) when I close paperlib with CMD+W shortcut.

**Comment by GeoffreyChen777** [comment]
Fixed.
