### ISSUE TITLE
[Feature Request] TUI

### ISSUE THREAD

**Issue by hhoeflin** [Future-Scholars/paperlib#421]
Hi,

one great feature would be to have a TUI interface to this library! Is something like that planned?

Best

Holger

**Comment by GeoffreyChen777** [comment]
Hi, what is TUI? terminal cli?

**Comment by hhoeflin** [comment]
Text-based user interface, which exists for many tools, like git (e.g. lazygit) etc.

**Comment by GeoffreyChen777** [comment]
OK, I know lazygit.

Sorry I have no plan for that. Paperlib is a GUI app.

Basically, to implement a TUI version Paperlib, you need to figure out how to connect the realm database:
https://www.mongodb.com/docs/realm/sdk/

And how to import a PDF is also a problem.

Anyway, contributions are welcome.

**Comment by hhoeflin** [comment]
Thanks. Yeah I assume it would require redoing the GUI part.

showing pdf could just be done through command line call. 

Unfortunately by Typescript is not good enough for this.
