### ISSUE TITLE
[BUG] Some Chinese UI are not adapted

### ISSUE THREAD

**Issue by Rccubc** [Future-Scholars/paperlib#422]
**Describe the bug**
After switching the language to Chinese, some menus in the main view are still in English.

**Screenshots or Log**
![image](https://github.com/Future-Scholars/paperlib/assets/64493219/00735c2c-8d3e-4192-9d7a-bb4586174721)

**System (please complete the following information):**
 - OS: Windows 11
 - Paperlib Version 3.0.2

**Comment by GeoffreyChen777** [comment]
Hi thanks.

If you want to contribute to this:

Replace:
https://github.com/Future-Scholars/paperlib/blob/2c64257610ada40d913f77197f733381b8927aff/app/renderer/ui/main-view/menubar-view/window-menu-bar.vue#L326

with `{{ $t("menu.listview") }}`

https://github.com/Future-Scholars/paperlib/blob/2c64257610ada40d913f77197f733381b8927aff/app/locales/locales/zh.CN.json#L76

**Comment by Rccubc** [comment]
> Hi thanks.
> 
> If you want to contribute to this:
> 
> Replace:
> 
> https://github.com/Future-Scholars/paperlib/blob/2c64257610ada40d913f77197f733381b8927aff/app/renderer/ui/main-view/menubar-view/window-menu-bar.vue#L326
> 
> with `{{ $t("menu.listview") }}`
> 
> https://github.com/Future-Scholars/paperlib/blob/2c64257610ada40d913f77197f733381b8927aff/app/locales/locales/zh.CN.json#L76

OK.

**Comment by Rccubc** [comment]
Which branch should I PR to? dev?
