### ISSUE TITLE
[Feature Request] Minimize to tray option

### ISSUE THREAD

**Issue by HelixCarinae** [Future-Scholars/paperlib#424]

**Comment by GeoffreyChen777** [comment]
Hi, for Windows?

**Comment by HelixCarinae** [comment]
Windows is the main one I had in mind, but possibly for Linux too if applicable.

**Comment by GeoffreyChen777** [comment]
Could you please explain why you need this feature?
If you want to minimize the UI, just clicking the `-` in the menu bar should be enough.

**Comment by HelixCarinae** [comment]
Mostly just to reduce taskbar clutter. My use case is mostly having it run minimized and adding articles as I'm browsing so I'm not really interacting directly with paperlib (or in the past Zotero) too much. 

To be honest I thought this would be a more straightforward request (what a fool I was) that might have a builtin function, but looking into it a bit it seems a bit more involved. I'd be willing to try and get this working on my own if you would like.

**Comment by GeoffreyChen777** [comment]
Hi, I'm going to close this as it's inactive.

Feel free to reopen it. I'm still looking forward to your contribution.
