### ISSUE TITLE
[Feature Request] Sort by tag count

### ISSUE THREAD

**Issue by MinusGix** [Future-Scholars/paperlib#427]
It would be nice to be able to sort papers by the number of tags they have. Often I don't tag papers immediately, but then would tag a bunch at once, which sorting by tag count (to quickly get zero or low tag papers) makes easy.

**Comment by GeoffreyChen777** [comment]
Hi, it could be achieved by advanced searching or a smart filter: `tags.@count == 0`

<img width="302" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/511a68ed-4d7c-481f-bc95-29479014aa6e">


<img width="738" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/3b1d4254-19f9-45f2-ab2b-56875c3630a5">

You should manually edit the query sentence of the smartfilter as the UI editor doesn't support `@count` yet.

**Comment by GeoffreyChen777** [comment]
Flor low tag papers you can try `tags.@count <= x`

**Comment by MinusGix** [comment]
Oh, that works. Thanks!
