### ISSUE TITLE
[BUG] Katex render error lead to no abstract in article preview

### ISSUE THREAD

**Issue by renecotyfanboy** [Future-Scholars/paperlib#428]
**Describe the bug**
Abstract with buggy maths formula will crash the rendering and hide the whole abstract

**To Reproduce**
1. Add [this article](https://arxiv.org/abs/2403.11635) which has custom \sun command which are not declared
2. Try to read the abstract from the sidebar
3. See error

**System (please complete the following information):**
 - OS: Sonoma 14.4
 - Paperlib 3.0.2

**Additional context**
This occurred when fetching this morning's astro-ph arxivs

**Comment by GeoffreyChen777** [comment]
Thanks, will investigate.

**Comment by GeoffreyChen777** [comment]
Hi, this has been fixed. Please wait for the next release.
