### ISSUE TITLE
[Feature Request] Make it possible to clear rating

### ISSUE THREAD

**Issue by giorgosgiapis** [Future-Scholars/paperlib#430]
After assigning a rating to a paper it's impossible to clear the rating. It would be nice to add that option.

Operating System: MacOS

**Comment by GeoffreyChen777** [comment]
Do you mean to zero star?

**Comment by giorgosgiapis** [comment]
> Do you mean to zero star?

Yes, right now I can only modify it.

**Comment by igoogolx** [comment]
Sure! Would the double-click work for you? Like [this](https://ant.design/components/rate)

**Comment by GeoffreyChen777** [comment]
> Sure! Would clicking again work for you? Like [this](https://ant.design/components/rate)

Yes it look good!
