### ISSUE TITLE
[Feature Request] Perplexity API

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib#431]
@uservinu

Hi thanks for your suggestions.

1. Support manually adding Multiple Tags
Do you mean this?
<img width="552" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/e87afb1c-cf9c-4e6c-ab2e-a23ca30eeff3">

2. Support for VSCODE when working with tex files. with citation key search/author search.+Generate a .bib file with the included citations.
It's unnecessary to have a Vscode extension. Try `ctrl/cmd + shift + I`
![Screen Recording 2024-03-17 at 19 00 12](https://github.com/Future-Scholars/paperlib/assets/14183213/90c23897-4a06-45eb-b17f-69aa08141622)

3. Support for perplexity API.
Could you please provide more info about this? what is it?

**Comment by uservinu** [comment]
Hi Thanks for the quick reply. 
1. I did not check the edit option, I was expecting to have the edit feature in the right preview pane. Cool this will work.
2. Very neat, I did not know about this feature. This is the best feature IMO. This gif needs to be on the front page.
3.  https://www.perplexity.ai/pro this one is a chatgpt alternative but provides access to multiple models like claude etc.

**Comment by uservinu** [comment]
Perplexity supports using python openAI libraries. https://docs.perplexity.ai/docs/getting-started

**Comment by GeoffreyChen777** [comment]
> Hi Thanks for the quick reply.
> 
> 1. I did not check the edit option, I was expecting to have the edit feature in the right preview pane. Cool this will work.
> 2. Very neat, I did not know about this feature. This is the best feature IMO. This gif needs to be on the front page.
> 3. https://www.perplexity.ai/pro this one is a chatgpt alternative but provides access to multiple models like claude etc.

The focus issue should be solved now.
