### ISSUE TITLE
[Feature Request] Make CMD+Shift+I smoother

### ISSUE THREAD

**Issue by giorgosgiapis** [Future-Scholars/paperlib#432]
Currently, CMD+Shift+I shifts focus to Paperlib and when the citation is exported it doesn't move the view back to the previous window. This is a bit frustrating when working fullscreen on another app (e.g. VSCode for writing LaTex). It would make for a smoother experience if CMD+Shift+I functioned like Apple's spotlight (display on top of fullscreen window) or, if that's not possible, shift the view back to the window it was called from when closed.

Operating System: MacOS

**Comment by GeoffreyChen777** [comment]
Yes. I know this issue.

The reason is that Electron app doesn't support smooth focus back.

see here: https://stackoverflow.com/questions/50642126/previous-window-focus-electron

We use a workaround for this. However not good enough.

We will consistently improve this.

**Comment by giorgosgiapis** [comment]
I think [this](https://github.com/electron/electron/issues/4939) is what I am suggesting. Maybe there's something useful there.

**Comment by GeoffreyChen777** [comment]
I think I've found a solution to fix this. Now it looks like this:



https://github.com/Future-Scholars/paperlib/assets/14183213/53fdfc89-ad09-4f3c-838e-126c9bd433d1


Now it works with the fullscreened app.

And the focus recovery seems to be ok.

If you want to try now, please re-download the v3.0.3 (I replaced the previous 3.0.3 with a new build) and replace your current version. Or you can wait for the next release v3.0.4

**Comment by giorgosgiapis** [comment]
Works great! Thanks!
