### ISSUE TITLE
[Feature Request] CTRL/CMD + A  Hotkey Support

### ISSUE THREAD

**Issue by mohammedsaif-fb** [Future-Scholars/paperlib#433]
**Describe your feature request**
...
CTRL/CMD + A  Hotkey Support to select all the papers at a time.

**Comment by GeoffreyChen777** [comment]
Hi I'm waiting for this PR:
#364

However seems the contributor has been busy recently.

**Comment by igoogolx** [comment]
I will take this task if it's not assigned to someone else.

**Comment by GeoffreyChen777** [comment]
implemented #477
