### ISSUE TITLE
[Feature Request] A direct way to remove more than one paper from a folder

### ISSUE THREAD

**Issue by Rccubc** [Future-Scholars/paperlib#437]
**Problem**
I noticed that if I wanted to remove a paper from a `Folder` I needed to select it and edit the `Folder` label in the paper information panel on the right side of the main window. If I need to delete more than one paper from a folder, I can only seem to do it one by one.

**Describe your feature request**
A direct way to remove papers from a `Folder`. 
It is best to clearly distinguish between deleting a paper from the library and moving a paper out of a folder.

**Comment by GeoffreyChen777** [comment]
The problem is how to achieve this.

Contextmenu?

**Comment by Rccubc** [comment]
> The problem is how to achieve this.
> 
> Contextmenu?

How about adding a `Remove from` like the `Scrape from` in `Contextmenu`.

**Comment by GeoffreyChen777** [comment]
Suppose we have two papers, one is in FolderA, the other one is in FolderB.

We select both of them and right click. What should we have in this `remove from`?

**Comment by Rccubc** [comment]
or just in the folder selected status, there will be a `remove`?

**Comment by GeoffreyChen777** [comment]
I think it's doable. Hi would you mind try to implement this if you are happy:

1. get all folders of the selected papers here:
https://github.com/Future-Scholars/paperlib/blob/b14fc9b72843c62e89b82b8f2bfb736358ec4a51/app/renderer/ui/main-view/data-view/paper-data-view.vue#L150

2. Once we get the folder list, we need to modify the `showPaperDataMenu` method with an additional arg `categorizerList`:
https://github.com/Future-Scholars/paperlib/blob/b14fc9b72843c62e89b82b8f2bfb736358ec4a51/app/renderer/ui/main-view/data-view/paper-data-view.vue#L153-L155

type definition:
```
categorizeList: {
  type: CategorizerType      // PaperTag or PaperFolder,
  name: string,
  id: OID
}[]
```

3. in `showPaperDataMenu`, we should construct the contextmenu `remove from` according to the `categorizeList`.

4. Once an item is clicked, we should listen to the corresponding event and handle it. You can refer to the `ScrapeFrom` for inspiration:

https://github.com/Future-Scholars/paperlib/blob/b14fc9b72843c62e89b82b8f2bfb736358ec4a51/app/renderer/ui/main-view/main-view.vue#L329-L338
https://github.com/Future-Scholars/paperlib/blob/b14fc9b72843c62e89b82b8f2bfb736358ec4a51/app/renderer/ui/main-view/main-view.vue#L132

5. we should have a new method named `removeSelectedEntitiesFrom`. In this method, we first get all selected papers, then filter out the categorizer we wish to remove. then update these selected papers with `paperService.update(...)`

**Comment by Rccubc** [comment]
I'll try it
