### ISSUE TITLE
[Feature Request] The potential of integrating Zotero-style

### ISSUE THREAD

**Issue by invisprints** [Future-Scholars/paperlib#441]
Love the software so much, I used https://papermemory.org/ to update my bib, but paperlib seems even better!

The last reason I still use Zotero as my primary paper management tool is the plugins developed by @MuiseDestiny. https://github.com/MuiseDestiny/zotero-style and https://github.com/MuiseDestiny/zotero-reference are wonderful plugins that bring the Zotero to a new level! I don't know if the paperlib have the potential to integrating these plugins, such as Publication Tags, Nested Tags, citing counts, displaying the mutual citation relationships of within the existing papers.

**Comment by GeoffreyChen777** [comment]
Hi I have never used them. You can tell me some features, I will tell you if it is doable in Paperlib.

1.what is publication tags?
2. Nested tags: no and never. This has been discussed a lot in Paperlib community. Tags must be atomic. See https://github.com/Future-Scholars/paperlib/discussions/354
3. citation count: please install the paperlib-citation-count-extension.
4. Mutual relationship: doable. But need someone to develop a extension for that.

**Comment by GeoffreyChen777** [comment]
Nested tags should be nested folders. Tags cannot be in hierarchical.

**Comment by invisprints** [comment]
Thank you. The nested folders in paperlib have implemented the nested tags I was looking for. You did a great job! 

The publication tags indicate the journal level of the paper, such as CCF, SCI, IF, etc. I found someone who had a similar idea to mine here https://github.com/Future-Scholars/paperlib/issues/398.

The picture describes the mutual relationship I want, I don't know if the paperlib extension API supports drawing a new panel like it. And the red circle in the picture means the paper is already in the paperlib.
![image](https://github.com/Future-Scholars/paperlib/assets/15833553/3c886dc2-4048-4410-a980-c5004e29021a)

**Comment by GeoffreyChen777** [comment]
1. You can try our nested smart filters. I believe it is even more powerful than nested folders. https://paperlib.app/en/doc/smart-filter/

2. journal level: really easy. Just like what we did in the `paperlib-citation-count-extension`. Get the required data. Show it in the details panel. https://github.com/Future-Scholars/paperlib-citation-count-extension

3. mutual relationship: certainly doable. We support new-window extensions. In the new window, you can do whatever you want:
https://paperlib.app/en/extension-doc/ext-types/new-window-ext.html

**Comment by GeoffreyChen777** [comment]
I'm going to close this issue as we don't have the capacity to develop such an extension right now.

We hope the community can get involved in extension development. If you wish to try, really welcome.
