### ISSUE TITLE
[Feature Request] Delete the downloaded PDF from browser extension

### ISSUE THREAD

**Issue by giorgosgiapis** [Future-Scholars/paperlib#444]
When using the Chrome extension to import a paper, the downloaded paper stays in the downloads folder and a new (renamed) copy gets added to the PDF storage folder. It would be nice if the downloaded paper got permanently deleted from the downloads folder.

This happens on MacOS and the PDF storage folder for paperlib is set to a Google Drive folder (maybe this plays a role).

**Comment by GeoffreyChen777** [comment]
use this:

<img width="733" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/e045927e-d2de-450c-a8f1-7fc49d25fff7">

**Comment by giorgosgiapis** [comment]
Oh, you're right I hadn't noticed that. Sorry...
