### ISSUE TITLE
[BUG] Appearance error after window maximization and `cmd+w`

### ISSUE THREAD

**Issue by brant-ruan** [Future-Scholars/paperlib#446]
**Describe the bug**
1. Open Paperlib.
2. Press `ctrl+cmd+f` to maximize the window.
3. Press `ctrl+w` to close the window. **Then the window becomes a whole black screen and fails to interact.**
![Xnip2024-03-21_16-02-58](https://github.com/Future-Scholars/paperlib/assets/13882906/6d02b254-a19a-4ad3-9864-48cca1d8f39d)
4. To close the black window, wipe three fingers upwards on the touch panel to show all active tasks, hover on the Paperlib task and click the emerging upper left button. Then, the window is closed.
5. Click Paperlib in the dork once again, **the window becomes very weird** (very small and located upwards of the screen):
![Xnip2024-03-21_16-07-56](https://github.com/Future-Scholars/paperlib/assets/13882906/3608f801-81dc-4219-8e79-dca1e3e7421e)

**System (please complete the following information):**
 - OS: macOS 13.6.5 (Intel)
 - Paperlib Version 3.0.3

**Comment by GeoffreyChen777** [comment]
Because `cmd+w` is only hiding the window, not closing.

I think before hiding, unmaximizing the window can fix this.

**Comment by brant-ruan** [comment]
Got it. I will try this before hiding the window. Thank you!
