### ISSUE TITLE
[Enhance] Refactor shourtcuts management.

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib#447]

**Comment by GeoffreyChen777** [comment]
@igoogolx 

The shortcuts management has introduced so many bugs. Some have not been solved yet: #453 

I think we should prioritize resolving this issue.

Feel free to tell me if you need any help.

**Comment by igoogolx** [comment]
> @igoogolx If we just use the `shortcutService` for shortcuts, is there any way to stop the event propagation when the editing view is showing?
> 
> We register `space` in the main view. When the editing view shows, we press `space`, the event should stop at the editing view. It should not propagate to the main view.
> 
> Any idea how to achieve this?

No. I think we still need a method to disable other shortcuts when the editing view is showing.

**Comment by igoogolx** [comment]
Why do we need `registerInInputField ` in `shortcut-service`? I mean, what's the difference between it and `register`?

**Comment by GeoffreyChen777** [comment]
> Why do we need `registerInInputField ` in `shortcut-service`? I mean, what's the difference between it and `register`?

Because some shortcuts should be disabled in `<input/> <textfield/>`. Some should always be enabled.

**Comment by GeoffreyChen777** [comment]
I have some very initial ideas:

 1. We only use the `shortcutService` to manage shortcuts.
 2. We have a priority group mechanism in `shortcutService`.
    - shortcuts should be registered with different priority levels.
    - there is an API to set/unset the current working priority level of `shortcutService`:
        - `shortcutService.setPriorityLevel(...)`
        - `shortcutService.resetPriorityLevel(...)`: reset the priority level to the previous one.
3. We listen to all keydown events, just like what we do now in `shortcutService`. According to the current working priority level, we do actions registered with priority >= the current working priority.
4. `<input/>/<textfiled/>` should automatically have a very high priority, such as 99. As we know the `event.target` is an input or not, we can automatically handle the current working priority level for it without `shortcutService.setPriorityLevel(...)`


For example, for the `space`:

- in the mainview, pressing `space` should show the preview window. The current priority level is 0, we register the previewing action with priority 0.
- in the editing view, we should disable `space` for previewing. So when we show the editing view, we increase the working priority level to 1. Now the previewing action will not be trigered.
- when we close the editing view, we reset the priority level to 0.

What do you think about this design?

**Comment by GeoffreyChen777** [comment]
Yes, agree, the views number is limited, we can pre-define such groups.

For Global shortcuts: quick reference plugin. I think we need to regeister it in the main process. shortcutService is in the renderer process.

**Comment by igoogolx** [comment]
Sure. BTW, I tried to implement `shortcut-service ` in the renderer process by [this](https://www.electronjs.org/docs/latest/tutorial/keyboard-shortcuts#intercepting-events-in-the-main-process) and expose it to the renderer with rpc. However, I found it hard to maintain in the multi-process environment. So global shortcuts in the main process and others in the renderer process are better.  

**Note**: Local shortcuts are implemented by `Menu.setApplicationMenu` now. But with this design, we will listen to the keyboard event on the web page to implement it like business shortcuts.

What do you think about this?

**Comment by GeoffreyChen777** [comment]
We keep the menu items and remove all shortcuts binding.

<img width="421" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/133c2479-cecc-4217-831b-3195573d5ac4">

**Comment by igoogolx** [comment]
Why does onBlur do nothing in the command bar when the mouse is over? @GeoffreyChen777 

https://github.com/Future-Scholars/paperlib/blob/0b3beba0810d36aa4caa3bd9d4ae733139b15860/app/renderer/ui/main-view/menubar-view/components/command-bar.vue#L211

**Comment by GeoffreyChen777** [comment]
When the command panel shows up, we can use the mouse to choose commands.

Once we click a command, the `<input>` will lose focus. So here we need to return.

**Comment by igoogolx** [comment]
> I have some very initial ideas:
> 
> 1. We only use the `shortcutService` to manage shortcuts.
> 2. We have a priority group mechanism in `shortcutService`.
>    
>    * shortcuts should be registered with different priority levels.
>    * there is an API to set/unset the current working priority level of `shortcutService`:
>      
>      * `shortcutService.setPriorityLevel(...)`
>      * `shortcutService.resetPriorityLevel(...)`: reset the priority level to the previous one.
> 3. We listen to all keydown events, just like what we do now in `shortcutService`. According to the current working priority level, we do actions registered with priority >= the current working priority.
> 4. `<input/>/<textfiled/>` should automatically have a very high priority, such as 99. As we know the `event.target` is an input or not, we can automatically handle the current working priority level for it without `shortcutService.setPriorityLevel(...)`
> 
> For example, for the `space`:
> 
> * in the mainview, pressing `space` should show the preview window. The current priority level is 0, we register the previewing action with priority 0.
> * in the editing view, we should disable `space` for previewing. So when we show the editing view, we increase the working priority level to 1. Now the previewing action will not be trigered.
> * when we close the editing view, we reset the priority level to 0.
> 
> What do you think about this design?

Even if the views are limited, defining all views as constants is unnecessary. So we can further simplify the mechanism. Here I propose the scope group mechanism based on the priority group mechanism. **The core idea is to stop the propagation of events across other scopes.**

 1. We only use the `shortcutService` to manage shortcuts.
 2. We have a scope group mechanism in `shortcutService`.
    - shortcuts should be registered with different scopes.
    - there is an API to set/unset the current working scope of `shortcutService`:
        - `shortcutService.updateScope(...)`： return a clean function to reset the scope to the previous one.
3. We listen to all keydown events, just like what we do now in `shortcutService`. According to the current working scope, we do actions registered with scope **===** the current working scope.
4. There will be 3 scopes: Main, Overlay, Input. **Note**: They are unique identifiers, not representative of parent-child relationships.

![image](https://github.com/Future-Scholars/paperlib/assets/27353191/b61745ad-0223-4508-8944-28bb1ecd31b8)

For example, for the `space`:

- in the mainview, pressing `space` should show the preview window. The current scope is `Main`, we register the previewing action with scope `Main`.
- in the editing view, we should disable `space` for previewing. So when we show the editing view, we set the working scope to `Overlay`. Now the previewing action will not be trigered.
- when we close the editing view, we reset the scope to `Main`. 

What do you think about this? @GeoffreyChen777

**Comment by igoogolx** [comment]
I have implemented most of the scope group mechanism in https://github.com/Future-Scholars/paperlib/tree/enchance/refactor-shourtcuts-management. You can pull the code and check it. @GeoffreyChen777

**Comment by GeoffreyChen777** [comment]
Looks good but I have a question.

Let's use the `ctrl+s` in the editing view for example:

`ctrl+s` should save and close the editing view in both `overlay` and `input` scopes. So here how to register this `ctrl+s`?

We register twice?

**Comment by GeoffreyChen777** [comment]
I briefly looked through the new `shortcutService`.
https://github.com/Future-Scholars/paperlib/blob/enchance/refactor-shourtcuts-management/app/renderer/services/shortcut-service.ts

I cannot understand how you handle the `<input/>`.

Seems there is no more `input` element detection. We need to register shortcuts every time a `<input>` gets focused?

**Comment by igoogolx** [comment]
I think there are two scenarios with the <input> now.

1. We actively register the shortcut keys, which are in the `Input `scope and can function properly.
2. For the regular input, we don't take any action. Since it will have an `Overlay` scope from its parent compent, I believe it should also work fine. For example, `input` in the preference page will be in `Overlay` scope because the preference page is in  `Overlay` scope.

I mean every `input` will be in `Input ` or `Overlay` scope. 

Did I miss something?

**Comment by GeoffreyChen777** [comment]
In the left sidebar, we can edit the name of a tag/folder.

In this case, we are in the `Main` scope. Here we have many main scope shortcuts, such as `space`, `enter` should be disabled.

When we show the `<input />` for name editing, we should set the scope to `Input`. In the current implementation, do we need to change/reset this scope explicitly?

**Comment by GeoffreyChen777** [comment]
I mean as we can check if the `e.target` is a `<input>` or not:

https://github.com/Future-Scholars/paperlib/blob/ab48ebf3f0878920dcce3325c15ece177a3a2b34/app/renderer/services/shortcut-service.ts#L31

We can automatically set/unset the scope of `Input` without doing it explicitly.

**Comment by igoogolx** [comment]
I see. Yours is better. We need to set/unset the scope of Input explicitly now. Like this:

![image](https://github.com/Future-Scholars/paperlib/assets/27353191/d351a4c4-7f79-43a0-ba15-0e77df2119cb)

**Comment by igoogolx** [comment]
> I mean as we can check if the `e.target` is a `<input>` or not:
> 
> https://github.com/Future-Scholars/paperlib/blob/ab48ebf3f0878920dcce3325c15ece177a3a2b34/app/renderer/services/shortcut-service.ts#L31
> 
> We can automatically set/unset the scope of `Input` without doing it explicitly.

I will add `input `element detection.

**Comment by igoogolx** [comment]
Since then, there have been some new changes.

1. Support hot reloading: Changes will take effect without restarting.
https://github.com/Future-Scholars/paperlib/blob/b083df364f88830ddedfd0c6c83bb5d559662b17/app/renderer/ui/main-view/main-view.vue#L693
2. New Global Scope: Shortcuts with this scope will always be triggered. 
https://github.com/Future-Scholars/paperlib/blob/b083df364f88830ddedfd0c6c83bb5d559662b17/app/renderer/ui/main-view/main-view.vue#L604
3. Support setting the scope explicitly when registering shortcuts
https://github.com/Future-Scholars/paperlib/blob/b083df364f88830ddedfd0c6c83bb5d559662b17/app/renderer/services/shortcut-service.ts#L79

**Comment by GeoffreyChen777** [comment]
yes looks like the global scope is necessary for `cmd+w`. BTW, I think in macOS. the keycode for `command` is `Meta`.

**Comment by igoogolx** [comment]
> yes looks like the global scope is necessary for `cmd+w`. BTW, I think in macOS. the keycode for `command` is `Meta`.

`Meta` will be formatted as `Command`.

https://github.com/Future-Scholars/paperlib/blob/d4dca2f2bb0b2ab1db9e32f4315eecffedcfdd54/app/common/utils.ts#L10
