### ISSUE TITLE
[Feature Request] Check extension updates every day.

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib#452]

**Comment by GeoffreyChen777** [comment]
May I assign this to you @ischaojie ?

**Comment by GeoffreyChen777** [comment]
Sorry I assign to the wrong person @ischaojie .

@charlieJ107 may I assign this to you?

**Comment by charlieJ107** [comment]
Sure, I'll take this 😉

**Comment by charlieJ107** [comment]
We currently check for updates to each extension when the extension management service is initialized. Do we think that users may not exit or restart Paperlib for many days?

**Comment by GeoffreyChen777** [comment]
Yes, that's why we need this feature. For me, I barely exit Paperlib.

We already have an API for update checking, and you can just use this `SchedulerService` to create a task to implement this feature.

**Comment by GeoffreyChen777** [comment]
Or,

You can write the logic of update checking in the extension management service by copying some codes from `SchedulerService`. I think this option should be better.
