### ISSUE TITLE
[BUG] Some bugs when editing metadata.

### ISSUE THREAD

**Issue by Lincest** [Future-Scholars/paperlib#453]
**Describe the bug**
1. can not press arrow key (↑, ↓, ←, →) when make notes.
2. If press "`<space>`" when editing metadata, the preview mode is triggered.

**Screenshots or Log**

screenshot for problem 1

<img width="500" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/43769667/6644e80e-c8ac-4a75-b12d-ed75259912b3">

screenshot for problem 2: 

<img width="941" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/43769667/1c1b0cdc-66b3-4e85-bda3-c50858e6c666">

**System (please complete the following information):**
 - OS: macos 
 - Paperlib Version: 3.0.5

**Comment by GeoffreyChen777** [comment]
Please wait for this: #447 

We are working on this.

**Comment by igoogolx** [comment]
We register 'View-preview' twice. The reason for problem 2 is that the shortcut registered in the `main-view` can't be disabled. I think that we can delete the code in the ` main-view` to fix the problem 2. @GeoffreyChen777 

https://github.com/Future-Scholars/paperlib/blob/0b3beba0810d36aa4caa3bd9d4ae733139b15860/app/renderer/ui/main-view/main-view.vue#L456

https://github.com/Future-Scholars/paperlib/blob/0b3beba0810d36aa4caa3bd9d4ae733139b15860/app/main/services/menu-service.ts#L193

**Comment by igoogolx** [comment]
Regarding problem 1, I can't reproduce it on Windows. Could you plz help with it on macOS? @GeoffreyChen777

**Comment by GeoffreyChen777** [comment]
@igoogolx Yes, looks like it can fix problem 2.

I would suggest removing all shortcuts binding in the `menuService` (except that global shortcut). Just use the `shortcutService` for shortcuts.

In this way, we don't need to pay attention to when to enable and when to disable shortcuts.

**Comment by GeoffreyChen777** [comment]
> Regarding problem 1, I can't reproduce it on Windows. Could you plz help with it on macOS? @GeoffreyChen777

@igoogolx I can't reproduce this either.

**Comment by igoogolx** [comment]
Thanks. Since problem 1 can't be reproduced, I think we can fix this by deleting the code now without #447 and I will file a PR. @GeoffreyChen777

**Comment by GeoffreyChen777** [comment]
Solved. #465
