### ISSUE TITLE
[BUG] Why do we need to disable shortcuts when lose focus?

### ISSUE THREAD

**Issue by igoogolx** [Future-Scholars/paperlib#454]
https://github.com/Future-Scholars/paperlib/blob/e69437ff801084d9701377f076c2929b157b2f0c/app/renderer/ui/app-view.vue#L269

According to the [docs](https://www.electronjs.org/docs/latest/tutorial/keyboard-shortcuts#local-shortcuts), local shortcuts are triggered only when the application is focused. So I think it is unnecessary. The problem is since #449, the global shortcuts will be disabled too.

**Comment by GeoffreyChen777** [comment]
The reason is that, we have two windows, the main window and the quick reference window. When the quick reference window shows up, we need to disable some shortcuts such as space, enter.

This is a really emergency bug. We need to fix it soon and release a new version.

**Comment by igoogolx** [comment]
I have filed a PR to fix it.
