### ISSUE TITLE
[BUG] trouble with bibtex imports

### ISSUE THREAD

**Issue by blake5634** [Future-Scholars/paperlib#457]
Scrapers or parsers crash when importing a bibtex file.   Ideally there would be a bibtex import option in the settings import tab.   It seems you can drag a bibtex file into the main window but that sometimes works and sometimes doesn't work.  

1. Drag a .bib file (bibtex format) into the main window. 
2. Error messages usually occur, OR, basic bibtex data is not included in the paper metadata after import.    Overall paper count does not increase or change. 
 
Screenshot:
![image](https://github.com/Future-Scholars/paperlib/assets/6518601/a16f7d4a-037d-4aa5-8dd7-f3c281f824d3)

**System (please complete the following information):**
 - OS: Linux
 - Paperlib Version 3.0.6

**Additional context**
My use case is I'd like to paste or read in bibtex data and have Paperlib parse that and put them in the library (ideally downloading the PDFs).

**Comment by GeoffreyChen777** [comment]
The reason is that your `.bib` contains unparseable bibtex entries.

It's hard to fix this bug we don't know which entry caused this.

For your case, you can share your `.bib` with us.

**Comment by GeoffreyChen777** [comment]
Close as inactive. Feel free to reopen.
