### ISSUE TITLE
[Feature Request] support openrouter

### ISSUE THREAD

**Issue by mintisan** [Future-Scholars/paperlib#467]
Set the openrouter address and API as shown below.

<img width="378" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/9136049/afb2e7d2-b2b5-4bf3-85e9-f54aa217b4e5">

However, when I use the summary, the following error is displayed.

<img width="274" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/9136049/dd684433-cf10-4130-b902-169521af8eb3">

I don't know if it's not supported.

**Comment by GeoffreyChen777** [comment]
The proxy API's route must be exactly the same as the OPENAI's or Gemini's.

See:

https://github.com/Future-Scholars/paperlib-ai-summary-extension/blob/595dfbf064b8e020273d6c5026ecadfe2c479fba/src/services/ai-service.ts#L172

https://github.com/Future-Scholars/paperlib-ai-summary-extension/blob/595dfbf064b8e020273d6c5026ecadfe2c479fba/src/services/ai-service.ts#L237

**Comment by GeoffreyChen777** [comment]
I am not familiar with your proxy API. So you need to try it by yourself. Sorry about that.

**Comment by mintisan** [comment]
It works when use `https://openrouter.ai/api/`, thanks.
