### ISSUE TITLE
IOS version[Feature Request] 

### ISSUE THREAD

**Issue by Garibelhj** [Future-Scholars/paperlib#468]
Is there any plan for an ios version?

**Comment by GeoffreyChen777** [comment]
Sorry, no.

I'm a PhD student, so I have my research work🤣. I don't have any extra time to develop an iOS version. Maintaining macOS/Win/Linux has drained me.

But I'm welcome to any contribution.

**Comment by Garibelhj** [comment]
> Sorry, no.
> 
> I'm a PhD student, so I have my research work🤣. I don't have any extra time to develop an iOS version. Maintaining macOS/Win/Linux has drained me.
> 
> But I'm welcome to any contribution.

okay, thanks. I'm  also a PhD student, my main research areas are network security, GNN, and LLM. I welcome any discussions and exchanges on these topics.
