### ISSUE TITLE
[Feature Request] Suggest that the browser automatically redirects to the paper webpage when clicking on the publication place

### ISSUE THREAD

**Issue by yym68686** [Future-Scholars/paperlib#469]
Suggest that the browser automatically redirects to the paper webpage when clicking on the publication place

<img width="192" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/31803242/3d8432a7-e9e6-4340-9262-506891fe307f">

**Comment by GeoffreyChen777** [comment]
For papers with arxiv id and doi, it's easy to achieve this. Is it enough?

For papers without such an identifier, it's hard.

**Comment by yym68686** [comment]
I know that I can find papers through arXiv ID and DOI. I need to first open the paper details panel, then copy the arXiv ID and DOI, then open the browser, and search for the paper through the arXiv ID and DOI number, which will be more troublesome for me.

Every time I want to reread a paper and see that the publication is listed as arXiv, I unconsciously click on arXiv, but actually, nothing happens. This is very frustrating for me. I think being able to click on the publisher to directly reach the paper's page is very intuitive and user-friendly. I hope this feature can be added.

**Comment by GeoffreyChen777** [comment]
I mean, we can add this feature. But only for papers with arxivID and DOI. With such an identifier, it would be easy to infer their online source URL.

For papers without such an identifier, we cannot.

**Comment by charlieJ107** [comment]
Just a catch up if there's not yet assigned to someone else, I'll take this task and implement this feature. @GeoffreyChen777

**Comment by GeoffreyChen777** [comment]
@charlieJ107 sure, thanks!

**Comment by GeoffreyChen777** [comment]
implemented. Please wait for the next release.

Now we have a new section called 'Online Resources' in the details panel. It looks like this:

<img width="267" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/17d326cc-7041-49c6-bac3-cd82bcdce298">
