### ISSUE TITLE
[Feature Request] Support more shortcuts in the preview extension 

### ISSUE THREAD

**Issue by igoogolx** [Future-Scholars/paperlib#470]
**Describe your feature request**
...
Hi! Since #465 , I think it is time to introduce more shortcuts in the preview extension. I'm working on two features.

1. click `shortcutPreview `shortcut again to close the preview window
2. preview next and previous files with shortcuts

You can learn more in the demo below. What do you think about this? @GeoffreyChen777 

![Recording 2024-04-01 100500](https://github.com/Future-Scholars/paperlib/assets/27353191/67aba973-8000-45f1-ba02-4927e93c7236)

**Comment by GeoffreyChen777** [comment]
Hi it's cool.

I tried to implement the second feature before. However, it's impossible on macOS as we use the system's quicklook for previewing. There is no event in Electron to tell us if the quicklook window is opened/closed.

It's doable in Windows and Linux with the `preview-extension`. Your demo looks good.

**Comment by igoogolx** [comment]
You just reminded me that I didn't consider the implementation on macOS. It seems that this feature can't be implemented on macOS unless we use the preview extension instead of the quick look.

**Comment by GeoffreyChen777** [comment]
For macOS, we just keep the current experience. We can only add these features for windows and linux.

**Comment by igoogolx** [comment]
Could you plz help release a new version of paperlib-api? @GeoffreyChen777

**Comment by GeoffreyChen777** [comment]
It requires a new release of the main APP. I’m out for a trip these days. Will be back tomorrow.

**Comment by igoogolx** [comment]
> It requires a new release of the main APP. I’m out for a trip these days. Will be back tomorrow.

Thanks. Enjoy your trip:).

**Comment by GeoffreyChen777** [comment]
Released.
