### ISSUE TITLE
[BUG] Papers downloaded through researchgate

### ISSUE THREAD

**Issue by omrihaber** [Future-Scholars/paperlib#472]
There's a paper I've linked its official code base in [papers with code](https://cs.paperswithcode.com/paper/parallel-maximum-clique-algorithms-with)
if I download and add the paper through [arxiv version](https://arxiv.org/pdf/1302.6256v2.pdf) it adds the github repo to the metadata as expected.

However if i download it through [researchgate](https://www.researchgate.net/publication/235712357_A_Fast_Parallel_Maximum_Clique_Algorithm_for_Large_Sparse_Graphs_andTemporal_Strong_Components) and add it to paperlib its not able to scrape and add the [github repository](https://github.com/ryanrossi/pmc)

I think this might happen due to a page researchgate adds prior to the actual papers downloaded through them:
![image](https://github.com/Future-Scholars/paperlib/assets/76410724/980a58d9-f606-465b-bf84-be55b42635be)

**Comment by GeoffreyChen777** [comment]
Click this to manually edit source code link:

<img width="513" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/9f5cd50f-c801-4268-be13-dc2671845868">

**Comment by omrihaber** [comment]
I see,
ty!

**Comment by omrihaber** [comment]
just making sure.

are these the correct queries done against paperswithcode? because I'm getting the same result with both queries
[Parallel+Maximum+Clique+Algorithms+with+Applications+to+Network+Analysis+and+Storage](https://paperswithcode.com/search?q_meta=&q_type=&q=Parallel+Maximum+Clique+Algorithms+with+Applications+to+Network+Analysis+and+Storage)

[A+Fast+Parallel+Maximum+Clique+Algorithm+for+Large+Sparse+Graphs+and+Temporal+Strong+Components](https://paperswithcode.com/search?q_meta=&q_type=&q=A+Fast+Parallel+Maximum+Clique+Algorithm+for+Large+Sparse+Graphs+and+Temporal+Strong+Components)

**Comment by GeoffreyChen777** [comment]
You can find this paper by two titles as the paperwithcode website does fuzzy searching.

However, in Paperlib, when we get the response from the paperwithcode API, we do a string comparison (title and authors) with a threshold to determine whether the result in the response is the data of the paper you imported. In this case, I believe the string similarity score is lower than the threshold.

**Comment by omrihaber** [comment]
I see, ty!
