### ISSUE TITLE
[Feature Request] Show links to scraped sources if available

### ISSUE THREAD

**Issue by omrihaber** [Future-Scholars/paperlib#473]
I would like to be able to quickly access the paper on paperswithcode/arxiv/other scraping sources if it can be found there.
i.e. if by scraping the paper the system found a match save a url/link of the paper as part of the metadata and show these links.

**Comment by GeoffreyChen777** [comment]
Duplicate #469

**Comment by GeoffreyChen777** [comment]
implemented. Please wait for the next release.

Now we have a new section called 'Online Resources' in the details panel. It looks like this:

see #469
