### ISSUE TITLE
[Question]  Advanced search function

### ISSUE THREAD

**Issue by houjialin** [Future-Scholars/paperlib#481]
Hi, thanks for your developing paperlib, I love it very much. However, I'm a little confusing about the advanced search function and can't use it very well, especially in the version 3.0. For example, currently I don't know how to search all papers tagged with "Archaea" with the Advanced search, and there is no helpful information neither in the official website or the tool itself. So could you please update the official document about the search function? It would be much helpful for me, thanks a lot !

By the way, I don't know why, but the browser's extension (Arc in MacOS), the \tagit and \summarize function all can't work in my laptop (I can access google actually). I feel so bad that I can't miss so much fun things about paperlib.

**Comment by GeoffreyChen777** [comment]
For advanced searching, you can lear it with the smart filter. By creating a smart filter, you will see a dialog. There are many options, once you choose them, you will see an automatically generated query sentence. That is the query sentence you can use in the advanced searching.

browser extension: could you please try it with Chrome? How do you use it?

\tag it etc require an LLM API KEY. Please go to the preference of the ai summary extension to setup.

**Comment by GeoffreyChen777** [comment]
As I cannot reproduce your issues, close for now, feel free to reopen.
