### ISSUE TITLE
[BUG] Build Failure

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib#486]
See https://github.com/Future-Scholars/paperlib/actions/runs/8600082345/job/23564310568

@igoogolx

**Comment by GeoffreyChen777** [comment]
I think we need to add a github action with `pnpm run prebuild` to prevent this in future.

**Comment by igoogolx** [comment]
> I think we need to add a github action with `pnpm run prebuild` to prevent this in future.

Agree. It seems that `pnpm run dev` won't check ts types.
