### ISSUE TITLE
Themes to support High contrast colours and custom colour palettes  [Feature Request] 

### ISSUE THREAD

**Issue by mohammedsaif-fb** [Future-Scholars/paperlib#489]
Current app only has light and dark mode, it would be nice to have it supports user configurable colour options to users or some kind of config file mapping similar to [vscode color themes](https://code.visualstudio.com/docs/getstarted/themes). This feature essentially could make the application more accessible.

**Comment by GeoffreyChen777** [comment]
duplicated #273
