### ISSUE TITLE
[Feature Request] Add a button to open the PDF file directly through the BibTeX launcher.

### ISSUE THREAD

**Issue by jianghao-zhang** [Future-Scholars/paperlib#492]
The file search and open function in Spotlight Search/Raycast is excellent and useful. I wonder if we could add a button to the BibTeX launcher (Cmd+Shift+I) of Paperlib to directly open the PDF file, similar to the image below:

<img width="712" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/81921082/a700364d-2594-4a96-9236-f6c077f4c552">

**Comment by jianghao-zhang** [comment]
Meanwhile, it would be best if we could find papers in the BibTeX launcher using the abbreviated name (e.g., "transformer" for "Attention is All You Need").

**Comment by GeoffreyChen777** [comment]
1. `cmd + enter` is occupied if you link to a folder.

<img width="623" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/fb0bdc25-b6fd-41ce-b1c1-9ec9a5d99c0e">

Honestly, there is no suitable shortcut in this window for this...

2. For an alias, just put it in the note.
<img width="586" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/c10c8355-4c14-4dfd-b2bb-4b7333688e91">

**Comment by jianghao-zhang** [comment]
Try using the Cmd+O?

**Comment by GeoffreyChen777** [comment]
Could you please tell me why we need this feature?

As the quick reference window is designed for citing references, it seems odd to open PDFs there.

**Comment by jianghao-zhang** [comment]
For myself, simply because I've used to opening anything with the Raycast.
For others, I believe it would also enhance convenience, particularly when they need to review the content of specific papers while simultaneously using other applications. Directly opening PDFs through the reference window could streamline this process.

PS: To find the annotated PDF file, we can implement similar functions directly using Raycast. However, the problem of duplicate PDF files may still hinder me.

**Comment by GeoffreyChen777** [comment]
I would suggest developing a Raycast extension for this.

Paperlib has an extension `paperlib-apihost-extension`. It exposes most services of Paperlib to other Apps.

You can use the exposed API to search papers via Raycast, open PDFs etc.

<img width="348" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/4cdc2afc-817c-4f42-a258-59d44125c9c3">

For Paperlib, our design philosophy is to keep it as simple as possible. Unless it's absolutely necessary, we are very cautious when adding new features. Opening a PDF within this window is not in line with the context, as the current function of this window is simply reference citation.

**Comment by jianghao-zhang** [comment]
Thank you for your consideration. I may work on it when I'm available (
