### ISSUE TITLE
[BUG] Unable to select custom csl file

### ISSUE THREAD

**Issue by yunfanzuo** [Future-Scholars/paperlib#497]
I can't pick a CSL file in preference-export-CSL Style-Import from a folder.
The "china-national-standard-gb-t-7714-2015-numeric.csl" is downloaded from [CSL Style Repository](https://github.com/citation-style-language/styles/blob/master/china-national-standard-gb-t-7714-2015-numeric.csl).

<img width="1093" alt="bug" src="https://github.com/Future-Scholars/paperlib/assets/59811265/5a49d5fc-dc74-4031-8044-9cf17450186e">

**Comment by GeoffreyChen777** [comment]
Just choose this folder.

**Comment by yunfanzuo** [comment]
Thank you!
