### ISSUE TITLE
[Feature Request] Automatically obtain a paper CCF rank.

### ISSUE THREAD

**Issue by AlphaGogoo** [Future-Scholars/paperlib#500]
**Describe your feature request**
Inspired by CCFrank of edge browser plug-in, can paperlib automatically obtain the CCF rank of the paper from the meta-information of the paper, so as to facilitate the sorting of the paper by users.
<img width="887" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/69681789/a8272bc6-e9c2-4081-b5ab-c240cf527f62">

**Comment by GeoffreyChen777** [comment]
see #299

please implement this with an extension.

As CCF is used only by CN users, we will never implement this in the main Paperlib App.

**Comment by AlphaGogoo** [comment]
> see #299
> 
> please implement this with an extension.
> 
> As CCF is used only by CN users, we will never implement this in the main Paperlib App.

I have implemented the above functions, the plug-in name is `paperlib-ccf-rank-scrape-extension` [link](https://www.npmjs.com/package/paperlib-ccf-rank-scrape-extension)

**Comment by GeoffreyChen777** [comment]
很棒，基本功能实现了，但是感觉有点不太准呢，CVPR咋ccf b了，你的数据源是啥

**Comment by AlphaGogoo** [comment]
> 很棒，基本功能实现了，但是感觉有点不太准呢，CVPR咋ccf b了，你的数据源是啥

我检查一下，数据提取可能出问题了

**Comment by AlphaGogoo** [comment]
> 很棒，基本功能实现了，但是感觉有点不太准呢，CVPR咋ccf b了，你的数据源是啥

方便说一下是哪个论文吗，我这边测试正常。

**Comment by AlphaGogoo** [comment]
我用的publication，匹配机制出现问题了，你可以帮忙看一下。
数据源在这里：

[中国计算机学会推荐国际学术会议和期刊目录-2022.pdf](https://github.com/Future-Scholars/paperlib/files/15015228/-2022.pdf)

我提取好的数据在main.ts写死了，可以直接看到

https://github.com/AlphaGogoo/paperlib-ccf-rank-scrape-extension

数据源
