### ISSUE TITLE
[Feature Request] 侧边栏添加文件夹，显示未分组论文

### ISSUE THREAD

**Issue by AlphaGogoo** [Future-Scholars/paperlib#501]
使用过程中，拖动文件添加论文之后，没办法直接找到论文所在的条目，需要在所有论文中进行一个个查找

建议在侧边蓝增加一个系统自带的文件夹，显示未分组论文
建议在首页增加论文排序功能，根据论文名、添加时间排序之类的
建议添加论文后，自动滑动到论文所在的条目，并显示一定的高亮

**Comment by GeoffreyChen777** [comment]
1. 已经支持。详见 https://github.com/Future-Scholars/paperlib/issues/262
2. 已经支持，
<img width="315" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/5a174d42-80b6-445f-86d6-9e19d2622909">
3. 实现层面不好做，暂时应该不会做。
