### ISSUE TITLE
[BUG] smart filter error

### ISSUE THREAD

**Issue by AlphaGogoo** [Future-Scholars/paperlib#503]
I created a filter：
<img width="694" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/69681789/56d3027d-74eb-4766-8bbe-2c42e0c1f44a">
But it doesn't work.
<img width="277" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/69681789/e63c93e7-7bd3-49ee-a67a-2641a5abdde4">

**Comment by GeoffreyChen777** [comment]
This is a bug.

**Comment by GeoffreyChen777** [comment]
fixed in #508

**Comment by AlphaGogoo** [comment]
Doesn't seem to be working.
<img width="267" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/69681789/a2f95c53-f335-4d48-ae92-1898cf64fb7f">
<img width="506" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/69681789/c89abe1e-aff5-450d-a1ab-1a0bb92e92fe">

**Comment by GeoffreyChen777** [comment]
Because the new version has not been released yet 🤣. I just told you this has been fixed in that PR.

Please wait for the next release.

**Comment by AlphaGogoo** [comment]
Hahahahaha, Looking forward to the next version.
