### ISSUE TITLE
[Question] How can i import the CSV file exported from Paperlib into another device?

### ISSUE THREAD

**Issue by Dookoen** [Future-Scholars/paperlib#505]

**Comment by GeoffreyChen777** [comment]
Hi are you trying to sync between different devices?

**Comment by Dookoen** [comment]
Hello! Actually i use MongoDB to sync. But i lost all paper tags and notes before i update it to MongoDB. I just have a CSV file with all paper tags and notes exported from Paperlib. I tried to use Button [import from Zotero], but it does not work. Is there any simple way to restore my paper tags/notes with this CSV file? Thanks.

**Comment by GeoffreyChen777** [comment]
Ok. I need to update the entry scrape extension for this. I will tell you once it’s ready.

**Comment by GeoffreyChen777** [comment]
Hi, 

**If you are sure that the `.csv` has all your data, then please follow these steps**:

### Data backup

1. backup your `.csv`. with this `.csv` you will never lose your data.
2. backup your library folder, i.e., the one you use for storing all your PDFs.

### Delete previous data

1. Change the library folder to a new empty folder. Your current library folder should be the one with many PDFs. Please choose a new empty folder.
2. Delete all papers, tags, folders, etc. to clear data in the online database. NOTE: you should first login to Mongodb before doing this.
3. Logout Mongodb.
4. Change the library folder to the previous one (the one with your PDFs).
5. Close Paperlib.
6. Remove all database-related files and folders in the library folder. (something like `.realm`)
7. Open Paperlib, you will see an empty UI.
8. Make sure the `paperlib-entry-scrape-extension` is at `v0.0.27`
9. Uninstall the `paperlib-metadata-scrape-extension` temporarily if you don't want to wait for the metadata rescraping.
10. Drag your `.csv` into Paperlib.
11. Now you should see all your data in Paperlib.


### Sync to Mongodb

1. Now login to Mongodb.
2. Click `migrate` to migrate local to cloud.

Feel free to tell me if you have any problem with this.

Remember, **BACKUP YOUR CSV AND PDFs**

**Comment by Dookoen** [comment]
Thanks a million! I've restored the metadata for my papers.
