### ISSUE TITLE
[Feature Request] Notify when adding an existing paper.

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib#510]

**Comment by ultranity** [comment]
Even better if the browser extension could show hint if an existing paper.

**Comment by GeoffreyChen777** [comment]
@ultranity Hi, I’m waiting for the refactoring of the chrome extension by @ischaojie 

After that I can implement this feature.

However, it’s still in progress. All of us are using our spare time to maintain this project which means when we are busy, we need to postpone the development. We will finish it ASAP.

**Comment by GeoffreyChen777** [comment]
implemented.
