### ISSUE TITLE
[Feature Request] Tags Folder

### ISSUE THREAD

**Issue by Dookoen** [Future-Scholars/paperlib#511]
**Describe your feature request**
There are so many tags in my Paperlib and they are unsorted. Is it simple to add some folders for tags? For example, tags indicating different conferences may lie in one folder, and tags indicating different research areas may lie in another folder.

**Comment by ZephyrZhang3** [comment]
If do this, wouldn't `Tags` be the same as `Folder`?

**Comment by Dookoen** [comment]
But how can I manage those tags? They are unsorted and completely messy. I subscribed several research areas and there are almost one hundred tags.

**Comment by GeoffreyChen777** [comment]
Hi.

A hierarchical tag system will never be implemented in Paperlib.

This has been discussed a lot, see #354.

Tags must be **atomic**, which means that sub-tag is invalid.

If a tag is not atomic, then it is a folder.

So, as mentioned by @ZephyrZhang3 , you can use folders rather than tags to manage your papers if you really want this feature.

Or, you can use the nested smartfilter like this:

<img width="320" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/26f49163-9f88-4012-ba9a-87f0a7a0d1a8">

**Comment by Dookoen** [comment]
Hello! What i mean is not a sub-tag. 
```
tag folder
|---tag1
|---tag2
```
`tag folder` is not a tag. It just collects tags and will never be used to index or search. In database, it can be implemented by add a table with `folder name` as key and a list of tags as value (Realm supports list). So the tag is still **atomic**. Like what i mentioned above,  `tag folder` only makes tags sorted or structured, and is never used to manage papers.

**Comment by GeoffreyChen777** [comment]
However, if we display it in the tags list:

```
Tags
| -- tag folder
      | -- tag1
      | -- tag2
```

It's really a tag. For other users, it's so confusing.

I would suggest you try the nested smartfilter. It can achieve this.

**Comment by Dookoen** [comment]
Okay, maybe I'll have to leave my hundred tags disorganized for a while.

**Comment by GeoffreyChen777** [comment]
I believe this can be solved if we optimise the smartfilter creation. For example, drag and drop a tag to a smartfilter will create a sub-smartfilter with a query sentence for the tag.

**Comment by Dookoen** [comment]
It's a good idea, but users must first locate the tag they want among hundreds of unsorted tags.

**Comment by GeoffreyChen777** [comment]
But if you have already had 100+ tags. With the tags folder feature you still need to locate these tags when you create your tag folder for the first time.

**Comment by Dookoen** [comment]
Once index were created it would be fast to locate a tag. Maybe i can contribute for this feature and add a switch to disable/enable it.
---- Replied Message ----
***@***.***>Date04/23/2024 18:26 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [Future-Scholars/paperlib] [Feature Request] Tags Folder (Issue #511)
But if you have already had 100+ tags. With the tags folder feature you still need to locate these tags when you create your tag folder for the first time.

**Comment by GeoffreyChen777** [comment]
I would say it's really not an easy feature.

It's related to the database, query sentence tree, UI, etc.

**Comment by Dookoen** [comment]
I will try. By the way, is it possible to integrate Git into Electron? I find Git might be the best way to make checkpoints instead of tar PDFs and Realm.
---- Replied Message ----
***@***.***>Date04/23/2024 18:43 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [Future-Scholars/paperlib] [Feature Request] Tags Folder (Issue #511)
I would say it's really not an easy feature.
It's related to the database, query sentence tree, UI, etc.

**Comment by ZephyrZhang3** [comment]
You can Capitalize the tag to the top, perhaps as a quick solution to finding a particular tag. Like conference name?

**Comment by GeoffreyChen777** [comment]
@Dookoen checkpoint for what?

**Comment by Dookoen** [comment]
May be difficult, since i have tags of university, organization,Inc and so on.
---- Replied Message ----
***@***.***>Date04/23/2024 18:57 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [Future-Scholars/paperlib] [Feature Request] Tags Folder (Issue #511)
You can Capitalize the tag to the top, perhaps as a quick solution to finding a particular tag. Like conference name?

**Comment by Dookoen** [comment]
The whole Paperlib data. Data may be lost on account for any misoperation, especially for a CSer.
---- Replied Message ----
***@***.***>Date04/23/2024 18:59 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [Future-Scholars/paperlib] [Feature Request] Tags Folder (Issue #511)
@Dookoen checkpoint for what?

**Comment by GeoffreyChen777** [comment]
> I will try. By the way, is it possible to integrate Git into Electron? I find Git might be the best way to make checkpoints instead of tar PDFs and Realm. ---- Replied Message ---- ***@***.***>Date04/23/2024 18:43 ***@***.***> ***@***.***>, ***@***.***>SubjectRe: [Future-Scholars/paperlib] [Feature Request] Tags Folder (Issue #511) I would say it's really not an easy feature. It's related to the database, query sentence tree, UI, etc. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

@Dookoen Before you implement this, I would suggest you describe your design here.

If the implement may confuse others or conflict with the design philosophy of Paperlib, I would probably not merge it. I don't want to waste your time.

**Comment by GeoffreyChen777** [comment]
> The whole Paperlib data. Data may be lost on account for any misoperation, especially for a CSer. ---- Replied Message ---- ***@***.***>Date04/23/2024 18:59 ***@***.***> ***@***.***>, ***@***.***>SubjectRe: [Future-Scholars/paperlib] [Feature Request] Tags Folder (Issue #511) @Dookoen checkpoint for what? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

@Dookoen I would say we won't implement this in the main Paperlib App. Many users don't know what is git.

You can implement this in an extension. Or you can setup the cloud sync https://paperlib.app/en/doc/cloud-sync/setup.html All data are stored on cloud.

NOTE: please don't use git to sync between different devices. Realm is a realtime sync database. It means that you make changes on PC A, the PC B will update immediately. And the database file has a filelock. I'm not sure git can handle it correctly.

**Comment by GeoffreyChen777** [comment]
作为插件比较好，我想了想现在提供的API应该足以完成这个。

什么叫做配置分类？

**Comment by Dookoen** [comment]
就是不推荐不熟悉不了解的人去更改或者设置，比如设置git同步之类的
---- Replied Message ----
***@***.***>Date04/23/2024 19:29 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [Future-Scholars/paperlib] [Feature Request] Tags Folder (Issue #511)
作为插件比较好，我想了想现在提供的API应该足以完成这个。
什么叫做配置分类？

**Comment by GeoffreyChen777** [comment]
这个感觉不需要，做成插件吧，需要的人自然会去安装

**Comment by ZephyrZhang3** [comment]
如果没理解错，是个备份需求。那用现在的API，做个定时备份的插件应该完全可以。好像只需要拿到PAPERLIB_HOME，然后直接打包压缩加个时间戳？

**Comment by Dookoen** [comment]
嗯啊，那我按插件去做
---- Replied Message ----
***@***.***>Date04/23/2024 19:33 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [Future-Scholars/paperlib] [Feature Request] Tags Folder (Issue #511)
这个感觉不需要，做成插件吧，需要的人自然会去安装

**Comment by Dookoen** [comment]
是的，这样就可以在玩崩了的时候用打包的pdf和本地数据库恢复了
---- Replied Message ----
***@***.***>Date04/23/2024 19:34 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [Future-Scholars/paperlib] [Feature Request] Tags Folder (Issue #511)
如果没理解错，是个备份需求。那用现在的API，做个定时备份的插件应该完全可以。好像只需要拿到PAPERLIB_HOME，然后直接打包压缩加个时间戳？
