### ISSUE TITLE
[Feature Request] Tags JOIN

### ISSUE THREAD

**Issue by Dookoen** [Future-Scholars/paperlib#512]
**Describe your feature request**
Is it simple to implement a tags JOIN operation? For instance, when I keep pressing a certain key (such as 'command'), I click on 'tag1' and 'tag2' (and possibly more), then Paperlib shows all papers that contain both 'tag1' and 'tag2'. I think this way is more convenient compared to using smart filters. There may be multiple combinations for these JOINs, and managing a massive amount of smart filters may be difficult.

**Comment by GeoffreyChen777** [comment]
have you tried the advanced searching?

`ALL {'tag1', 'tag2'} IN tags.name`

**Comment by Dookoen** [comment]
Hello! Yes, I have tried it before this issue. Paperlib is a paper manager with a nice modern UI. Users might not want to use it in a CLI manner for some simple functions, especially those who are not CS majors.

**Comment by GeoffreyChen777** [comment]
OK, it's doable. I think it's not very hard.

However, recently I've been a little busy with my own research. If you could contribute to this feature, I can give you some suggestions about this.

**Comment by Dookoen** [comment]
Yes, i think it is not complicated and i can contribute to this. I just need some time to clarify the code architecture.

**Comment by GeoffreyChen777** [comment]
I would suggest you starting from here:

https://github.com/Future-Scholars/paperlib/blob/b52540248ad3df50e7cbeb686604d6f005900d41/app/renderer/ui/sidebar-view/sidebar-library-view.vue#L69-L69

That’s what will happen when a user clicks a tag/folder.

**Comment by GeoffreyChen777** [comment]
Hi @Dookoen , are you still working on this? Do you need any help?

**Comment by GeoffreyChen777** [comment]
implemented.
