### ISSUE TITLE
[Feature Request] hope the thesis title supports simple latex formulas.

### ISSUE THREAD

**Issue by yym68686** [Future-Scholars/paperlib#514]
As shown in the figure, the title of the list of papers displays the original LaTeX strings. However, the paper information bar on the right can correctly display LaTeX superscripts.
<img width="854" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/31803242/060d5139-cc56-4585-99f4-087d6a86783c">

**Comment by GeoffreyChen777** [comment]
see #359 

it supports html. You can change this title to <sup>2</sup>

**Comment by yym68686** [comment]
Thank you for your reply. Since LaTeX has performance issues, can we automatically replace the formatting such as superscripts and subscripts in the title with HTML format?

**Comment by GeoffreyChen777** [comment]
It can be easily achieved via an extension.

See https://github.com/Future-Scholars/paperlib-format-pubname-extension for some hints.

**Comment by yym68686** [comment]
I attempted to use the configuration `{"$^{": "<sup>", "}$": "</sup>"}` in the plugin paperlib-format-pubname-extension, but it doesn't work and did not replace with superscripts as shown in the image:

<img width="858" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/31803242/ffb2421e-946e-46e2-8b72-b224c5697470">

<img width="406" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/31803242/16f83028-c85a-496b-acac-e556806b72a8">

**Comment by yym68686** [comment]
I attempted to use the configuration `{"$^{": "<sup>", "}$": "</sup>"}` in the plugin paperlib-format-pubname-extension, but it doesn't work and did not replace with superscripts as shown in the image:

<img width="858" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/31803242/62e6072a-d72d-426a-9482-77f898213ad9">
<img width="406" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/31803242/efb2954a-dae5-4eef-9d68-039a2e60bd1b">

**Comment by GeoffreyChen777** [comment]
I mean you need to develop a new small extension. You can find some inspiration in the link I provided.

**Comment by yym68686** [comment]
Okay, I understand. But I still hope that in the future, the original format of the paper title can be supported by default. Because I think it is a bit unsightly to only display the original LaTeX string at present.

**Comment by GeoffreyChen777** [comment]
I need to find a solution to solve the rendering bottleneck.

**Comment by yym68686** [comment]
Looking forward to the rendering issue being resolved. This software is excellent!

**Comment by GeoffreyChen777** [comment]
implemented.
