### ISSUE TITLE
Introduction pdf file failure

### ISSUE THREAD

**Issue by zhongguozhiwang** [Future-Scholars/paperlib#516]
Thanks to the author for developing such a great tool, I recently found that when using Version 3.0.10, I could not properly import pdf files. When dragging in pdf files, it showed:

ScrapeService
Official scrape extension is not installed yet.
ScrapeService
Official scrape extension is not installed yet.

How should this be solved, please? Thank you.

<img width="246" alt="11" src="https://github.com/Future-Scholars/paperlib/assets/124131673/ec66257c-aebf-4ec3-a243-eb069c3aa3bb">

**Comment by GeoffreyChen777** [comment]
Please install the scrape extension. Go to the preference window.

**Comment by zhongguozhiwang** [comment]
> Please install the scrape extension. Go to the preference window.
It has been solved, thank you for your timely reply!
