### ISSUE TITLE
[BUG] Importing papers from folder failed, and the software got stuck when restarting.

### ISSUE THREAD

**Issue by leeechsh** [Future-Scholars/paperlib#519]
**Describe the bug**
1.Importing Papers from a Folder Failed:
![PixPin_2024-05-06_21-06-32](https://github.com/Future-Scholars/paperlib/assets/11641945/fa7bab4e-fb5d-47d0-8a52-d4c426eb0fb0)
2.Software Stuck When Restarting:
![image](https://github.com/Future-Scholars/paperlib/assets/11641945/6ecc5e1b-ca36-4077-9b90-d98de16fa5a6)

**System (please complete the following information):**
 - OS: Windows11 23H2
 - Paperlib Version 3.0.10

**Comment by GeoffreyChen777** [comment]
Hi please try to open the dev tools by pressing ctrl shift I or F12 and share the screenshot of the console tab.

**Comment by leeechsh** [comment]
> Hi please try to open the dev tools by pressing ctrl shift I or F12 and share the screenshot of the console tab.

![image](https://github.com/Future-Scholars/paperlib/assets/11641945/1adfbf5d-bcb2-4eee-aca9-d70d2df0204c)

**Comment by GeoffreyChen777** [comment]
似乎没报错一切正常。很奇怪。

如果你正在刚开始用paperlib，那把现有的数据库删了重来好了。

本质上你之前遇到的报错并不会影响什么，他不是报错卡死，而是在等待metadata的搜寻结果，出错的文章会跳过不影响别的。

删除数据库只需要前往你选择的 app library 路径，里面所有名字和 realm 相关的文件文件夹都删了，然后再打开paperlib就好了。

鉴于你的论文很多很多，我建议你分批次导入，比如一次500篇这样，metadata API 有每分钟请求次数限制，你论文过多一次性请求偶尔可能触发限制。所以建议分批次。

**Comment by GeoffreyChen777** [comment]
删除数据库重新添加应该会解决你卡loading的问题。

全部一次性导入卡住理论上不会出现但是也许有什么隐藏bug我没有测到。我之前测试过一次性2000pdf没啥问题。我猜测有可能是你导入的文件里面有什么特殊的文件会触发？

分批次导入可以帮你和我定位到是为什么。

**Comment by leeechsh** [comment]
我还发现一个比较有意思的问题，我之前删数据库是直接清空 “AppData\Roaming\paperlib” 文件夹，重置软件没问题。
但是我刚刚按您说的删除 “和realm 相关的文件文件夹” （同时清空app library 路径）还是会卡loading

**Comment by GeoffreyChen777** [comment]
如果设置了同步，你在 AppData 里也会找到一些 realm 相关的文件和文件夹。需要清空那些，但是你可以保存config以及extension等文件。

此时 app lib 里的 realm 相关文件是废的。

**Comment by leeechsh** [comment]
我刚刚就是把 AppData 里realm 相关的文件和文件夹都删了，还是卡loading ，只有把整个文件夹清空重置软件才行

**Comment by GeoffreyChen777** [comment]
我觉得是因为你设置了同步数据库，当你不清空config的时候，你删了同步数据库的本地缓存，还是会去登录同步数据库。显然是同步数据库的问题把你卡住的。

你的同步数据库设置成功了嘛？你有用一两个文件测试看看，以及在 mongodb 网站的 log 里看到成功的写入了吗？

**Comment by leeechsh** [comment]
似乎是同步数据库的问题导致的卡loading，我最开始就是先设置同步数据库再import文件，就直接卡loading
我刚刚重置后先import文件就没问题，但是我接着设置同步数据库就再次卡住了。
mongodb log报错
![image](https://github.com/Future-Scholars/paperlib/assets/11641945/09cdafb1-c8f2-4f2b-824c-035fbaa11b50)

**Comment by GeoffreyChen777** [comment]
你没有打开 development mode 导致数据库里面的格式无法自动创建。

参见 https://paperlib.app/cn/doc/cloud-sync/setup.html#%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE%E5%BA%93%E8%A1%A8

**Comment by GeoffreyChen777** [comment]
理论上是，但是云数据库返回的错误信息很有限，而且对于用户来说并没有什么价值。到最后还是得提issue解决。

主要的问题都是记录在mongodb的log里，因此最好严格按照步骤一步步设置。有一定门槛，但是这就是白嫖云数据库的代价吧🤣

**Comment by leeechsh** [comment]
哈哈哈 白嫖是这样的，非常感谢热心解答，祝Paperlib越来越好^(*￣(oo)￣)^
