### ISSUE TITLE
[Feature Request] Highlight search results

### ISSUE THREAD

**Issue by thequilo** [Future-Scholars/paperlib#525]
**Describe your feature request**

It would be nice to highlight the words that match the query in the search results. For me, it makes it much easier to find the item I am looking for when I see the matched words highlighted.

**Comment by thequilo** [comment]
I can imagine that. How about doing this just for the simple search and add a second pass, after matching, with something along the lines of `result.replace(query_word, "<span class=highlight>" + query_word +"</span>")`?

**Comment by GeoffreyChen777** [comment]
Thanks for your suggestion, will consider that

**Comment by igoogolx** [comment]
We can use https://github.com/kawamataryo/vue-word-highlighter with less code.

**Comment by GeoffreyChen777** [comment]
@igoogolx that looks pretty good!

Currently, we can get the searing string:
https://github.com/Future-Scholars/paperlib/blob/da0f48e65dd3e4144bb6aaa71c2f07726c3b96f0/app/renderer/services/uistate-service.ts#L45
with `vue-word-highlighter`, it would be easy to implement.

However, we still need to test the rendering performance to make sure it will not slow down the UI if we have numerous papers.

**Comment by GeoffreyChen777** [comment]
Seems the performance is ok. #528

This will be available with the next version.

<img width="1308" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/73ba043e-0199-4bb0-80d3-f831d5e5e607">

**Comment by thequilo** [comment]
Thanks a lot!
