### ISSUE TITLE
[Question] Any way import only metadata without downloading the PDF files?

### ISSUE THREAD

**Issue by cpfy** [Future-Scholars/paperlib#527]
First of all, thanks for this great work! However, there are still some features I'd like to suggest.

I hope to implement such a feature in Paperlib: Similar to the star feature on GitHub, to mark a paper and add it to the Paperlib list for collection. 

Since some paper PDF files are large and downloading them is very slow, and my requirement is not to save the files locally, but just to add a metadata entry. It's like synchronizing the paper list on other devices, without downloading the source files for each paper. It should be lightweight and convenient, and I can download them anytime I need.

I wonder if there's a way to implement this in the web extension.

**Comment by GeoffreyChen777** [comment]
https://github.com/Future-Scholars/paperlib-chrome-extension/issues/1

Hi, WIP.

**Comment by GeoffreyChen777** [comment]
Is a private project sorry. Just wait for the next version of the extension.

**Comment by GeoffreyChen777** [comment]
The new browser extension is ready. I will release it with the next version of Paperlib.

<img width="404" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/fd163132-7512-4bea-bcac-827363d133a4">

**Comment by cpfy** [comment]
Up to Chrome extension version 1.0.1, this feature is available! Absolutely fantastic!

btw, I can only use it after upgrading Paperlib to version 3.1.1. It might not be fully compatible if the Paperlib client version is lower.

**Comment by GeoffreyChen777** [comment]
Hi, It requires some new functions in the latest update. We always recommend users use the latest version.
