### ISSUE TITLE
[BUG] Investigate RSS 403

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib#531]
https://rss.sciencedirect.com/publication/science/01668641

**Comment by GeoffreyChen777** [comment]
<img width="265" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/b4d15a83-c4a2-46e6-b014-efb7620e0e09">

**Comment by charlieJ107** [comment]
> @charlieJ107 Hello 最近忙么，有时间帮忙修一下这个么。

OK, I'll take it 😉
