### ISSUE TITLE
[Feature Request] Automatically move the items to a classified folder when drag a pdf into a child folder.

### ISSUE THREAD

**Issue by SakuraToErii** [Future-Scholars/paperlib#533]
**Describe your feature request**
...
Suppose that I have created three folders like RL, LLM, DL. 
If I open the “RL” folder, I drag a pdf file from local into the window "RL", it will not appear in this folder, but in "All Papers", I need to manually drag the item from "All Papers" into "RL". 

如果此时我打开的是RL文件夹，我把一个pdf文件从我本地拖入窗口“RL”，它不会出现在这个文件夹中，而是出现在“All Papers”里，需要我再手动从“All Papers”将item拖入“RL”中。

**Comment by GeoffreyChen777** [comment]
请直接把pdf拖入左侧侧边栏对应标签或组。

**Comment by SakuraToErii** [comment]
啊这样，谢谢
