### ISSUE TITLE
[Feature Request] 关于使用的一些新功能需求建议

### ISSUE THREAD

**Issue by RongxuanLai** [Future-Scholars/paperlib#535]
1. 希望新增附件详情内容。单击文献后，右侧栏有详情展示，但是关于附件一栏，仅有文件后缀名的图标显示。建议可以展示附件详，如文件名、文件类型等。
    - 需求场景1：某arxiv文章可能存在多个版本，可以按需直观的选择打开哪个版本的文件
    - 需求场景2：某开源论文，源代码可以以附件（zip/rar）形式上传
2. 建议借鉴zotero的一个小功能，选择某个文献后，按住ctrl键，可以在左侧栏分组中高亮显示该文献被分在了哪些组里（现在是以右侧栏的分组中以字符串形式展示，当存在多个分组时，很不直观）

最后感谢作者的开源。

**Comment by GeoffreyChen777** [comment]
arxiv链接和源代码不是展示在在线资源那一栏嘛，你是说在线资源还是附件哇？

**Comment by RongxuanLai** [comment]
说的是附件。arxiv是在线链接，但是在读论文的时候通常会把文章下载下来，甚至会下载多个版本，又或者有一些论文有中文版，又或者有一些pdf版的阅读笔记，总之就是可能存在多个相同后缀（如PDF）的附件。这种情况下，在右侧栏中无法区分不同附件，只能区分主文件和一般附件。所以建议可以把附件信息展示出来，方便精准直接地双击打开。

具体一点，可以借鉴一下zotero的管理方式，如下图：
![2024-05-21_160254](https://github.com/Future-Scholars/paperlib/assets/146648859/fecb966f-89d4-49f8-8910-b352d3add231)

不当之处敬请包涵，谢谢作者。

**Comment by GeoffreyChen777** [comment]
Zotero 的方式应该是不会采用的，很乱。

关于附件详情，见#177。历史遗留问题，还没有一个比较好的方案。

**Comment by RongxuanLai** [comment]
感谢回复，zotero的方式确实也有一点不合适，截图仅为更好说明我的意思。多谢作者，期待新版paperlib。

**Comment by GeoffreyChen777** [comment]
那我暂时先关闭这个了哈，你可以去#177追踪，一旦找到好的解决办法，就会解决。

**Comment by GeoffreyChen777** [comment]
找到了一个好方法，自定义附件名称已经实现了。
