### ISSUE TITLE
[Feature Request] Import files without duplicating and renaming

### ISSUE THREAD

**Issue by hany606** [Future-Scholars/paperlib#536]
I was trying to import my files from the file system, but the files got duplicated and renamed. That missing up many things. It would be great if importing existing files links between old files names and locations without the need for duplication.

Or maybe having an option to duplicate and rename or not.

Thank you for the great work here!

**Comment by GeoffreyChen777** [comment]
In the preference, see the source file operation, use ‘link’ rather than’copy’.

**Comment by hany606** [comment]
Oh did not see that, I will close the issue then.

Thank you!
