### ISSUE TITLE
[Feature Request] Add website link like BLOG into the attachments.

### ISSUE THREAD

**Issue by SakuraToErii** [Future-Scholars/paperlib#542]
有的时候论文懒得做笔记，网上有现成的blog，如果可以加到附件里就好

**Comment by GeoffreyChen777** [comment]
不需要新 feature，试试这样

<img width="566" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/fd7decc5-3ab0-49f0-b762-fb7ebeb96968">

**Comment by SakuraToErii** [comment]
感谢，这样似乎也很好

**Comment by SakuraToErii** [comment]
请问一下，笔记里添加<md>是把它变成markdown格式，但是我在哪里能看到md格式的笔记内容呢，我试了“列表视图”和“表格视图”，似乎都只能看到md源码

**Comment by GeoffreyChen777** [comment]
详情页面，你点这个论文，在右侧。

**Comment by SakuraToErii** [comment]
原来如此，好优雅，谢谢大佬
另外就是，可以让这个地方不显示源码吗？因为我在用”笔记“这个功能给论文起别名

<img width="716" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/53287824/1a516235-5c4f-44ec-8941-6976c0e40bb3">

**Comment by GeoffreyChen777** [comment]
目前没法不显示源码。

你想 markdown 是需要渲染的，而且通常是多行的，如果是多行的，如何渲染到一行里显示呢。所以这里显示的是源码。现在能做到的就是下个版本稍微改一下，去掉前面的 <md> 显示。

关于你想要起别名，建议关注这个功能，#530

目前只能先凑合。

**Comment by SakuraToErii** [comment]
感谢大佬！
