### ISSUE TITLE
[Feature Request] Fetch Pdf from Arxiv when Reading, No Local Storage or Webdav Needed

### ISSUE THREAD

**Issue by ChangeFWorld** [Future-Scholars/paperlib#546]
Thanks for your great and nice project.

Can we add a selection for remote storage only? i.e. fetch pdf files from Arxiv like source website when reading. It is likely that Arxiv is the Webdav source so there is no need for users own Webdav. It is also great that the received files are cached locally and the old cache can be replaced with new files.

**Comment by GeoffreyChen777** [comment]
Hi, 

do you only read papers on ArXiv? I think ArXiv is just one of the paper sources. What about other papers?

**Comment by ChangeFWorld** [comment]
> Hi,
> 
> do you only read papers on ArXiv? I think ArXiv is just one of the paper sources. What about other papers?

Yeah, that is a problem. And it's also bad if you want to change something in the pdf file. But I think it is a great way to reduce local storage space if the file is publicly available on the internet, and it will also benefit multi-device users for easy sync. Maybe adding additional fields `source_url` and `local_changable` for each paper will help. If the users want to reduce local storage or webdav usage, they can enable an option to free these spaces. If the internet source is not available, just keep it locally or on users own webdav.

Anyway, thanks for you attention!

**Comment by GeoffreyChen777** [comment]
I believe most users want to store the file locally.

1. If we implement such a feature, it will significantly increase the complexity of the storage logic.
2. If you use cloud services, such as OneDrive, Dropbox, etc, to sync files, most of them support features like `free up space` to save disk usage.
3. If you use WebDAV, the app lib folder is for caching. On the new device, when you connect the WebDAV, Paperlib will check if the PDF is on WebDAV or not. If yes, you will see a download button in the details panel. Paperlib will not download the PDF unless you click that button.
4. If you don't want to download PDF when you import a paper. There is an option in the browser extension. Just disable it. If you want to download it in future, just click the `locate` button.
<img width="359" alt="Screenshot 2024-05-27 at 16 32 10" src="https://github.com/Future-Scholars/paperlib/assets/14183213/68c39d7f-7cae-4ff6-ad5e-f8f112bedb1a">

<img width="430" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/80e11125-3812-40e2-81ab-a79fbd9e145f">

**Comment by ChangeFWorld** [comment]
> I believe most users want to store files locally.
> 
> 1. If we implement such a feature, it will significantly increase the complexity of the storage logic.
> 2. If you use cloud services, such as OneDrive, Dropbox, etc, to sync files, most of them support features like `free up space` to save disk usage.
> 3. If you use WebDAV, the app lib folder is for caching. On the new device, when you connect the WebDAV, Paperlib will check if the PDF is on WebDAV or not. If yes, you will see a download button in the details panel. Paperlib will not download the PDF unless you click that button.
> 4. If you don't want to download PDF when you import a paper. There is an option in the browser extension. Just disable it. If you want to download it in future, just click the `locate` button.
> 
> <img alt="Screenshot 2024-05-27 at 16 32 10" width="359" src="https://private-user-images.githubusercontent.com/14183213/334153287-68c39d7f-7cae-4ff6-ad5e-f8f112bedb1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjQzNzQsIm5iZiI6MTcxNjgyNDA3NCwicGF0aCI6Ii8xNDE4MzIxMy8zMzQxNTMyODctNjhjMzlkN2YtN2NhZS00ZmY2LWFkNWUtZjhmMTEyYmVkYjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE1MzQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ODRmODYwNWU4ZDZjOWUzMjkzZDhhMWE5NDBlY2EwNWM4NDMwZjAyZWY0ZDU1MWE4ODc0NDhlNTU2YWM2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fFRPphnYxdlO4M-hC40NC5aeUCOS-5Y9P0ncX3ui6eo"> <img alt="image" width="430" src="https://private-user-images.githubusercontent.com/14183213/334153548-80e11125-3812-40e2-81ab-a79fbd9e145f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjQzNzQsIm5iZiI6MTcxNjgyNDA3NCwicGF0aCI6Ii8xNDE4MzIxMy8zMzQxNTM1NDgtODBlMTExMjUtMzgxMi00MGUyLTgxYWItYTc5ZmJkOWUxNDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE1MzQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NzIwMGQyYzk5YWZlOTdiMTVhZTA5ZDQ1NzhkMzAxZjM1MTQ1NzM2ZWViMzMyZTNiOTY1OTQ1Y2JiOTA3NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.02Ki0Ms1ShVgjsZq32LcL6pw1zKkqTEEbsCF5_x0ZXw">

I see. Agree with you. These suggestions solve this problem to some extent. Only the case that the user wants to save both onedrive and local spaces when they discover they have downloaded too many papers will suffer. 

Thanks for your kind work and reply.

**Comment by GeoffreyChen777** [comment]
I will close this for now, if you have any further questions, welcome to reopen.
