### ISSUE TITLE
[Feature Request] Importer plug-ins

### ISSUE THREAD

**Issue by Wells-XW** [Future-Scholars/paperlib#547]
Very clean software! Already downloaded and followed the tutorial to set up the database.
I have a longer history of using Zotero, will Paperlib follow with import (and attachment) capabilities?
Thanks for bringing a better alternative to Zotero.

**Comment by GeoffreyChen777** [comment]
Hi,

are you going to import your data from Zotero into Paperlib?

**Comment by GeoffreyChen777** [comment]
<img width="1220" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/fcffdd6a-f9ea-4631-a739-e99987402ba6">

It has been introduced in the Getting Started.

**Comment by GeoffreyChen777** [comment]
The Zotero exported CSV doesn't contain any information about the Collection/Folder information.

If you wish to restore the folder structure of your library, I have few suggestions:

Suppose you have some collections:

```
| -- Project A
    | -- Sub A
| -- Project B
```

1. Create the same folder structure in Paperlib manually.
2. Export zotero csv for each collection as an individual `.csv`, for example, `Project A.csv`, `Sub A.csv`
3. Drag the corresponding `.csv` into the folder in the left sidebar like this:
<img width="597" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/4ab1228b-1bc2-4651-81af-3fa84b7e0daa">

4. repeat for each `.csv`.

**Comment by Wells-XW** [comment]
> The Zotero exported CSV doesn't contain any information about the Collection/Folder information.
> 
> If you wish to restore the folder structure of your library, I have few suggestions:
> 
> Suppose you have some collections:
> 
> ```
> | -- Project A
>     | -- Sub A
> | -- Project B
> ```
> 
> 1. Create the same folder structure in Paperlib manually.
> 2. Export zotero csv for each collection as an individual `.csv`, for example, `Project A.csv`, `Sub A.csv`
> 3. Drag the corresponding `.csv` into the folder in the left sidebar like this:
> 
> <img alt="image" width="597" src="https://private-user-images.githubusercontent.com/14183213/334471547-4ab1228b-1bc2-4651-81af-3fa84b7e0daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDk1MjMsIm5iZiI6MTcxNjkwOTIyMywicGF0aCI6Ii8xNDE4MzIxMy8zMzQ0NzE1NDctNGFiMTIyOGItMWJjMi00NjUxLTgxYWYtM2ZhODRiN2UwZGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE1MTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmOGYzM2Y4NTM1NTAxNDJjYjQ1MmY2NTM3ZjY4ZTQ3MDIzNTdjYjI3OGUxNDBhNDIxZTVlZWE0MTRjZmI1ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EF_Oay2shjYjIHPH2y88s6TI-sF6nkN3ta-_oxpzBrw">
> 4. repeat for each `.csv`.

Thank you very much for the offer, this should work and I will rebuild the folder structure in Paperlib. Can't wait to start using Paperlib!

**Comment by GeoffreyChen777** [comment]
I'm going to close this for now, feel free to reopen it if you have any further questions.

**Comment by Wells-XW** [comment]
OK, your answer was really helpful, thanks again!
---- Replied Message ----
***@***.***>Date5/28/2024 ***@***.***>CcXu ***@***.***>,
***@***.***>SubjectRe: [Future-Scholars/paperlib] [Feature Request] Importer plug-ins (Issue #547)
I'm going to close this for now, feel free to reopen it if you have any further questions.
