### ISSUE TITLE
[Feature Request] Too little metadata included

### ISSUE THREAD

**Issue by y1-fan** [Future-Scholars/paperlib#548]
我猜想现在的元数据编辑器对于 CS 可能是够用了，但是如果 paperlib 是为了所有学科准备的，那似乎还不太够。

paperlib 包含的元数据有点太少了。首先是 type of reference 选项太少，那个 Others 选项里面混杂了图书章节、预印本、数据集等，造成了一定程度的混乱，如果是艺术类学科的可能还需要电影、音频、展览等，那就更难管理了。

然后，比方说书籍，有没法填写 ISBN 以及作者、编辑、译者无法区分等问题。由于没法编辑索书号、存档位置等元数据，历史类学科需要的古籍也很难在 paperlib 里面管理。至于具体需要什么元数据，就是希望 Zotero 导出的 CSV 里的元数据最好是能原样保留。另外就是，日常经常会用到 RIS 格式，也希望 paperlib 能支持导入 RIS。

感谢你们的付出！

**Comment by GeoffreyChen777** [comment]
关于 type of reference，有计划去更多扩展一点。

paperlib 如名，论文库。因此在设计之初就是围绕论文来的。并且很多设计理念是绑定 latex 来的。即写作论文时候需要用到的元数据有什么，就存什么。因此在目前强面向理工科。

对于文科的支持，确实很少。也许这是之后会做的。目前首先要做到满足好理工科，才能扩展。

感谢建议。

**Comment by GeoffreyChen777** [comment]
另外，Paperlib 现在正在准备支持自定义字段。因此你所要求的东西，完全可以在 #530 实现之后，自定义实现。
