### ISSUE TITLE
[Feature Request] 组的嵌套和取出

### ISSUE THREAD

**Issue by mobulan** [Future-Scholars/paperlib#549]
**Describe your feature request**
一旦一个组嵌套到另一个组内，就没办法将其取出来了，希望通过调整ui的交互来解决这个问题
...

**Comment by GeoffreyChen777** [comment]
目前，可以从一个组拖到另外一个组里面，但是无法拖到顶级组。

临时解决办法是，创建一个同名的顶级空组，去你想拖动的组里，全选所有论文，拖入顶级空组，然后删掉原来的那个组。

后续会解决这个问题。

**Comment by GeoffreyChen777** [comment]
已经实现 #549

等待下个版本。
