### ISSUE TITLE
[.bib importer] 

### ISSUE THREAD

**Issue by Nosenzor** [Future-Scholars/paperlib#550]
I'd like a .bib aka BibTex importer. I know there's an exporter.

**Comment by GeoffreyChen777** [comment]
https://paperlib.app/en/doc/getting-started.html#import-new-papers

> The .bib file and the .csv file exported from Zotero are also supported.

**Comment by Nosenzor** [comment]
Haha sorry, i was looking in the menus ... but that's great, grab and drop is enough. I love paperlib !

**Comment by Nosenzor** [comment]
The importation is done through dropping bib files into windows
