### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by L4Walk** [Future-Scholars/paperlib#558]
**Describe the bug**

Failed to create a View Tree from a querySentence graph.
RealmError RealmError: Access to invalidated Results objects at Reflect.get (<anonymous>) at...

**Screenshots or Log**
![image](https://github.com/Future-Scholars/paperlib/assets/67847083/e705a4c9-a3d4-4048-a067-11587f26d7f6)

**System (please complete the following information):**
 - OS: win11
 - Paperlib Version: Version 3.1.3

**Comment by GeoffreyChen777** [comment]
Could you please describe the operation you did before you met this bug?

**Comment by GeoffreyChen777** [comment]
To solve it easily, you can add my wechat if you are happy with it.

https://share.1password.com/s#vsgt3v0oSmsxpAngOYoxvdVmKGEoQ_lpjFP4G7VSPps

**Comment by GeoffreyChen777** [comment]
Have you solved this bug?

**Comment by GeoffreyChen777** [comment]
I'm going to close this as inactive. Feel free to reopen.
