### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Lixiao-bai** [Future-Scholars/paperlib#559]
**Describe the bug**

**To Reproduce**
1. Go to Microsoft Word
2. Click on Paperlib add-in
3. Chose on paper and click "Add citation"
4. See "单击或点击此处输入文字"

![image](https://github.com/Future-Scholars/paperlib/assets/63952761/77694930-c285-4f52-b475-96da92231a04)

**System (please complete the following information):**
 - OS: Windows 11 pro 23H2
 - Paperlib Version 3.13

**Comment by GeoffreyChen777** [comment]
cannot reproduce.

<img width="750" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/20eb916e-cc32-4556-9962-c7a227aaeb3f">

could you please delete this field and try again?

**Comment by Lixiao-bai** [comment]
I tried almost everything, it still work untill afternoon, I tried remove paperlib and re-install it manytimes, but it's still not work,

**Comment by GeoffreyChen777** [comment]
我认为你应该是中文使用者，所以我用中文跟你沟通，避免误解。

重新安装 paperlib 永远不会解决这个问题，因为这个是word插件的问题。

首先：

1. 备份你这个文档。防止你的文件丢失。
2. 你的文档里一定有坏掉的content field. 引用是放在word的content field 里的。并且每一个都有分配id等信息。我猜你应该是有不小心删除了一些东西，但是没删除完全，导致出现了坏掉了的content field。

定位到底是哪里的问题：
1. 首先新建一个word，复制你这个文档所有内容进去，然后试试好了没。
2. 如果不好，你可以使用二分法来找，删除一半的文档，试试好了没，如果好了，那就是在删除的那一段里面有问题，然后再删除那一段里面的一半，循环，你很快会定位到是哪里的问题。

**Comment by GeoffreyChen777** [comment]
或者你加我微信 

https://share.1password.com/s#vsgt3v0oSmsxpAngOYoxvdVmKGEoQ_lpjFP4G7VSPps

**Comment by Lixiao-bai** [comment]
用二分法解决了，谢谢老哥！
