### ISSUE TITLE
[Feature Request] Import paper shortcut 

### ISSUE THREAD

**Issue by Davids048** [Future-Scholars/paperlib#563]
Currently, the only way to import a new paper is by dragging and dropping the paper into the main view, or through the browser extension. Is it possible to add a feature where a user can import a PDF file directly inside the Paperlib application? 

For example, when a user wants to import a new paper, they can type command + o to open a finder window, and select the paper to import from there. I think this would be helpful as currently, I need to go to finder, open the folder where the paper is stored, and drag the paper into paperlib from there, instead of having all the import operations done inside the paperlib app. 

Thank you for your app! I really like it!

**Comment by GeoffreyChen777** [comment]
That's an easy-to-implement feature. We have all the necessary APIs. If you cannot wait for us to implement this, you can even implement by yourself via an extension.

Just use these two API:

`PLMainAPI.fileSystemService.showFilePicker()` + `PLAPI.paperService.create(...)` and register a command or a contextmenu item.

https://paperlib.app/en/extension-doc/plapi/paper-service.html#create

**Comment by GeoffreyChen777** [comment]
@lcandy2 try this?

**Comment by GeoffreyChen777** [comment]
Implemented
