### ISSUE TITLE
Cannot find the paperlib extension in MS Word Add-in store

### ISSUE THREAD

**Issue by zqxiao2001** [Future-Scholars/paperlib#568]
![](https://zqxiao.oss-cn-beijing.aliyuncs.com/202406200047486.png)

**Comment by GeoffreyChen777** [comment]
请按照这个

https://paperlib.app/cn/doc/extensions/msword-extension.html

**Comment by zqxiao2001** [comment]
> 请按照这个
> 
> https://paperlib.app/cn/doc/extensions/msword-extension.html

感谢！刚刚没理解文档的“插件市场”指的是什么，以为是MS WORD的add-in store。是否需要在文档种强调一下，是用paperlib软件内的插件市场。

**Comment by GeoffreyChen777** [comment]
MS WORD 的插件市场上架需要给MS保护费，奈何没钱 🤣

**Comment by zqxiao2001** [comment]
不过我以管理员身份运行paperlib安装插件，并没有在Word看到新增插件哦。是不是我哪里操作不当。Word 2021版
![](https://zqxiao.oss-cn-beijing.aliyuncs.com/202406200101415.png)

**Comment by GeoffreyChen777** [comment]
2021 不知道支不支持，你可以重启下 word 试试，
 现在我测试支持的是 MS Office 365。我这只有订阅的 365。

**Comment by zqxiao2001** [comment]
> 2021 不知道支不支持，你可以重启下 word 试试， 现在我测试支持的是 MS Office 365。我这只有订阅的 365。

好的，感谢，我再调一调

**Comment by zqxiao2001** [comment]
请问大佬有计划开发WPS的插件嘛？

**Comment by GeoffreyChen777** [comment]
我并不清楚 WPS 兼不兼容 Word 插件，如果兼容，你可以尝试加载，否则就不行。

我个人不使用不太了解 WPS，Word 也几乎不用。所以无法帮到你。

如果你愿意为这个功能贡献代码，非常欢迎。

**Comment by GeoffreyChen777** [comment]
我暂时关闭这个issue，如果有任何想要继续讨论的，欢迎重新开启。
