### ISSUE TITLE
[BUG] Open default sample failed.

### ISSUE THREAD

**Issue by HaoxuanGuo** [Future-Scholars/paperlib#569]
**Describe the bug**
Can not open default sample by double clicking nor space.

**To Reproduce**
1. Double click the default item.
2. See error

**Screenshots or Log**
<img width="1552" alt="截屏2024-06-25 16 13 15" src="https://github.com/Future-Scholars/paperlib/assets/13018380/feb7aab3-67c4-47c4-9dbb-bf752b38c18e">
<img width="922" alt="截屏2024-06-25 16 14 35" src="https://github.com/Future-Scholars/paperlib/assets/13018380/0a9d1386-6b6f-4fbd-8066-7e9cca9dde14">

**System (please complete the following information):**
 - OS: macOS Apple Sillicon Somoma 14.5
 - Paperlib Version 3.1.5

**Additional context**
Sorry for the screenshot in Chinese.

**Comment by GeoffreyChen777** [comment]
this is not a bug. As there is no file for this demo item, you cannot open it. Just delete this demo item.
________________________________
From: Haoxuan Guo ***@***.***>
Sent: Tuesday, June 25, 2024 9:17:57 AM
To: Future-Scholars/paperlib ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Future-Scholars/paperlib] [BUG] Open default sample failed. (Issue #569)


Describe the bug
Can not open default sample by double clicking nor space.

To Reproduce
Steps to reproduce the behavior:

  1.  Double click the default item.
  2.  See error

Screenshots or Log
2024-06-25.16.13.15.png (view on web)<https://github.com/Future-Scholars/paperlib/assets/13018380/feb7aab3-67c4-47c4-9dbb-bf752b38c18e>
2024-06-25.16.14.35.png (view on web)<https://github.com/Future-Scholars/paperlib/assets/13018380/0a9d1386-6b6f-4fbd-8066-7e9cca9dde14>

System (please complete the following information):

  *   OS: macOS Apple Sillicon Somoma 14.5
  *   Paperlib Version 3.1.5

Additional context
Sorry for the screenshot in Chinese.

**Comment by HaoxuanGuo** [comment]
Is it better to show a more friendly info to users?
