### ISSUE TITLE
[BUG] Nothing happened after calling AI

### ISSUE THREAD

**Issue by HaoxuanGuo** [Future-Scholars/paperlib#570]
**Describe the bug**
Nothing happened after calling AI except a very short loading circle.

**To Reproduce**
1. Select a paper.
2. Right click.
3. Click "AISummaryExt - summary"
4. Get bug.

**Screenshots or Log**
Sorry, no.

**System (please complete the following information):**
 - OS: macOS Apple Sillicon Sonoma 14.5
 - Paperlib Version 3.1.5

**Additional context**
N/A

**Comment by GeoffreyChen777** [comment]
You must setup your API key in the preference of this extension.

BTW. For issues related to extensions, please open in the corresponding github.

https://github.com/Future-Scholars/paperlib-ai-summary-extension
