### ISSUE TITLE
[Question] 打开云同步 metadata 后论文消失

### ISSUE THREAD

**Issue by cntommy** [Future-Scholars/paperlib#574]
打开云同步 metadata 后，在合并本地云端数据库选项点击合并之后，paperlib 中之前的论文和标签都消失了，请问怎么办呢？还能恢复嘛？

**Comment by GeoffreyChen777** [comment]
1. 你的本地数据永远存放在库文件夹里。也就是pdf的同文件夹。只要你不删除一直在。为了显示本地数据，请：登出云同步，保证你的库文件夹选择的是你之前的文件夹。
2. 为了防止你丢数据，你可以备份库文件夹里所有realm相关的文件。
3. 你云同步失败应该是你数据库没设置好。请按照教程仔细设置，错误可以在mongodb atlas里的logs页面看。

**Comment by GeoffreyChen777** [comment]
如果你持续无法设置好，可以加我微信我可以帮你，geoffreychen777
