### ISSUE TITLE
[Feature Request] Find and remove/merge duplicates

### ISSUE THREAD

**Issue by yassineS** [Future-Scholars/paperlib#575]
Hello,

After Importing several papers in PDF and bib formats, I end up with 2 or more copies (sometimes) of the same manuscript, with no clear way of bulk deleting or merging duplicates.

Thank you,
Y

**Comment by GeoffreyChen777** [comment]
Identical paper should only be inserted into the database once. Could you please check if the title,author, and publication venue are exactly identical?

There are some cases you will get ‘duplicated’ items such as the titles of the scraped metadata are slightly different, for example: ‘TitleABC’ and ‘TitleABC.’

**Comment by yassineS** [comment]
It imported the same bib file twice.

**Comment by GeoffreyChen777** [comment]
Hi, if you'd like to find any potential duplicated papers in your library, please use the command `\find-duplicates` in the command bar (i.e., the search bar)

If you don't have such a command in your Paperlib, please upgrade the `paperlib-metadata-scrape-extension`.

**Comment by GeoffreyChen777** [comment]
I'm going to close this as this has been implemented. Feel free to reopen if you have any further questions about this.
