### ISSUE TITLE
[BUG] Importing Paper by Chrome Extension Leads to Wrong Title and Metadata

### ISSUE THREAD

**Issue by ChangeFWorld** [Future-Scholars/paperlib#576]
**Describe the bug**
There may be something wrong with the title and metadata of a paper, when importing by chrome extension

**To Reproduce**
The paper's source website is [https://arxiv.org/abs/2309.05027](https://arxiv.org/abs/2309.05027)

**Screenshots or Log**
![image](https://github.com/Future-Scholars/paperlib/assets/90496029/8526d0e2-f967-44aa-b47f-f34cb79991fd)

![image](https://github.com/Future-Scholars/paperlib/assets/90496029/58b3ba2b-8d28-47db-a590-95c808e2129d)

**System (please complete the following information):**
 - OS: win10
 - Paperlib Version 3.1.6
 - Paperlib Extension 1.0.3

**Comment by GeoffreyChen777** [comment]
<img width="853" alt="image" src="https://github.com/Future-Scholars/paperlib/assets/14183213/df0ff7a6-5e51-40ff-9e49-7cdefd1c791c">

For me, everything looks ok.

Please try to rescrape the metadata for this paper by right-clicking - scrape.

There might be some reason for this issue:

- the network connection between your PC and our metadata server is not good.
- the network connection between your PC and the arxiv server is not good.

If the paper has a arxiv id, we first scrape the arxiv database to get some basic metadata such as the title and authors.

**Comment by ChangeFWorld** [comment]
> <img alt="image" width="853" src="https://private-user-images.githubusercontent.com/14183213/346869291-df0ff7a6-5e51-40ff-9e49-7cdefd1c791c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODg5OTEsIm5iZiI6MTcyMDU4ODY5MSwicGF0aCI6Ii8xNDE4MzIxMy8zNDY4NjkyOTEtZGYwZmY3YTYtNWU1MS00MGZmLTllNDktN2NkZWZkMWM3OTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA1MTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMjc4NTQ3N2Y3YWM5MmJkM2JkZTNlNzMwZjM0MGRiZWI0Y2E0YTViODY0YzM4MTU4MDY1OWMyZmU5N2I0ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Eh2nUlwbXjJlzVcGyX0LCEehd0N_-jBujrtQZv4aTA">
> For me, everything looks ok.
> 
> Please try to rescrape the metadata for this paper by right-clicking - scrape.
> 
> There might be some reasons for this issue:
> 
> * the network connection between your PC and our metadata server is not good.
> * the network connection between your PC and the arxiv server is not good.
> 
> If the paper has an arxiv id, we first scrape the arxiv database to get some basic metadata such as the title and authors.

Thank you!
