### ISSUE TITLE
[BUG] Add 'online resources' has bug

### ISSUE THREAD

**Issue by yhgalaxy** [Future-Scholars/paperlib#577]
**Describe the bug**
Add 'online resources' has bug. If I add one, it will override those I've added before or auto fetched. So I can't edit url of these resources.

**To Reproduce**
1. The paper has some online resources.
![image](https://github.com/Future-Scholars/paperlib/assets/130375321/f849ea4d-1ab6-4b88-9d68-c49154a574db)
1. Go to 'edit'
1. Click on 'advanced'
![image](https://github.com/Future-Scholars/paperlib/assets/130375321/50f4d3ed-c4ac-4945-9746-933bed82ba3c)
1. There are no urls of existed online resources.
![image](https://github.com/Future-Scholars/paperlib/assets/130375321/e2678dba-3adb-420a-8985-57aac5cd2315)
1. Click '+' to add one and save.
![image](https://github.com/Future-Scholars/paperlib/assets/130375321/32b97b2d-b811-4618-9b0e-a0e71c37e064)
1.  Online resource of the paper is only one that I've added just now. Others are all deleted.
![image](https://github.com/Future-Scholars/paperlib/assets/130375321/4c23b2c5-e8e5-485e-8a7e-fdf85cad450f)

**Screenshots or Log**
If applicable, add screenshots or log to help explain your problem.

**System (please complete the following information):**
 - OS: Windows 11
 - Paperlib Version 3.1.6

**Comment by GeoffreyChen777** [comment]
Thanks for reporting this, will fix in the next version.

**Comment by yhgalaxy** [comment]
> Thanks for reporting this, will fix in the next version.

Ok, thanks.

**Comment by GeoffreyChen777** [comment]
This has been fixed now.
