### ISSUE TITLE
[Feature Request] Ask one more time before deleting folder

### ISSUE THREAD

**Issue by lvjonok** [Future-Scholars/paperlib#579]
To be honest, I am not sure whether this is a bug or a feature request, but I have encountered a situation where one can easily delete a folder with papers. Personally, I was trying to select `edit` and suddenly hit `delete`.

The folder was removed immediately, and I think it is unfortunate to lose information this way. Could you consider adding an additional check to confirm the removal of the directory?

I am not very proficient in TypeScript, but I can give it a try if you are short on time.

**Comment by GeoffreyChen777** [comment]
Do you mean the folder in the left sidebar?

**Comment by lvjonok** [comment]
> Do you mean the folder in the left sidebar?

Yes

**Comment by GeoffreyChen777** [comment]
Let me ask if @igoogolx is free to implement this.

@igoogolx Do you have time to implement this feature? I'm working on a big change, to move all services from the renderer process to a separate process, and disable `nodeItegration`.

**Comment by igoogolx** [comment]
Sure, I will take this.

**Comment by GeoffreyChen777** [comment]
@igoogolx thanks, currently we have a confirmation window for paper deleting, you can borrow the UI style in that component.

**Comment by GeoffreyChen777** [comment]
Implemented, will be released with the next update.
