### ISSUE TITLE
[Question] iCloud & MongoDB 同步问题

### ISSUE THREAD

**Issue by Lightblues** [Future-Scholars/paperlib#583]
1. 问题描述: 有两台笔记本同时打开paperlib, iCloud同步, 发现之前最近添加的paper没有显示; 检查iCloud文件夹是有pdf的 —— 请问是否是因为那个 .realm 只能单个读取造成了冲突? 另外发现同一篇论文有多个pdf, 应该也是该问题?
<img width="795" alt="image" src="https://github.com/user-attachments/assets/84751c9c-92c2-41f1-86d0-2cc763f6a263">
2. 尝试根据教程用mongdb同步metadata (pdf保留icloud), 在点击「合并」之后会有一系列的提醒和报错; 重启paperlib小之后发现远程应该没有同步到本地的数据. (启动的时候会显示login但是要等很久, 最后能进主界面, 关联 #393 
<img width="272" alt="image" src="https://github.com/user-attachments/assets/9e3569dc-b0d3-465f-a727-309e3ce1452a">

**Comment by Lightblues** [comment]
另, 对于图1的问题是否可增加「删除多余的文件」or「检查pdf文件列表」的功能?

**Comment by GeoffreyChen777** [comment]
首先绝不可以使用网盘类比如icloud 进行数据的云同步，因为会有文件锁，造成冲突。

其次关于你设置云同步，我不清楚你是否成功，建议检查云数据库的log确认，再继续后续操作。

可以加我微信我帮助你。geoffreychen777

**Comment by ChangeFWorld** [comment]
我有个类似的问题，不过我只是在单一设备上使用，打开了mongodb备份metadata；之前几个月没有发现异常，最近发现有时新加的paper会马上消失（加进来了，但是几秒后就没有了），但是paperlib目录下的pdf文件还在，再次添加该paper会引入重复的pdf；我猜测是由于网络问题没有和mongodb通信成功，不确定是不是bug

https://github.com/user-attachments/assets/5c7721f3-0c3f-4764-b563-65768d8808b4

**Comment by GeoffreyChen777** [comment]
@ChangeFWorld 同样欢迎加我微信我帮你解决。
