### ISSUE TITLE
使用网页插件添加的条目无法获得PDF文件

### ISSUE THREAD

**Issue by meowpass** [Future-Scholars/paperlib#585]
当使用网页插件尝试import新条目并下载对应PDF时，条目引入成功，但是并没有获得相应的PDF文件。
右下角报错：
* FileService 
Failed to move files of a paper entity
Error: EXDEV: cross-device link not permitted, rename '.....

此时条目存在，尝试打开论文显示：
* FileService
URL should have a protocol

请问一下这种情况我应该如何解决？还是我使用网页插件的方式存在问题？

系统：Windows11
Paperlib版本：Version 3.1.7
问题复现：以arxiv论文为例，进入论文对应的arxiv界面后，点击插件，勾选Download PDF并import

**Comment by GeoffreyChen777** [comment]
你的库文件夹应该和你的下载文件夹不是一个盘吧？

**Comment by meowpass** [comment]
> 你的库文件夹应该和你的下载文件夹不是一个盘吧？

是的，我的库文件夹设置为D盘的Onedrive文件夹而网络插件下载文件夹在C盘的用户文件夹下的downloads。问题应该是不允许跨盘的复制
尝试将库文件夹设置为下载文件夹后解决问题。
感谢作者。尝试修改默认下载路径到D盘或许可以解决问题

**Comment by GeoffreyChen777** [comment]
这个问题已经修复了，只是还没发新版。
我现在发新版。
你等待10分钟，更新新版就可以解决。

**Comment by meowpass** [comment]
> 这个问题已经修复了，只是还没发新版。 我现在发新版。 你等待10分钟，更新新版就可以解决。

感谢作者！

**Comment by GeoffreyChen777** [comment]
更新后应该没问题了。如有问题请在这告诉我。

**Comment by JiaWang0704** [comment]
作者您好，
我的系统： mac，
paperlib 版本：3.1.10

我按照您说的，将网页下载的文件和库文件放在了一个文件下，仍然出现了这个问题，请问有什么解决办法？
