### ISSUE TITLE
DOI导入

### ISSUE THREAD

**Issue by cxvzerox** [Future-Scholars/paperlib#586]
是否考虑增加通过DOI方式导入文件

**Comment by GeoffreyChen777** [comment]
你好，doi如何导入文件呢？你是说直接通过doi添加论文条目？

那对应的pdf期望是自动下载还是？

**Comment by GeoffreyChen777** [comment]
暂时关闭因长期不活跃。如需继续请重开。

**Comment by cxvzerox** [comment]
通过doi添加论文条目，附件则由自己上传或者只需要生成条目便于在word引用。
