### ISSUE TITLE
[BUG] Notifications Screen Cannot Be Closed on Windows

### ISSUE THREAD

**Issue by relic-yuexi** [Future-Scholars/paperlib#590]
**Describe the bug**
After installation, the application enters a new user guide. However, the Notifications screen cannot be closed, blocking other operations.

**To Reproduce**

1. Install the application on a Windows platform.
2. Follow the new user guide.
3. Arrive at the Notifications screen.
4. Attempt to close the Notifications screen.
5. Observe that the Notifications screen remains open and blocks other operations.

**Screenshots or Log**

![image](https://github.com/user-attachments/assets/82f9b7b1-e6dc-48b6-aeff-0ebaf7b25873)

![image](https://github.com/user-attachments/assets/683718b7-5171-4dbd-bb5c-5728a4dd3610)

**System (please complete the following information):**
- OS: Windows
- Paperlib Version: 3.1.8

**Additional context**
This issue occurs immediately after installation and during the initial user guide. The Notifications screen can not touch the visible close button or any other apparent way to dismiss it, making it impossible to proceed with other tasks in the application.

**Comment by GeoffreyChen777** [comment]
Thanks. The reason is that the notification should appear after the new user guide.

I will fix this.

Currently, you can go through all new user guide, after that , you can click the button in the notification view.

**Comment by GeoffreyChen777** [comment]
This has been fixed now.

The notification now appears when you import the first paper with the newest extension version.
