### ISSUE TITLE
[Feature Request] Request to Add Paperlib to Scoop Bucket

### ISSUE THREAD

**Issue by p455enger** [Future-Scholars/paperlib#591]
Hello Paperlib Maintainers,

I hope this message finds you well. I'm writing to request adding Paperlib to a Scoop bucket. Scoop is a popular command-line installer for Windows, making it easy to install and manage software.

Adding Paperlib to a Scoop bucket would provide the following benefits:

- Ease of Installation: Users can install and update Paperlib with a single command.
- Wider Reach: Being part of the Scoop ecosystem could introduce Paperlib to more developers and users.
- Simplified Updates: Users can benefit from automatic version checking and updates.

Please consider this request, and let me know if more information is needed.

---

您好，Paperlib 维护者，

我写这封信是想请求将 Paperlib 添加到 Scoop 软件源。Scoop 是一个流行的 Windows 命令行安装工具，使得软件的安装和管理变得非常简单。

将 Paperlib 添加到 Scoop 软件源将带来以下好处：

- 简化安装：用户可以通过一个命令安装和更新 Paperlib。
- 扩大影响：成为 Scoop 生态系统的一部分可以让更多的开发者和用户接触到 Paperlib。
- 简化更新：用户可以受益于自动版本检查和更新。

请考虑这个请求，如果需要更多信息，请告诉我。

**Comment by GeoffreyChen777** [comment]
you can use this one:

https://github.com/hoilc/scoop-lemon

**Comment by p455enger** [comment]
> you can use this one:
> 
> https://github.com/hoilc/scoop-lemon
Help a lot . Thanks !
