### ISSUE TITLE
[Feature Request] Add papers using URL path

### ISSUE THREAD

**Issue by shoham-elad** [Future-Scholars/paperlib#592]
Currently, The primary way to add a paper is to download and then drag it.

The feature I am suggesting is to type \add <url.to.arxiv.or.whatever> to automatically download and add it to paperlib.

**Comment by GeoffreyChen777** [comment]
1. For URL, you can use the browser extension.
<img width="570" alt="image" src="https://github.com/user-attachments/assets/3228bd2a-a913-49f9-a28d-b778258149e1">

2. For Arxiv IDs, DOIs, you can use `\import-from`, for example:
```
\import-from 2403.16276;10.1109/tpami.2024.3367416;Audio-Visual LLM for Video Understanding
```

**Comment by shoham-elad** [comment]
Thanks for the swift reply.
I was thinking of a simpler URL from which you can download the PDF.

**Comment by GeoffreyChen777** [comment]
what is a simpler URL?

**Comment by shoham-elad** [comment]
I mean that I would like the following command to work `\add https://arxiv.org/pdf/2007.04937`
![image](https://github.com/user-attachments/assets/4f029a8b-00ce-4be0-b151-77da85e4d772)

It's less desirable to go to the source of the paper and find the DOIs.

**Comment by GeoffreyChen777** [comment]
For arxiv, you can use `\import-from 2007.04937`

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/bc0e5f31-e81f-4562-bb3f-025e9e17e64f">

**Comment by GeoffreyChen777** [comment]
Or you can open this URL in your browser, and use the browser extension to import papers into paperlib.

**Comment by shoham-elad** [comment]
I want to use the URL through the command and not the ID.
Using the extension is less desirable.

The motivation to not use the extension is:
too many extensions cause the browser to be bloated. Additionally, if a hosted version of paperlib will be released, then I will have to download the extension on every environment I use. 

The motivation to not use the ID:
Sometimes, it's not from arxiv, and you can not swiftly extract an ID or DOI (if even possible to extract). Furthermore, sometimes, I add lecture notes or papers under review from the open review, and then they might not have these attributes.

The emphasis of this feature is to receive a link with a PDF (only), and add it to paperlib. 
This should "automate" the manual task of 
1 finding a pdf
2 downloading it
3 dragging its

**Comment by GeoffreyChen777** [comment]
OK, then it's a feature request to https://github.com/Future-Scholars/paperlib-entry-scrape-extension

Please open an issue and track it there.
