### ISSUE TITLE
[Feature Request] Option to disable "_id" for PDF renaming

### ISSUE THREAD

**Issue by pratch** [Future-Scholars/paperlib#595]
I am wondering what the significance of the long id (e.g. 6629ff14d803c6c662099f77) in the file name is, and if there is a way to disable it? I assume that it is used for some internal working of paperlib, but it makes the file names super long and look rather messy.

**Comment by GeoffreyChen777** [comment]
No, there is no way to disable it.

ID is the unique identifier of a paper. The default renaming format is `title_id.pdf`. Papers may have identical titles. Without a unique id, two papers with the same title will point to a single PDF.

**Comment by pratch** [comment]
That may be a simple solution to the title conflict issue, but 24-character long ID is still pretty overkill and user-unfriendly IMHO. How about these alternatives: 
- Use shorter IDs. Would simple running numbers 0001, 0002,... work?
- Force append author/year for files with title conflict
- Handle uniqueness internally in the db

You mentioned in another issue that we should not access the PDF folder directly and only via the app, but say, in order to annotate the PDF on an ipad, we still need to access the folder via maybe gdrive, and it will be quite difficult to find files with current, limited way of naming.

**Comment by GeoffreyChen777** [comment]
1. The ID is the one used in the backend database. which is not an increasing number.
2. This solution still cannot fully avoid conflict.
3. Can't, in database, each paper is an item:
```
{
id: xxxxxx;
title: xxxx;
author: xxxxx,
.....
mainFileURL: /path/to/the/pdf.
}
```

It requires the URL for each item should be unique.

---

I would suggest using a custom renaming format like this:

```
{year}/{publication}/
```

to orgnise your folder, although it's not a very decent way. 

---

We are planning to create a self-host webpage version, I believe using paperlib in iPad browser could finally solve your problem. Stay tuned.
