### ISSUE TITLE
[Question] PAPERLIB not able to open without internet

### ISSUE THREAD

**Issue by wadesnoopy** [Future-Scholars/paperlib#598]
This software is outstanding for organizing papers!

I followed the instructions to sync metadata via MongoDB and files through Dropbox. Everything functions seamlessly when syncing between my two MacBooks. However, when I was offline, PAPERLIB became unresponsive upon launch. From the attached screenshot, it seems to be attempting to load the MongoDB data and other extensions. Without an internet connection, it fails to open. It would be good to have offline functionality (at least I can open the software).

Could this be a bug on my end? Any assistance would be greatly appreciated. Thank you!

<img width="1320" alt="Screenshot 2024-08-22 at 3 46 58 PM" src="https://github.com/user-attachments/assets/8b9e5366-1bd4-4b7d-b028-366890bde508">

**Comment by GeoffreyChen777** [comment]
Hi, it's expected.

If you have already opened paperlib, then disconnect from the internet, everything will be fine. You can use paperlib as usually, and when you reconnect to the internet, your modification to the database will upload to the cloud database (the conflict will be merged automatically).

However, if you disconnect first, then open paperlib, the current version will get stuck at the login step.

We have already found a solution. We will release the patch in the future version.

**Comment by wadesnoopy** [comment]
Cool! Yep. Just tested and it behaves exactly as you said. I find one solution but not ideal (using phone hotspot to open it when internet is gone, in case I accidentally close it beforehand). Looking forward to the next version! Thanks.

**Comment by GeoffreyChen777** [comment]
The new version was released.

**Comment by wadesnoopy** [comment]
Thank you so much! Tested and it works nice!!!
