### ISSUE TITLE
[Question] Mainview author first name and last name order

### ISSUE THREAD

**Issue by wadesnoopy** [Future-Scholars/paperlib#600]
Hello,

I noticed that the General tab allows us to change the local file name using the "Renaming Format," with the option to arrange names as "{lastname}, {firstname}". I'm interested in having a similar format for the Authors displayed in the Mainview, where the default is currently "Firstname Lastname." Is there a possibility to introduce an option for viewing names as "Lastname, Firstname" for all the authors in the Mainview? I understand this might not be everyone's preference, but I would appreciate the flexibility if it's feasible.

Thank you.

**Comment by GeoffreyChen777** [comment]
Currently, we don't have such a feature.

The main view is just showing the author string in the database. Usually, the database store 'First Last'. If you prefer 'Last, First', you can write an extension to transform all the author strings into your preferred format.

https://paperlib.app/en/extension-doc/

We won't implement such a very private feature.

**Comment by wadesnoopy** [comment]
Understood! That sounds great. Thanks.
