### ISSUE TITLE
[Feature Request] For newest version of papers on arxiv

### ISSUE THREAD

**Issue by MYM181** [Future-Scholars/paperlib#604]
**Describe your feature request**
...
Hi. I recently find that sometimes it's hard to grasp the newest version of papers on the arxiv, as some papers have multiple versions upgrading.
I like your appa lot, and I use it all day. 
Hope you can make this better. It will be eaiser to use. 
Thanks!

**Comment by GeoffreyChen777** [comment]
![image](https://github.com/user-attachments/assets/1bf26bb8-a04f-47ca-8921-af82b21b7a81)
Click this should open the webpage for the latest version.

**Comment by MYM181** [comment]
Fine. It helps a lot!

**Comment by MYM181** [comment]
> ![image](https://private-user-images.githubusercontent.com/14183213/363412868-1bf26bb8-a04f-47ca-8921-af82b21b7a81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDcwNzcsIm5iZiI6MTcyNTEwNjc3NywicGF0aCI6Ii8xNDE4MzIxMy8zNjM0MTI4NjgtMWJmMjZiYjgtYTA0Zi00N2NhLTg5MjEtYWY4MmIyMWI3YTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyMTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MzI1MjM1MTI4MDEzNDU3NWZhNGE0ZmIyZDY4YmY3OWE0NWVmYjhkN2Y5MDY4MmRkMWNkOTcyNGQ1OGRhMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vn0GKAlhDDSvnGKX5QPePlWxsn5R45krtk7BjGBo8ZU) Click this should open the webpage for the latest version.

Fine. It helps a lot! Thank you.
