### ISSUE TITLE
Deprecation of Device Sync in Atlas App Services - Migration Required

### ISSUE THREAD

**Issue by zhai-lw** [Future-Scholars/paperlib#607]
Device Sync from Atlas App Services has been marked for deprecation. According to the [official MongoDB documentation](https://www.mongodb.com/docs/atlas/app-services/sync/device-sync-deprecation/), Device Sync will be deprecated as of September 2024 and will be fully removed on September 30, 2025.

**Comment by GeoffreyChen777** [comment]
WTF. That’s really a bad news. Thanks for telling us.

**Comment by GeoffreyChen777** [comment]
I will discuss this with other contributors in #608, feel free to track it there if you want.
