### ISSUE TITLE
[Feature Request] Sync webdav in one click.

### ISSUE THREAD

**Issue by HaoxuanGuo** [Future-Scholars/paperlib#610]
Is it possible to sync (upload) webdav in one click?

The current sync is lazy which means it will only sync the item which has been operated. When a user want to setup on another device, it will found the paper it want to read has not been uploaded nor not downloadable.

To avoid this condition, is it possible to upload all files on one click?

**Comment by GeoffreyChen777** [comment]
How long will it take before uploading?

**Comment by HaoxuanGuo** [comment]
@GeoffreyChen777 Sorry I can not understand your question.

There are 252 items.

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/7016bdda-b4d2-4dfb-8a50-c0ecd2e9f0c4">

There are 12 items.

<img width="1322" alt="image" src="https://github.com/user-attachments/assets/1b75795a-5abb-4b6a-b88e-2ccb1bd656ca">

The upload process only run when I click an item. Nothing will happen if I only put the software idling. So I can not answer the question "how long".

**Comment by GeoffreyChen777** [comment]
The file uploading will trigger immediately after you drag a PDF in paperlib. If not, there must be something wrong.

You can share me the log file. `~/Library/Logs/paperlib/`

**Comment by HaoxuanGuo** [comment]
When I set up webdav, there were already a lot of files in the database. These old files will not be automatically uploaded. I haven't tried to drag in new files yet.

Here are the logs.

[extension.log](https://github.com/user-attachments/files/16994270/extension.log)
[main.log](https://github.com/user-attachments/files/16994275/main.log)
[renderer.log](https://github.com/user-attachments/files/16994276/renderer.log)

**Comment by GeoffreyChen777** [comment]
yes that's the problem.

The webdav will watch the library folder, if there is any file creating, deleting, editing, we do the sync.

Currently, you can first, delete all files on your webdav, then copy PDFs out of your library folder, and then paste it back.

**Comment by HaoxuanGuo** [comment]
Is it possible to add a sync function triggered by manual or when webdav config changed?

**Comment by GeoffreyChen777** [comment]
sorry, for now, we don't have this function.

**Comment by HaoxuanGuo** [comment]
Close due to won't implement.
