### ISSUE TITLE
[Feature Request] Quick search for tags

### ISSUE THREAD

**Issue by fkcptlst** [Future-Scholars/paperlib#611]
**Describe your feature request**

Tags can be a bit messy when importing paper or grouping paper. It would be nice if I could do a quick search.

<img width="314" alt="image" src="https://github.com/user-attachments/assets/45ecc1c5-a859-42f1-a0bc-7a034683a840">

**Comment by GeoffreyChen777** [comment]
Yes, agree, will enhance this soon.

**Comment by GeoffreyChen777** [comment]
implemented, please wait for the next release.
