### ISSUE TITLE
[Bug] Sort key bug

### ISSUE THREAD

**Issue by nvv1d** [Future-Scholars/paperlib#613]
Why did I suddenly get this error? everything was perfect and then:
RealmError RealmError: Cannot sort on key path 'feed': property 'PaperEntity.feed' does not exist. ...

Can't access anything in the app.

**Comment by GeoffreyChen777** [comment]
Try to close and reopen paperlib?

**Comment by nvv1d** [comment]
I did, I even uninstalled and reinstalled it. Same error.

**Comment by GeoffreyChen777** [comment]
What is your OS, windows? macOS?

**Comment by nvv1d** [comment]
I'm on Windows 11.

**Comment by GeoffreyChen777** [comment]
Go to `%APPDATA%/paperlib/`. There is a file `config.json`. Open it, check `mainviewSortBy`, `sidebarSortBy`.

**Comment by nvv1d** [comment]
> 	"sidebarSortBy": "name",

> 	"mainviewSortBy": "feed",

not sure what to check but here they are.

**Comment by GeoffreyChen777** [comment]
`"mainviewSortBy": "feed"`, -> `"mainviewSortBy": "addTime"`

Then reopen paperlib.

**Comment by nvv1d** [comment]
Worked like a charm. Thank you. But why did this happen?

**Comment by GeoffreyChen777** [comment]
It's a bug, when you sort the feed view by feed name, but never switch back to the library view before you close the paperlib, the `mainviewSortBy` will never restore. You cannot sort the main view with `feed` as the key.

**Comment by GeoffreyChen777** [comment]
fixed.
