### ISSUE TITLE
[BUG] Typo on the Chrome Extension

### ISSUE THREAD

**Issue by WissenY** [Future-Scholars/paperlib#615]
**A Typo on the Chrome Extension**
It may be `whether` but not `weather` when import papers from websites.
![CleanShot 2024-09-24 at 17 52 55@2x](https://github.com/user-attachments/assets/474fdcea-6ac5-4dbc-88ad-b2d9bb2f14b4)

**Comment by GeoffreyChen777** [comment]
fixed. Please wait for the next release.
