### ISSUE TITLE
[BUG] 无法删除标签和smart过滤器；无法为标签更换颜色

### ISSUE THREAD

**Issue by manson6616** [Future-Scholars/paperlib#617]
**Describe the bug**
无法删除标签和smart过滤器；
无法为标签更换颜色

**To Reproduce**

**Screenshots or Log**

**System (please complete the following information):**
 - OS: macOS 14.4 (23E214)
 - Paperlib Version 版本3.1.9 (3.1.9)

**Additional context**

**Comment by GeoffreyChen777** [comment]
无法复现，试试重启?

**Comment by manson6616** [comment]
重启正常了，感谢回复
