### ISSUE TITLE
[Feature Request] Possible interactive logic improvement for adding papers to specific folders

### ISSUE THREAD

**Issue by KevinWu2017** [Future-Scholars/paperlib#622]
**Describe your feature request**
...
Thanks for developing such amazing application.

I’ve encountered an issue when adding papers to a specific folder in Paperlib. After selecting the desired folder and dragging a paper into it, the paper does not appear in the folder.

It seems that the interactive logic could be improved to ensure that the paper is automatic classified into the corresponding folder after being added.

**Comment by GeoffreyChen777** [comment]
When you click the folder in the left panel, you are not really opening a folder. It's just a filtering query.

For example, when you click `FolderA`, the database will get a query like `folder.name == 'FolderA'`, then the main view shows the filtered results.

It means that you can use Control to combine several queries, such as `Ctrl + Click FolderA + Click FolderB + Click TagA`

As a result. currently we cannot implement your feature request.
