### ISSUE TITLE
元数据检索功能全部实效了?

### ISSUE THREAD

**Issue by Haifeng-Dai** [Future-Scholars/paperlib#623]
无法通过任何方式检索元数据，我看网页上的服务状态也全部不在线。

另外，有没有备选的多设备同步方案啊，大部分网盘都不同步.lock文件。

**Comment by GeoffreyChen777** [comment]
话说我试了下，服务没崩，只是监控网页崩了。你检索不到元数据吗？比如哪个文章？

**Comment by Haifeng-Dai** [comment]
[Mu2023 - FedProc Prototypical Contrastive Federated Learning on Non-IID Data.pdf](https://github.com/user-attachments/files/17917915/Mu2023.-.FedProc.Prototypical.Contrastive.Federated.Learning.on.Non-IID.Data.pdf)
这个文章，我拖到软件里显示如图
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/91da622a-c84b-40e8-967c-86b676501d8f">
然后右键检索元数据都不行，但是它识别到DOI了，插件如图
<img width="720" alt="image" src="https://github.com/user-attachments/assets/eb0cade3-201a-4121-be32-d2dda131d629">

**Comment by GeoffreyChen777** [comment]
我可以哎

<img width="398" alt="image" src="https://github.com/user-attachments/assets/653f33e6-4135-4b85-88bc-97a6c769a2a3">

看下你的网络？浏览器打开这个是啥？
https://metadata.paperlib.app/query?sources=doi&doi=10.1016/j.future.2023.01.019&secret=future-scholars

**Comment by GeoffreyChen777** [comment]
证明你的网络没问题。那你邮件重新搜索的时候，左下角有什么红色提示出现不？

**Comment by GeoffreyChen777** [comment]
或者你直接加我微信，沟通方便 https://share.1password.com/s#qxwFwE1Smt5NwMyH14BY67RdKWHLjrr_6Qu4bGqzS2E

**Comment by Haifeng-Dai** [comment]
没有，左下角提示出现，并很快消失
<img width="278" alt="image" src="https://github.com/user-attachments/assets/1928fa78-2be0-4c17-8c77-47328be05050">
