### ISSUE TITLE
[Feature Request] Select and export multiple documents

### ISSUE THREAD

**Issue by noirchen** [Future-Scholars/paperlib#625]
This is a very good application, and it would be better if I can select multiple entries, and export the documents to a location. This is very helpful to share relevant references to others.

**Comment by GeoffreyChen777** [comment]
1. Use ctrl to select multiple papers.
2. Press ‘alt’
3. Drag those paper out
4. Release ‘alt’
5. Release mouse

**Comment by noirchen** [comment]
Oh that's neat. Thank you.
