### ISSUE TITLE
Different papers were interpreted as duplicates.

### ISSUE THREAD

**Issue by dcandiah97** [Future-Scholars/paperlib#626]
When I try to add papers with the same name, Paperlib interprets them as duplicates, so I can only add one of them. If I have already added one and then try to add the other, the visualization of the previous paper in Paperlib disappears. The papers have differents years of publication, authors, volumes and DOI:

https://doi.org/10.3767/003158510X552636
https://doi.org/10.3767/003158509X482951

 - OS: Windows 10
 - Paperlib Version 3.1.9

Also, papers from Ingenta Connect cannot be added using the browser extension. So, I downloaded them to add them to Paperlib manually.

**Comment by GeoffreyChen777** [comment]
With this two DOI, we got two identical papers. same title, same authors.

Could you please tell me what are the authors of these two papers as you claimed they are different.

Thanks!

**Comment by dcandiah97** [comment]
Hello, thanks for your response 

Both papers are different since the first page, if you see them you could notice that.

They have different years of publication, and have no "formally authors" because the papers compile 7-12 fungal description notes from different authors.

I know that is a weird form to publish a paper, but Zotero can recognize both of them as difference.
Here are new links to the same papers:

https://pmc.ncbi.nlm.nih.gov/articles/PMC2890159/
https://pmc.ncbi.nlm.nih.gov/articles/PMC2802724/

If I a try to add both papers from these links, the same error happen.

**Comment by GeoffreyChen777** [comment]
fixed.
