### ISSUE TITLE
[BUG] Folder context menu malfunctions

### ISSUE THREAD

**Issue by zixingjiang** [Future-Scholars/paperlib#628]
**Describe the bug**
The _change color_ and _delete_ buttons in the context menu of a folder do not work when returning to the Library page from the Feeds page. 

**To Reproduce**
1. Open a new Paperlib window
2. Click the Feeds button on the left panel to enter the Feeds page
3. Click the Library button on the left panel to return to the Library page
4. Right-click a folder to toggle the context menu
5. Click the buttons in the context menu
6. See the bug

**Screenshots or Log**
See the screen recording below:
https://github.com/user-attachments/assets/3fc3e9fd-2ac1-4eac-89ee-86a1c417eeaa

**System (please complete the following information):**
 - OS: Windows 11 Pro 24H2 OS build 26100.2605
 - Paperlib Version 3.1.9 (development mode off)

**Additional context**
- This bug will not occur if a newly opened Paperlib window never enters the Feeds page
- Folder creation and editing (renaming) are not affected by this bug

**Comment by GeoffreyChen777** [comment]
reproduced. Thanks for reporting this. will fix.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Zixing Jiang ***@***.***>
Sent: Friday, December 13, 2024 6:12:12 PM
To: Future-Scholars/paperlib ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Future-Scholars/paperlib] [BUG] Folder context menu malfunctions (Issue #628)


Describe the bug
The change color and delete buttons in the context menu of a folder do not work when returning to the Library page from the Feeds page.

To Reproduce
Steps to reproduce the behavior:

  1.  Open a new Paperlib window
  2.  Click the Feeds button on the left panel to enter the Feeds page
  3.  Click the Library button on the left panel to return to the Library page
  4.  Right-click a folder to toggle the context menu
  5.  Click the buttons in the context menu
  6.  See the bug

Screenshots or Log
See the screen recording below:
https://github.com/user-attachments/assets/3fc3e9fd-2ac1-4eac-89ee-86a1c417eeaa

System (please complete the following information):

  *   OS: Windows 11 Pro 24H2 OS build 26100.2605
  *   Paperlib Version 3.1.9 (development mode off)

Additional context

  *   This bug will not occur if a newly opened Paperlib window never enters the Feeds page
  *   Folder creation and editing (renaming) are not affected by this bug

**Comment by GeoffreyChen777** [comment]
fixed.
