### ISSUE TITLE
[BUG] Tag links in the right panel don't work

### ISSUE THREAD

**Issue by zixingjiang** [Future-Scholars/paperlib#629]
**Describe the bug**
Clicking on the tag in the right panel doesn't show any papers. I think it's supposed to list all papers with that tag in the main view, just like clicking on authors and folders. Maybe something is wrong with the database query?

**To Reproduce**
1. Select a paper with tags in the main view to toggle the right panel
2. Clicking on a tag in the right panel
3. See error

**Screenshots or Log**
See the screen recording below:
https://github.com/user-attachments/assets/f74508f8-0355-4c04-a789-a98c729a6efe

**System (please complete the following information):**
 - OS: Windows 11 Pro 24H2 OS build 26100.2605
 - Paperlib Version 3.1.9 (development mode off)

**Additional context**
None.

**Comment by GeoffreyChen777** [comment]
Yes, it's a bug. I will fix it, but maybe next week caused I got covid. Thanks for reporting this.

**Comment by zixingjiang** [comment]
So sorry to hear that and wish you a speedy recovery. Many thanks for your efforts!

**Comment by GeoffreyChen777** [comment]
fixed.
