### ISSUE TITLE
[BUG] Tags disappeared in client, while remains visible in the importer

### ISSUE THREAD

**Issue by fkcptlst** [Future-Scholars/paperlib#630]
**Describe the bug**

Tags all disappeared in client, while remains visible in the importer.

**Attempt**

I have already attempted shutdown and restart the software, with little help.

**Screenshots or Log**
If applicable, add screenshots or log to help explain your problem.

<img width="241" alt="image" src="https://github.com/user-attachments/assets/cc049587-b667-4f3a-b9de-b92a27a62d1a" />

<img width="314" alt="image" src="https://github.com/user-attachments/assets/718f6590-c58e-4bb5-8f6d-f732a8f5e285" />

**System (please complete the following information):**
 - OS: macOS
 - Paperlib Version Version 3.1.9

**Comment by GeoffreyChen777** [comment]
Are you using cloud sync?

**Comment by GeoffreyChen777** [comment]
What about metadata? Mongodb Atlas?

**Comment by fkcptlst** [comment]
> What about metadata? Mongodb Atlas?

Yes, I am using Mongodb

**Comment by GeoffreyChen777** [comment]
It’s a bug. Go to the mongodb web dashboard - click Browser Collections - click PaperTag - in the Filter input box, type `{name: "Tags"}` - delete all results with zero children. 

You can also do the same thing for folders, smart filters.

**Comment by GeoffreyChen777** [comment]
fixed.
