### ISSUE TITLE
[Question] 多设备使用iCloud同步问题

### ISSUE THREAD

**Issue by yunfanzuo** [Future-Scholars/paperlib#632]
我有两台MacOS设备，在paperlib的设置中我将「存储文件夹」设为iCloud空间中的目录。此时一台设备上存储的pdf似乎不能在另一台设备上看到。
<img width="453" alt="image" src="https://github.com/user-attachments/assets/f034f58e-2811-403a-812a-d6fbffb4b62a" />

**Comment by GeoffreyChen777** [comment]
你好，你指的看不到pdf，是PDF文件没有，还是说paperlib 列表里没对应的论文？

**Comment by yunfanzuo** [comment]
> 你好，你指的看不到pdf，是PDF文件没有，还是说paperlib 列表里没对应的论文？

比如我在 A 设备中添加一篇论文，此时 iCloud 中会有对应的 pdf，但当我打开 B 设备的 paperlib 时，尽管他们都指向同一个文件夹，但 B 设备的 paperlib 中无法显示出在 A 设备上添加的论文。
我尝试在 B 设备上重新添加这篇论文，此时 iCloud 中会有两篇相同的论文，但文件名（后面的 id 部分）会有不同。

**Comment by GeoffreyChen777** [comment]
如果你是想在两个电脑间同步使用，不可以只用icloud，需要配合云同步功能。icloud 只用来同步 pdf 文件，而元数据数据库，需要通过 mongodb atlas 同步。https://paperlib.app/cn/doc/cloud-sync/setup.html

然而现在 mongodb atlas 不给用了。我们正在开发自己的同步服务器。

**Comment by GeoffreyChen777** [comment]
如有更多问题欢迎重新打开。
