### ISSUE TITLE
[Feature Request] Citation Scraper Integration

### ISSUE THREAD

**Issue by ODAncona** [Future-Scholars/paperlib#635]
**Feature Request: Citation Scraper Integration**

I propose adding a citation scraping feature to PaperLib. This would allow users to automatically retrieve citation counts for papers from different sources like Google Scholar, Semantic Scholar, Codium or OpenCitations. 

This feature would be immensely helpful for researchers who want to organize and analyze papers based on their citation metrics.

What are your thoughts?

**Comment by GeoffreyChen777** [comment]
We have an extension: `paperlib-citation-count-extension`. Try it.
