### ISSUE TITLE
请问批量下载文献，会比zotero，endnote下载更全，更完整吗

### ISSUE THREAD

**Issue by huangzsdy** [Future-Scholars/paperlib#636]
zotero, endnote的find full text 下载完成率不高，请问您这个工具，有对比过下载完成情况吗，或许可以作为一个卖点

**Comment by GeoffreyChen777** [comment]
你好，这个没有测试过。

**Comment by huangzsdy** [comment]
> 你好，这个没有测试过。

请问按照文档安装完插件后，就可以批量抓取PDF了嘛？您一般下载PDF都能下载齐全么？
![image](https://github.com/user-attachments/assets/196cabdd-182e-4750-829f-4a42bb3e12f3)
![image](https://github.com/user-attachments/assets/7ade89d9-e145-4f57-9eac-803f2c76d3f7)

尝试了，scratch, scratch from, fuzzily scratch，效果都不大好

**Comment by GeoffreyChen777** [comment]
你好，你发的这几个，只有locate是用来下载PDF。其他都是搜寻元数据的。

另外下载PDF牵扯法律版权问题。只有公开的一些PDF才能有可能下载。如果任何PDF都能下载到，怕是会被告上法庭。

**Comment by huangzsdy** [comment]
> 你好，你发的这几个，只有locate是用来下载PDF。其他都是搜寻元数据的。
> 
> 另外下载PDF牵扯法律版权问题。只有公开的一些PDF才能有可能下载。如果任何PDF都能下载到，怕是会被告上法庭。

哈哈哈哈，好的，蛮好用的，支持！！

**Comment by GeoffreyChen777** [comment]
感谢
